import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { AlertTriangle, ArrowLeftRight, BookOpen } from 'lucide-react';
import { api } from '../services/api';
import { CompetitionBadge, Empty, Loading, PageTitle, fmt } from '../components/Ui';
import ViewActions from '../components/ViewActions';
import type { Season } from '../types';

type Coverage={matches:number;completed:number|null;squad:number|null;last_verified_at:string|null};
type NormalizedSeason={points_per_match:number|null;goals_for_per_match:number|null;goals_against_per_match:number|null;win_rate:number|null};
type SeasonRecord=Season&{coverage:Coverage;normalized:NormalizedSeason};
type SeasonResponse={groups:{season:string;records:SeasonRecord[]}[];meta:{competition:string|null;competitions:string[];homogeneous:boolean;warning:string|null}};
type PlayerItem={player:{id:number;name:string;position:string|null;appearances:number|null;minutes:number|null;goals:number|null;assists:number|null};coverage:{seasons:number;with_stats:number;last_verified_at:string|null};normalized:{goals_per_90:number|null;assists_per_90:number|null;minutes_per_appearance:number|null};seasons:{season:string;competition:string;appearances:number|null;minutes:number|null;goals:number|null;assists:number|null;source_provider:string|null}[]}|null;
type PlayerResponse={items:PlayerItem[];meta:{competition:string|null;homogeneous:boolean;warning:string|null}};
const rawSeason:[keyof Season,string][]=[['final_position','Posizione'],['matches','Partite'],['wins','Vittorie'],['draws','Pareggi'],['losses','Sconfitte'],['goals_for','Gol fatti'],['goals_against','Gol subiti'],['points','Punti']];
const decimal=(value:number|null)=>value==null?'N/D':new Intl.NumberFormat('it-IT',{maximumFractionDigits:2}).format(value);

export default function Compare(){
  const[params,setParams]=useSearchParams();const[seasons,setSeasons]=useState<Season[]>([]);const[players,setPlayers]=useState<{id:number;name:string;position:string|null}[]>([]);const[data,setData]=useState<SeasonResponse|null>(null);const[playerData,setPlayerData]=useState<PlayerResponse|null>(null);
  const mode=params.get('type')==='players'?'players':'seasons',a=params.get('a')||'',b=params.get('b')||'',competition=params.get('competition')||'';
  useEffect(()=>{void api<Season[]>('/seasons').then(setSeasons);void api<{id:number;name:string;position:string|null}[]>('/players?all=1&sort=name').then(setPlayers)},[]);
  useEffect(()=>{if(!a||!b||a===b){setData(null);setPlayerData(null);return}const suffix=`enhanced=1&a=${encodeURIComponent(a)}&b=${encodeURIComponent(b)}${competition?`&competition=${encodeURIComponent(competition)}`:''}`;if(mode==='players')void api<PlayerResponse>(`/compare/players?${suffix}`).then(setPlayerData).catch(()=>setPlayerData({items:[],meta:{competition:null,homogeneous:false,warning:null}}));else void api<SeasonResponse>(`/compare/seasons?${suffix}`).then(setData).catch(()=>setData({groups:[],meta:{competition:null,competitions:[],homogeneous:false,warning:null}}));},[a,b,mode,competition]);
  const options=mode==='players'?players.map(x=>({value:String(x.id),label:`${x.name}${x.position?` · ${x.position}`:''}`})):[...new Set(seasons.map(x=>x.season))].map(x=>({value:x,label:x}));
  const competitions=[...new Set(seasons.map(x=>x.competition))].sort();
  const change=(key:'a'|'b'|'type'|'competition',value:string)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);if(key==='type'){next.delete('a');next.delete('b')}setParams(next)};
  const loading=Boolean(a&&b&&((mode==='players'&&!playerData)||(mode==='seasons'&&!data)));
  const seasonRows=useMemo(()=>data?.groups.flatMap(group=>group.records)??[],[data]);
  const playerRows=useMemo(()=>playerData?.items.filter((item):item is NonNullable<PlayerItem>=>Boolean(item))??[],[playerData]);
  const meta=mode==='players'?playerData?.meta:data?.meta;
  const actions=mode==='players'&&playerRows.length?<ViewActions filename="confronto-giocatori" rows={playerRows} filters={{type:mode,competition:competition||null,a,b}} sources={playerRows.flatMap(item=>item.seasons.map(row=>row.source_provider??''))} columns={[
    {key:'player',label:'Giocatore',value:item=>item.player.name},{key:'appearances',label:'Presenze',unit:'partite',value:item=>item.player.appearances},{key:'minutes',label:'Minuti',unit:'min',value:item=>item.player.minutes},{key:'goals',label:'Gol',value:item=>item.player.goals},{key:'assists',label:'Assist',value:item=>item.player.assists},{key:'goals90',label:'Gol per 90',unit:'gol/90 min',value:item=>item.normalized.goals_per_90},{key:'assists90',label:'Assist per 90',unit:'assist/90 min',value:item=>item.normalized.assists_per_90},{key:'coverage',label:'Stagioni con dati',value:item=>item.coverage.with_stats}
  ]}/>:mode==='seasons'&&seasonRows.length?<ViewActions filename="confronto-stagioni" rows={seasonRows} filters={{type:mode,competition:competition||null,a,b}} sources={seasonRows.map(row=>row.source_provider??'')} columns={[
    {key:'season',label:'Stagione',value:row=>row.season},{key:'competition',label:'Competizione',value:row=>row.competition},{key:'matches',label:'Partite',unit:'partite',value:row=>row.matches},{key:'points',label:'Punti',value:row=>row.points},{key:'ppm',label:'Punti per partita',unit:'punti/partita',value:row=>row.normalized.points_per_match},{key:'winRate',label:'Vittorie',unit:'%',value:row=>row.normalized.win_rate},{key:'gfpm',label:'Gol fatti per partita',unit:'gol/partita',value:row=>row.normalized.goals_for_per_match},{key:'coverage',label:'Gare con risultato',unit:'partite',value:row=>row.coverage.completed}
  ]}/>:undefined;
  return <><PageTitle title={`Confronta ${mode==='players'?'giocatori':'stagioni'}`} subtitle="Valori assoluti e normalizzati, separati per competizione e accompagnati dalla qualità della copertura." action={actions}/>
    <div className="card mb-5 flex flex-col gap-3 p-4"><div className="flex gap-2"><button className={mode==='seasons'?'btn-primary':'btn-secondary'} onClick={()=>change('type','seasons')}>Stagioni</button><button className={mode==='players'?'btn-primary':'btn-secondary'} onClick={()=>change('type','players')}>Giocatori</button></div><div className="grid gap-3 md:grid-cols-[1fr_auto_1fr_1fr]"><select aria-label="Primo elemento" className="input" value={a} onChange={e=>change('a',e.target.value)}><option value="">Prima scelta</option>{options.map(x=><option value={x.value} key={x.value}>{x.label}</option>)}</select><ArrowLeftRight className="hidden self-center text-neroverde-400 md:block"/><select aria-label="Secondo elemento" className="input" value={b} onChange={e=>change('b',e.target.value)}><option value="">Seconda scelta</option>{options.map(x=><option value={x.value} key={x.value}>{x.label}</option>)}</select><select aria-label="Competizione" className="input" value={competition} onChange={e=>change('competition',e.target.value)}><option value="">Tutte le competizioni</option>{competitions.map(item=><option key={item}>{item}</option>)}</select></div></div>
    {meta?.warning&&<div className="mb-5 flex gap-3 rounded-xl border border-amber-400/30 bg-amber-400/10 p-4 text-sm text-amber-100" role="status"><AlertTriangle className="h-5 w-5 shrink-0"/><div><b>Confronto non omogeneo.</b> {meta.warning}</div></div>}
    <details className="card mb-5 p-4"><summary className="flex cursor-pointer items-center gap-2 font-bold"><BookOpen className="h-4 w-4 text-neroverde-300"/>Definizione delle metriche</summary><p className="mt-3 text-sm leading-6 text-zinc-400">“Per 90” = valore ÷ minuti × 90. “Per partita” usa le partite registrate nel riepilogo stagione. La percentuale vittorie = vittorie ÷ partite × 100. Un valore non disponibile resta N/D e non viene trasformato in zero.</p></details>
    {loading&&<Loading/>}{data?.groups.length===0&&<Empty title="Confronto non disponibile" text="Non ci sono record compatibili per queste stagioni e questa competizione."/>}
    {data?.groups.map(group=><section className="card mb-5 p-5" key={group.season}><h2 className="mb-4 text-xl font-black">{group.season}</h2>{group.records.map(record=><div className="mb-5 last:mb-0" key={record.id}><div className="mb-3 flex items-center justify-between"><CompetitionBadge competition={record.competition}/><Link className="text-sm text-neroverde-300 hover:underline" to={`/seasons/${encodeURIComponent(record.season)}?competition=${encodeURIComponent(record.competition)}`}>Apri stagione</Link></div><div className="mb-3 grid gap-2 text-sm md:grid-cols-3"><div className="rounded-xl bg-zinc-950/50 p-3">Gare in archivio <b>{record.coverage.matches}</b></div><div className="rounded-xl bg-zinc-950/50 p-3">Con risultato <b>{record.coverage.completed??'N/D'}</b></div><div className="rounded-xl bg-zinc-950/50 p-3">Rosa censita <b>{record.coverage.squad??'N/D'}</b></div></div><div className="grid grid-cols-2 gap-px overflow-hidden rounded-xl bg-zinc-800 sm:grid-cols-4">{rawSeason.map(([key,label])=><div className="bg-zinc-950/70 p-3" key={String(key)}><div className="text-xs text-zinc-400">{label}</div><div className="font-bold">{fmt(record[key])}</div></div>)}{[['Punti / partita',record.normalized.points_per_match],['Vittorie %',record.normalized.win_rate],['GF / partita',record.normalized.goals_for_per_match],['GS / partita',record.normalized.goals_against_per_match]].map(([label,value])=><div className="bg-neroverde-900/40 p-3" key={String(label)}><div className="text-xs text-neroverde-300">{label}</div><div className="font-bold">{decimal(value as number|null)}</div></div>)}</div></div>)}</section>)}
    {playerData?.items.length===0&&<Empty title="Confronto non disponibile"/>}{playerRows.map(item=><section className="card mb-4 p-5" key={item.player.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black">{item.player.name}</h2><p className="mt-1 text-sm text-zinc-400">{item.player.position||'Ruolo N/D'} · {item.coverage.with_stats}/{item.coverage.seasons} stagioni con statistiche · verifica {item.coverage.last_verified_at?new Date(item.coverage.last_verified_at).toLocaleDateString('it-IT'):'N/D'}</p></div><Link className="btn-secondary" to={`/players/${item.player.id}`}>Apri profilo</Link></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{(['appearances','minutes','goals','assists'] as const).map(key=><div className="rounded-xl bg-zinc-950/60 p-3" key={key}><div className="text-xs text-zinc-400">{{appearances:'Presenze',minutes:'Minuti',goals:'Gol',assists:'Assist'}[key]}</div><div className="font-bold">{fmt(item.player[key])}</div></div>)}<div className="rounded-xl bg-neroverde-900/40 p-3"><div className="text-xs text-neroverde-300">Gol / 90</div><div className="font-bold">{decimal(item.normalized.goals_per_90)}</div></div><div className="rounded-xl bg-neroverde-900/40 p-3"><div className="text-xs text-neroverde-300">Assist / 90</div><div className="font-bold">{decimal(item.normalized.assists_per_90)}</div></div><div className="rounded-xl bg-neroverde-900/40 p-3"><div className="text-xs text-neroverde-300">Minuti / presenza</div><div className="font-bold">{decimal(item.normalized.minutes_per_appearance)}</div></div></div></section>)}
  </>;
}
