import { useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { Activity, AlertTriangle, ArrowLeft, ArrowRight, CalendarClock, Check, CheckCircle2, ChevronRight, CircleDot, ClipboardCheck, Clock3, Edit3, Plus, RefreshCw, Save, ShieldCheck, Sparkles, Table2, Users, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../services/api';
import { CompetitionBadge, Loading, PageTitle } from '../components/Ui';
import MatchEventEditor from '../components/MatchEventEditor';
import MatchPlayerStatsEditor from '../components/MatchPlayerStatsEditor';

type MatchState='scheduled'|'to_complete'|'completed'|'incomplete'|'invalid';
type MatchRow=Record<string,any>&{id:number;date:string;competition:string;round:string|null;home_team:string;away_team:string;home_score:number|null;away_score:number|null;state:MatchState;completeness:{score:number;checks:{key:string;label:string;done:boolean}[]}};
type StandingRow={id:number;competition:string;team_name:string;team_logo:string|null;rank:number|null;played:number|null;points:number|null;goals_diff:number|null;form:string|null};
type SquadRow={id:number;name:string;position:string|null;shirt_number:number|null;photo_url:string|null;injured:number;appearances:number|null;goals:number|null;assists:number|null};
type Absence={playerId:number|null;playerName:string;kind:'injury'|'suspension';reason:string|null;startDate?:string|null;endDate?:string|null;sourceProvider?:string|null};
type Dashboard={season:string;displaySeason:string;today:string;generatedAt:string;competitions:{name:string;total:number;expected:number;completed:number;scheduled:number;toComplete:number;nextRound:number|null;nextMatchId:number|null}[];matches:MatchRow[];lastUpdated:MatchRow|null;nextAction:MatchRow|null;latestResult:MatchRow|null;nextMatch:MatchRow|null;form:{matchId:number;date:string;opponent:string;result:'W'|'D'|'L';goalsFor:number;goalsAgainst:number}[];standings:StandingRow[];squad:SquadRow[];absences:Absence[];freshness:{lastSyncAt:string|null;providers:{provider:string;resource:string;lastRequest:string|null;lastSuccess:string|null;lastError:string|null}[];recentRuns:{id:number;provider:string|null;status:string;startedAt:string;finishedAt:string|null;error:string|null}[]};totals:{inserted:number;completed:number;scheduled:number;toComplete:number;incomplete:number};suggestions:{opponents:{name:string;stadium?:string|null}[];stadiums:{name:string}[];referees:{name:string}[];competitions:string[]}};
type FormData=Record<string,any>&{competition:string;round:string;date:string;time:string;venue:'home'|'away';opponent:string;status:'scheduled'|'completed';home_score:string;away_score:string;halftime_score:string};
type Validation={valid:boolean;errors:string[];warnings:string[];duplicate?:MatchRow|null};

const SASSUOLO='U.S. Sassuolo Calcio';
const DRAFT_KEY='sassuolo-current-season-match-draft-v1';
const steps=[['Partita',CalendarClock],['Risultato',CircleDot],['Dettagli',Sparkles],['Controllo',ClipboardCheck]] as const;
const emptyDetails={stadium:'',attendance:'',referee:'',shots_home:'',shots_away:'',shots_on_target_home:'',shots_on_target_away:'',corners_home:'',corners_away:'',fouls_home:'',fouls_away:'',xg_home:'',xg_away:'',source_url:''};
const isSassuolo=(value:string)=>/sassuolo/i.test(value);
const dateParts=(value?:string)=>({date:value?.slice(0,10)??'',time:value?.includes('T')?value.slice(11,16):''});
const labelDate=(value:string)=>new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('it-IT',{weekday:'short',day:'2-digit',month:'short',year:'numeric'});
const labelDateTime=(value:string|null)=>value?new Date(value).toLocaleString('it-IT',{dateStyle:'medium',timeStyle:'short'}):'Mai sincronizzato';
const stateMeta:Record<MatchState,{label:string;classes:string}>={
  scheduled:{label:'Programmato',classes:'border-sky-400/30 bg-sky-400/10 text-sky-200'},
  to_complete:{label:'Da completare',classes:'border-amber-400/30 bg-amber-400/10 text-amber-100'},
  completed:{label:'Concluso',classes:'border-emerald-400/30 bg-emerald-400/10 text-emerald-200'},
  incomplete:{label:'Dati incompleti',classes:'border-amber-400/30 bg-amber-400/10 text-amber-100'},
  invalid:{label:'Da correggere',classes:'border-red-400/30 bg-red-400/10 text-red-200'},
};

function inputFromMatch(match:MatchRow):FormData{
  const parts=dateParts(match.date),home=isSassuolo(match.home_team);
  return {competition:match.competition??'',round:String(match.round??'').replace(/\.0$/,''),...parts,venue:home?'home':'away',opponent:home?match.away_team:match.home_team,status:match.home_score==null&&match.away_score==null?'scheduled':'completed',home_score:match.home_score==null?'':String(match.home_score),away_score:match.away_score==null?'':String(match.away_score),halftime_score:match.halftime_score??'',...emptyDetails,...Object.fromEntries(Object.keys(emptyDetails).map(key=>[key,match[key]??'']))};
}

function MatchWizard({dashboard,match,onClose,onSaved}:{dashboard:Dashboard;match:MatchRow|null;onClose:()=>void;onSaved:(id:number)=>void}){
  const primaryCompetition=match?.competition??dashboard.nextAction?.competition??dashboard.competitions[0]?.name??'Serie A';
  const comp=dashboard.competitions.find(item=>item.name===primaryCompetition);
  const draft=useMemo(()=>{if(match)return null;try{return JSON.parse(localStorage.getItem(DRAFT_KEY)??'null')}catch{return null}},[match]);
  const [form,setForm]=useState<FormData>(()=>match?inputFromMatch(match):draft??{competition:primaryCompetition,round:comp?.nextRound?String(comp.nextRound):'',date:'',time:'',venue:'home',opponent:'',status:'scheduled',home_score:'',away_score:'',halftime_score:'',...emptyDetails});
  const [step,setStep]=useState(0);const[busy,setBusy]=useState(false);const[validation,setValidation]=useState<Validation|null>(null);const[dirty,setDirty]=useState(false);
  const set=(key:string,value:any)=>{setDirty(true);setValidation(null);setForm(current=>({...current,[key]:value}));};
  useEffect(()=>{if(!match&&dirty)localStorage.setItem(DRAFT_KEY,JSON.stringify(form));},[form,dirty,match]);
  useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty]);
  const home=form.venue==='home'?SASSUOLO:form.opponent,away=form.venue==='away'?SASSUOLO:form.opponent;
  const payload=()=>({...form,date:form.time?`${form.date}T${form.time}:00`:form.date,season:dashboard.season,home_team:home,away_team:away,home_score:form.status==='completed'?form.home_score:'',away_score:form.status==='completed'?form.away_score:'',halftime_score:form.status==='completed'?form.halftime_score:''});
  const next=async()=>{
    if(step===0&&(!form.competition||!form.date||!form.opponent)){setValidation({valid:false,errors:['Completa competizione, data e avversario prima di continuare.'],warnings:[]});return;}
    if(step===1&&form.status==='completed'&&(form.home_score===''||form.away_score==='')){setValidation({valid:false,errors:['Per una partita conclusa inserisci entrambi i risultati.'],warnings:[]});return;}
    if(step<3){setStep(step+1);return;}await save(false);
  };
  const save=async(forceWarnings:boolean)=>{setBusy(true);try{
    const checked=await api<Validation>('/current-season/matches/validate',{method:'POST',body:JSON.stringify({...payload(),id:match?.id})});setValidation(checked);
    if(!checked.valid||checked.warnings.length&&!forceWarnings)return;
    const result=await api<{id:number}>(match?`/current-season/matches/${match.id}`:'/current-season/matches',{method:match?'PUT':'POST',body:JSON.stringify({...payload(),forceWarnings})});
    localStorage.removeItem(DRAFT_KEY);setDirty(false);onSaved(result.id);
  }catch(error){setValidation({valid:false,errors:[String(error).replace(/^Error:\s*/, '')],warnings:[]});}finally{setBusy(false)}};
  const opponentSuggestion=dashboard.suggestions.opponents.find(item=>item.name===form.opponent);
  useEffect(()=>{if(!form.stadium&&opponentSuggestion?.stadium&&form.venue==='away')set('stadium',opponentSuggestion.stadium)},[form.opponent,form.venue]);
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/85 p-3 backdrop-blur-sm md:p-6" role="dialog" aria-modal="true" aria-label={match?'Modifica partita':'Nuova partita'}>
    <div className="mx-auto max-w-5xl overflow-hidden rounded-3xl border border-white/10 bg-zinc-950 shadow-2xl">
      <header className="sticky top-0 z-20 border-b border-white/[.08] bg-zinc-950/95 px-4 py-4 backdrop-blur md:px-7"><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.18em] text-neroverde-300">Stagione corrente · {dashboard.displaySeason}</div><h2 className="mt-1 text-xl font-black md:text-2xl">{match?'Aggiorna partita':'Inserisci una partita'}</h2><p className="mt-1 text-xs text-zinc-400">Bozza salvata automaticamente su questo dispositivo.</p></div><button className="btn-secondary !min-h-9 !px-2" aria-label="Chiudi" onClick={onClose}><X className="h-4 w-4"/></button></div>
        <ol className="mt-5 grid grid-cols-4 gap-1">{steps.map(([label,Icon],index)=><li key={label}><button type="button" onClick={()=>setStep(index)} className={`flex w-full items-center gap-2 rounded-xl px-2 py-2 text-left text-xs font-bold md:px-3 ${index===step?'bg-neroverde-400 text-zinc-950':index<step?'bg-neroverde-400/10 text-neroverde-300':'bg-zinc-900 text-zinc-400'}`}><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full border border-current/20">{index<step?<Check className="h-3.5 w-3.5"/>:<Icon className="h-3.5 w-3.5"/>}</span><span className="hidden sm:inline">{label}</span></button></li>)}</ol>
      </header>
      <form onSubmit={(e:FormEvent)=>{e.preventDefault();void next()}} className="p-4 md:p-7">
        {step===0&&<div><SectionTitle title="Contesto della partita" text="La stagione e il Sassuolo sono già impostati: scegli solo ciò che cambia."/><div className="grid gap-4 md:grid-cols-2">
          <Field label="Competizione" required><input className="input" list="current-competitions" value={form.competition} onChange={e=>set('competition',e.target.value)}/></Field>
          <Field label="Giornata / turno"><input className="input" value={form.round} onChange={e=>set('round',e.target.value)} placeholder="Es. 9 oppure Ottavi"/></Field>
          <Field label="Data" required><input className="input" type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></Field>
          <Field label="Ora"><input className="input" type="time" value={form.time} onChange={e=>set('time',e.target.value)}/></Field>
        </div><div className="mt-5"><div className="mb-2 text-sm font-bold text-zinc-300">Dove gioca il Sassuolo?</div><div className="grid grid-cols-2 gap-3">{(['home','away'] as const).map(value=><button type="button" key={value} onClick={()=>set('venue',value)} className={`rounded-2xl border p-4 text-left transition ${form.venue===value?'border-neroverde-400 bg-neroverde-400/10':'border-zinc-800 bg-zinc-900/60 hover:border-zinc-600'}`}><div className="font-black">{value==='home'?'In casa':'In trasferta'}</div><div className="mt-1 text-xs text-zinc-400">{value==='home'?'Sassuolo – Avversario':'Avversario – Sassuolo'}</div></button>)}</div></div>
        <div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Avversario" required><input className="input" list="current-opponents" value={form.opponent} onChange={e=>set('opponent',e.target.value)} placeholder="Inizia a digitare…"/></Field><Field label="Stadio" hint="Opzionale, completabile in seguito"><input className="input" list="current-stadiums" value={form.stadium} onChange={e=>set('stadium',e.target.value)} placeholder="Suggerito dai dati storici"/></Field></div>
        {form.opponent&&<div className="mt-5 rounded-2xl border border-neroverde-400/25 bg-neroverde-400/[.07] p-4 text-center text-lg font-black"><span className={isSassuolo(home)?'text-neroverde-300':''}>{home}</span><span className="mx-3 text-zinc-400">–</span><span className={isSassuolo(away)?'text-neroverde-300':''}>{away}</span></div>}</div>}
        {step===1&&<div><SectionTitle title="Stato e risultato" text="Una gara futura richiede solo i dati essenziali; potrai completarla dopo il fischio finale."/><div className="grid gap-3 sm:grid-cols-2">{(['scheduled','completed'] as const).map(value=><button type="button" key={value} onClick={()=>set('status',value)} className={`rounded-2xl border p-4 text-left ${form.status===value?'border-neroverde-400 bg-neroverde-400/10':'border-zinc-800 bg-zinc-900/60'}`}><div className="font-black">{value==='scheduled'?'Partita programmata':'Partita conclusa'}</div><p className="mt-1 text-xs text-zinc-400">{value==='scheduled'?'Salva calendario, ora e sede senza inventare il risultato.':'Inserisci risultato finale e, se disponibile, primo tempo.'}</p></button>)}</div>
        {form.status==='completed'&&<><div className="mt-6 grid grid-cols-[1fr_auto_1fr] items-end gap-3"><ScoreField team={home} value={form.home_score} onChange={value=>set('home_score',value)}/><span className="pb-3 text-2xl font-black text-zinc-400">–</span><ScoreField team={away} value={form.away_score} onChange={value=>set('away_score',value)}/></div><div className="mt-4 max-w-xs"><Field label="Risultato primo tempo"><input className="input" value={form.halftime_score} onChange={e=>set('halftime_score',e.target.value)} placeholder="Es. 1-0"/></Field></div></>}</div>}
        {step===2&&<div><SectionTitle title="Dettagli facoltativi" text="Aggiungi solo i dati che possiedi. Tutto ciò che manca resterà visibile nella dashboard."/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          <Field label="Arbitro"><input className="input" list="current-referees" value={form.referee} onChange={e=>set('referee',e.target.value)}/></Field><NumberField label="Spettatori" field="attendance" form={form} set={set}/><Field label="URL fonte"><input className="input" type="url" value={form.source_url} onChange={e=>set('source_url',e.target.value)} placeholder="https://…"/></Field>
        </div><h3 className="mb-3 mt-7 text-sm font-black uppercase tracking-wider text-zinc-400">Statistiche casa / trasferta</h3><div className="grid gap-3 md:grid-cols-2">{[['Tiri','shots_home','shots_away'],['Tiri in porta','shots_on_target_home','shots_on_target_away'],['Corner','corners_home','corners_away'],['Falli','fouls_home','fouls_away'],['xG','xg_home','xg_away']].map(([label,a,b])=><div className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-4" key={label}><div className="mb-3 text-sm font-bold">{label}</div><div className="grid grid-cols-2 gap-3"><input aria-label={`${label} ${home}`} className="input" type="number" min="0" step={label==='xG'?'0.01':'1'} value={form[a]} onChange={e=>set(a,e.target.value)} placeholder={home}/><input aria-label={`${label} ${away}`} className="input" type="number" min="0" step={label==='xG'?'0.01':'1'} value={form[b]} onChange={e=>set(b,e.target.value)} placeholder={away}/></div></div>)}</div></div>}
        {step===3&&<div><SectionTitle title="Controllo finale" text="Verifica il riepilogo. I controlli automatici distinguono gli errori dagli avvisi gestibili."/><div className="overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-zinc-900 to-zinc-950 p-5 md:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><CompetitionBadge competition={form.competition}/><span className="text-sm font-bold text-zinc-400">{form.round?`Giornata / turno ${form.round}`:'Turno non indicato'}</span></div><div className="my-8 grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center"><div className={`text-lg font-black md:text-2xl ${isSassuolo(home)?'text-neroverde-300':''}`}>{home}</div><div className="rounded-2xl bg-zinc-950 px-4 py-3 text-2xl font-black tabular-nums">{form.status==='completed'?`${form.home_score}–${form.away_score}`:'VS'}</div><div className={`text-lg font-black md:text-2xl ${isSassuolo(away)?'text-neroverde-300':''}`}>{away}</div></div><div className="grid gap-3 border-t border-white/[.08] pt-5 text-sm sm:grid-cols-3"><Summary label="Quando" value={`${form.date?labelDate(form.date):'Data mancante'}${form.time?` · ${form.time}`:''}`}/><Summary label="Stadio" value={form.stadium||'Da completare'}/><Summary label="Stato" value={form.status==='completed'?'Conclusa':'Programmata'}/></div></div>
        <div className="mt-5 rounded-2xl border border-sky-400/20 bg-sky-400/[.06] p-4 text-sm text-sky-100"><ShieldCheck className="mr-2 inline h-4 w-4"/>Il salvataggio sarà marcato come modifica manuale, registrato nell’audit e protetto dagli import automatici.</div></div>}
        {validation&&<ValidationPanel value={validation} onForce={()=>void save(true)}/>}<div className="mt-7 flex flex-col-reverse gap-3 border-t border-white/[.08] pt-5 sm:flex-row sm:items-center sm:justify-between"><button type="button" className="btn-secondary" onClick={()=>step?setStep(step-1):onClose()}><ArrowLeft className="h-4 w-4"/>{step?'Indietro':'Chiudi'}</button><button className="btn-primary" disabled={busy}>{step===3?<><Save className="h-4 w-4"/>{busy?'Controllo…':match?'Salva modifiche':'Salva partita'}</>:<>Continua<ArrowRight className="h-4 w-4"/></>}</button></div>
      </form>
      <datalist id="current-competitions">{dashboard.suggestions.competitions.map(name=><option key={name} value={name}/>)}</datalist><datalist id="current-opponents">{dashboard.suggestions.opponents.map(item=><option key={item.name} value={item.name}/>)}</datalist><datalist id="current-stadiums">{dashboard.suggestions.stadiums.map(item=><option key={item.name} value={item.name}/>)}</datalist><datalist id="current-referees">{dashboard.suggestions.referees.map(item=><option key={item.name} value={item.name}/>)}</datalist>
    </div></div>;
}

function Field({label,hint,required,children}:{label:string;hint?:string;required?:boolean;children:any}){return <label className="block text-sm"><span className="mb-1.5 flex items-center gap-1 font-bold text-zinc-300">{label}{required&&<span className="text-neroverde-400">*</span>}</span>{children}{hint&&<span className="mt-1.5 block text-xs text-zinc-400">{hint}</span>}</label>}
function NumberField({label,field,form,set}:{label:string;field:string;form:FormData;set:(key:string,value:any)=>void}){return <Field label={label}><input className="input" type="number" min="0" value={form[field]} onChange={e=>set(field,e.target.value)}/></Field>}
function ScoreField({team,value,onChange}:{team:string;value:string;onChange:(value:string)=>void}){return <label className="text-center"><span className="mb-2 block truncate text-xs font-bold text-zinc-400">{team}</span><input aria-label={`Gol ${team}`} className="input text-center text-3xl font-black tabular-nums" type="number" min="0" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function SectionTitle({title,text}:{title:string;text:string}){return <div className="mb-6"><h3 className="text-xl font-black text-white">{title}</h3><p className="mt-1 max-w-2xl text-sm leading-6 text-zinc-400">{text}</p></div>}
function Summary({label,value}:{label:string;value:string}){return <div><div className="text-xs font-bold uppercase tracking-wider text-zinc-400">{label}</div><div className="mt-1 font-semibold text-zinc-200">{value}</div></div>}
function ValidationPanel({value,onForce}:{value:Validation;onForce:()=>void}){if(!value.errors.length&&!value.warnings.length)return <div className="mt-5 rounded-2xl border border-emerald-400/30 bg-emerald-400/10 p-4 text-sm text-emerald-100"><CheckCircle2 className="mr-2 inline h-4 w-4"/>Controlli superati: la partita è pronta per il salvataggio.</div>;return <div className={`mt-5 rounded-2xl border p-4 ${value.errors.length?'border-red-400/30 bg-red-400/10 text-red-100':'border-amber-400/30 bg-amber-400/10 text-amber-100'}`}><div className="font-black">{value.errors.length?'Correggi prima di salvare':'Attenzione'}</div><ul className="mt-2 space-y-1 text-sm">{[...value.errors,...value.warnings].map(message=><li key={message}>• {message}</li>)}</ul>{!value.errors.length&&value.warnings.length>0&&<button type="button" className="btn-secondary mt-4 border-amber-300/30 text-amber-100" onClick={onForce}>Continua comunque</button>}{value.duplicate&&<Link className="btn-secondary mt-4" to={`/matches/${value.duplicate.id}`}>Apri partita esistente</Link>}</div>}

function MatchItem({match,onEdit,onEvents,onStats}:{match:MatchRow;onEdit:(match:MatchRow)=>void;onEvents:(id:number)=>void;onStats:(id:number)=>void}){const meta=stateMeta[match.state],missing=match.completeness.checks.filter(item=>!item.done).map(item=>item.label);return <article className="rounded-2xl border border-white/[.07] bg-zinc-950/45 p-4 transition hover:border-white/[.14]"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="flex min-w-0 flex-1 items-center gap-4"><div className="hidden w-14 shrink-0 text-center sm:block"><div className="text-xl font-black">{new Date(`${match.date.slice(0,10)}T12:00:00`).getDate()}</div><div className="text-[10px] font-black uppercase text-zinc-400">{new Date(`${match.date.slice(0,10)}T12:00:00`).toLocaleDateString('it-IT',{month:'short'})}</div></div><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2"><CompetitionBadge competition={match.competition} compact/><span className={`badge ${meta.classes}`}>{meta.label}</span>{match.round&&<span className="text-xs text-zinc-400">Giornata / turno {String(match.round).replace(/\.0$/,'')}</span>}</div><div className="flex items-center gap-2 font-black"><span className="truncate">{match.home_team}</span><span className="shrink-0 rounded-lg bg-zinc-900 px-2 py-1 tabular-nums">{match.home_score==null||match.away_score==null?'–':`${match.home_score}–${match.away_score}`}</span><span className="truncate">{match.away_team}</span></div></div></div><div className="w-full lg:w-48"><div className="flex items-center justify-between text-xs"><span className="text-zinc-400">Completezza</span><b>{match.completeness.score}%</b></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-zinc-800"><div className="h-full rounded-full bg-neroverde-400" style={{width:`${match.completeness.score}%`}}/></div>{missing.length>0&&<div className="mt-1.5 truncate text-[10px] text-zinc-400" title={missing.join(', ')}>Manca: {missing.slice(0,2).join(', ')}</div>}</div><div className="flex shrink-0 gap-2"><button className={match.state==='to_complete'||match.state==='scheduled'?'btn-primary':'btn-secondary'} onClick={()=>onEdit(match)}><Edit3 className="h-4 w-4"/>{match.state==='to_complete'?'Completa':'Modifica'}</button><button className="btn-secondary !px-3" aria-label="Statistiche e voti" title="Statistiche e voti" disabled={match.home_score==null||match.away_score==null} onClick={()=>onStats(match.id)}><Table2 className="h-4 w-4"/></button><button className="btn-secondary !px-3" aria-label="Gestisci eventi" title="Gestisci eventi" onClick={()=>onEvents(match.id)}><Plus className="h-4 w-4"/></button><Link className="btn-secondary !px-3" aria-label="Apri partita" to={`/matches/${match.id}`}><ChevronRight className="h-4 w-4"/></Link></div></div></article>}

function FocusMatch({label,match}:{label:string;match:MatchRow|null}){return <article className="card p-5"><div className="text-[11px] font-black uppercase tracking-[.16em] text-zinc-400">{label}</div>{match?<><div className="mt-3 flex items-center justify-between gap-3"><CompetitionBadge competition={match.competition} compact/><span className="text-xs text-zinc-400">{labelDate(match.date)}</span></div><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-2 text-center"><b>{match.home_team}</b><span className="rounded-xl bg-zinc-950 px-3 py-2 text-xl font-black tabular-nums">{match.home_score==null||match.away_score==null?'VS':`${match.home_score}–${match.away_score}`}</span><b>{match.away_team}</b></div><Link className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-neroverde-300 hover:underline" to={`/matches/${match.id}`}>Apri il dettaglio <ChevronRight className="h-4 w-4"/></Link></>:<p className="mt-4 text-sm text-zinc-400">Nessuna gara disponibile.</p>}</article>}

function SeasonOverview({data,competition}:{data:Dashboard;competition:string}){
  const standings=data.standings.filter(row=>row.competition===competition);const sassIndex=standings.findIndex(row=>isSassuolo(row.team_name));const start=Math.max(0,Math.min(sassIndex<0?0:sassIndex-2,Math.max(0,standings.length-5)));const tableRows=standings.slice(start,start+5);
  return <><div className="mb-5 grid gap-4 lg:grid-cols-2"><FocusMatch label="Ultima gara" match={data.latestResult}/><FocusMatch label="Prossima gara" match={data.nextMatch}/></div>
    <div className="mb-5 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><section className="card p-5"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-black"><Table2 className="h-5 w-5 text-neroverde-300"/>Classifica</h2><p className="mt-1 text-xs text-zinc-400">{competition} · zona Sassuolo</p></div><Link className="text-sm font-bold text-neroverde-300 hover:underline" to={`/seasons/${encodeURIComponent(data.season)}?competition=${encodeURIComponent(competition)}`}>Classifica completa</Link></div>{tableRows.length?<div className="overflow-x-auto"><table><thead><tr><th>#</th><th>Squadra</th><th>PG</th><th>DR</th><th>Pt</th></tr></thead><tbody>{tableRows.map(row=><tr key={row.id} className={isSassuolo(row.team_name)?'bg-neroverde-500/10':''}><td className="font-black">{row.rank??'N/D'}</td><td><div className="flex items-center gap-2">{row.team_logo&&<img className="h-6 w-6 object-contain" src={row.team_logo} alt=""/>}<b>{row.team_name}</b></div></td><td>{row.played??'N/D'}</td><td>{row.goals_diff??'N/D'}</td><td className="font-black">{row.points??'N/D'}</td></tr>)}</tbody></table></div>:<p className="rounded-xl border border-dashed border-zinc-800 p-6 text-center text-sm text-zinc-400">Classifica non ancora disponibile per questa competizione.</p>}</section>
    <section className="card p-5"><h2 className="flex items-center gap-2 font-black"><Activity className="h-5 w-5 text-neroverde-300"/>Forma recente</h2><p className="mt-1 text-xs text-zinc-400">Ultime cinque gare concluse, tutte le competizioni</p>{data.form.length?<div className="mt-5 space-y-3">{data.form.map(item=><Link to={`/matches/${item.matchId}`} key={item.matchId} className="grid grid-cols-[2rem_1fr_auto] items-center gap-3 rounded-xl bg-zinc-950/60 p-3 hover:bg-zinc-900"><span className={`grid h-8 w-8 place-items-center rounded-full text-xs font-black ${item.result==='W'?'bg-emerald-400/15 text-emerald-300':item.result==='D'?'bg-zinc-700 text-zinc-200':'bg-red-400/15 text-red-300'}`}>{item.result==='W'?'V':item.result==='D'?'N':'P'}</span><span className="truncate text-sm font-bold">{item.opponent}</span><span className="font-black tabular-nums">{item.goalsFor}–{item.goalsAgainst}</span></Link>)}</div>:<p className="mt-5 text-sm text-zinc-400">Nessun risultato disponibile.</p>}</section></div>
    <div className="mb-5 grid gap-4 lg:grid-cols-2"><section className="card p-5"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-black"><Users className="h-5 w-5 text-neroverde-300"/>Rosa</h2><Link className="text-sm font-bold text-neroverde-300 hover:underline" to="/squad">Tutta la rosa</Link></div>{data.squad.length?<div className="mt-4 grid gap-2 sm:grid-cols-2">{data.squad.slice(0,8).map(player=><Link to={`/players/${player.id}`} key={player.id} className="flex items-center gap-3 rounded-xl bg-zinc-950/55 p-3 hover:bg-zinc-900">{player.photo_url?<img src={player.photo_url} alt="" className="h-9 w-9 rounded-full object-cover"/>:<span className="grid h-9 w-9 place-items-center rounded-full bg-zinc-800 text-xs font-black">{player.shirt_number??'–'}</span>}<span className="min-w-0"><b className="block truncate text-sm">{player.name}</b><span className="text-xs text-zinc-400">{player.position??'Ruolo N/D'}{player.appearances!=null?` · ${player.appearances} pres.`:''}</span></span></Link>)}</div>:<p className="mt-5 text-sm text-zinc-400">Rosa corrente non ancora sincronizzata.</p>}</section>
    <section className="card p-5"><h2 className="flex items-center gap-2 font-black"><AlertTriangle className="h-5 w-5 text-amber-300"/>Infortuni e squalifiche</h2><p className="mt-1 text-xs text-zinc-400">Segnalazioni della rosa e della prossima gara</p>{data.absences.length?<div className="mt-4 space-y-2">{data.absences.map(item=><div key={`${item.playerId??item.playerName}-${item.kind}`} className="rounded-xl border border-amber-400/15 bg-amber-400/[.05] p-3"><div className="flex items-center justify-between gap-3"><b>{item.playerName}</b><span className="badge border-amber-400/20 text-amber-200">{item.kind==='suspension'?'Squalifica':'Infortunio'}</span></div><p className="mt-1 text-xs text-zinc-400">{item.reason??'Motivo non indicato'}</p></div>)}</div>:<p className="mt-5 rounded-xl border border-dashed border-zinc-800 p-5 text-sm text-zinc-400">Nessuna indisponibilità segnalata nei dati disponibili.</p>}</section></div></>;
}

export default function CurrentSeason(){const[data,setData]=useState<Dashboard|null>(null);const[error,setError]=useState('');const[syncing,setSyncing]=useState(false);const[syncMessage,setSyncMessage]=useState('');const[editing,setEditing]=useState<MatchRow|null|undefined>(undefined);const[eventMatchId,setEventMatchId]=useState<number|null>(null);const[statsMatchId,setStatsMatchId]=useState<number|null>(null);const[savedId,setSavedId]=useState<number|null>(null);const[competition,setCompetition]=useState('');const[view,setView]=useState<'attention'|'upcoming'|'completed'>('attention');
  const load=()=>api<Dashboard>('/current-season').then(value=>{setData(value);setError('');if(!competition)setCompetition(value.standings[0]?.competition??value.competitions[0]?.name??'');if(!data&&value.totals.toComplete+value.totals.incomplete===0)setView('upcoming')}).catch(err=>setError(String(err)));
  const sync=async()=>{setSyncing(true);setSyncMessage('');try{const result=await api<{ok:boolean;errors?:string[]}>('/update/current-season',{method:'POST'});setSyncMessage(result.errors?.length?`Aggiornamento parziale: ${result.errors.join(' · ')}`:'Aggiornamento completato.');await load()}catch(err){setSyncMessage(`Aggiornamento non completato: ${String(err).replace(/^Error:\s*/,'')}`);await load()}finally{setSyncing(false)}};
  useEffect(()=>{void load()},[]);
  const visible=useMemo(()=>{if(!data)return[];const rows=data.matches.filter(match=>(!competition||match.competition===competition)&&(view==='attention'?(match.state==='to_complete'||match.state==='invalid'||match.state==='incomplete'):view==='upcoming'?match.state==='scheduled':match.state==='completed'||match.state==='incomplete'));return rows.sort((a,b)=>view==='upcoming'?a.date.localeCompare(b.date):b.date.localeCompare(a.date)).slice(0,20)},[data,competition,view]);
  if(!data)return error?<div className="card p-6 text-red-200">{error}</div>:<Loading/>;
  const next=data.nextAction;
  const providerErrors=[...data.freshness.providers.filter(item=>item.lastError).map(item=>`${item.provider}: ${item.lastError}`),...data.freshness.recentRuns.filter(item=>item.status==='partial'||item.status==='failed').map(item=>`${item.provider??'Provider'}: ${item.error??item.status}`)].filter((value,index,all)=>all.indexOf(value)===index);
  return <><PageTitle eyebrow={`Stagione corrente · ${data.displaySeason}`} title="Centro stagione" subtitle="Risultati, calendario, classifica, forma, rosa e disponibilità con freschezza verificabile." action={<div className="flex flex-wrap gap-2"><button className="btn-secondary" disabled={syncing} onClick={()=>void sync()}><RefreshCw className={`h-4 w-4 ${syncing?'animate-spin':''}`}/>{syncing?'Aggiornamento…':'Aggiorna dati'}</button><button className="btn-primary" onClick={()=>next?setEditing(next):setEditing(null)}>{next&&next.state!=='completed'?<Clock3 className="h-4 w-4"/>:<Plus className="h-4 w-4"/>}{next?next.state==='scheduled'?'Aggiorna prossima gara':'Completa prossima gara':'Inserisci partita'}</button></div>}/>
    <section className={`mb-5 rounded-2xl border p-4 ${providerErrors.length?'border-amber-400/25 bg-amber-400/[.06]':'border-emerald-400/20 bg-emerald-400/[.05]'}`} aria-live="polite"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><div className="text-xs font-black uppercase tracking-wider text-zinc-400">Freschezza dei dati</div><div className="mt-1 font-bold">Ultimo sync riuscito: {labelDateTime(data.freshness.lastSyncAt)}</div></div><div className="text-xs text-zinc-400">Vista generata: {labelDateTime(data.generatedAt)}</div></div>{syncMessage&&<p className="mt-3 text-sm text-zinc-300">{syncMessage}</p>}{providerErrors.length>0&&<details className="mt-3 text-sm text-amber-100"><summary className="cursor-pointer font-bold">{providerErrors.length} avviso/i provider</summary><ul className="mt-2 space-y-1">{providerErrors.map(message=><li key={message}>• {message}</li>)}</ul></details>}</section>
    <SeasonOverview data={data} competition={competition}/>
    <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="In archivio" value={data.totals.inserted} hint="tutte le competizioni"/><Metric label="Concluse" value={data.totals.completed} hint="con risultato finale" tone="green"/><Metric label="Programmate" value={data.totals.scheduled} hint="gare future" tone="blue"/><Metric label="Da completare" value={data.totals.toComplete} hint="richiedono attenzione" tone="amber"/><Metric label="Dati incompleti" value={data.totals.incomplete} hint="integrabili in seguito" tone="amber"/></section>
    {next&&<section className="card mb-5 border-neroverde-400/20 bg-gradient-to-br from-neroverde-950/80 to-zinc-900 p-5 md:p-6"><div className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="mb-2 flex flex-wrap items-center gap-2"><span className="badge border-neroverde-400/30 bg-neroverde-400/10 text-neroverde-200">Prossima azione</span><CompetitionBadge competition={next.competition}/><span className="text-xs text-zinc-400">{next.round?`Giornata / turno ${String(next.round).replace(/\.0$/,'')} · `:''}{labelDate(next.date)}</span></div><div className="text-xl font-black md:text-3xl">{next.home_team} <span className="text-zinc-400">–</span> {next.away_team}</div><p className="mt-2 text-sm text-zinc-400">{next.state==='scheduled'?'La gara è già in calendario: aggiornala senza creare un nuovo record.':'La data è trascorsa e il risultato deve essere completato.'}</p></div><button className="btn-primary" onClick={()=>setEditing(next)}>{next.state==='scheduled'?'Aggiorna gara':'Completa partita'}<ArrowRight className="h-4 w-4"/></button></div></section>}
    <div className="mb-5 grid gap-4 lg:grid-cols-2">{data.competitions.map(item=><article className="card p-5" key={item.name}><div className="flex items-start justify-between"><div><CompetitionBadge competition={item.name}/><div className="mt-4 text-3xl font-black">{item.completed}<span className="text-lg text-zinc-400"> / {item.expected}</span></div><div className="mt-1 text-xs text-zinc-400">partite concluse · {item.total} in archivio</div></div>{item.toComplete>0&&<span className="badge border-amber-400/30 bg-amber-400/10 text-amber-100">{item.toComplete} da completare</span>}</div><div className="mt-5 h-2 overflow-hidden rounded-full bg-zinc-800"><div className="h-full rounded-full bg-neroverde-400" style={{width:`${item.expected?Math.min(100,item.completed/item.expected*100):0}%`}}/></div></article>)}</div>
    <section className="card p-4 md:p-5"><div className="mb-5 flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><h2 className="text-lg font-black">Partite operative</h2><p className="mt-1 text-xs text-zinc-400">Modifica, completa o apri una gara senza cambiare sezione.</p></div><div className="flex flex-col gap-2 sm:flex-row"><select className="input sm:w-48" value={competition} onChange={e=>setCompetition(e.target.value)}>{data.competitions.map(item=><option key={item.name}>{item.name}</option>)}</select><div className="flex rounded-xl border border-zinc-800 bg-zinc-950 p-1">{([['attention','Attenzione'],['upcoming','Future'],['completed','Concluse']] as const).map(([key,label])=><button key={key} className={`rounded-lg px-3 py-2 text-xs font-bold ${view===key?'bg-zinc-800 text-white':'text-zinc-400 hover:text-white'}`} onClick={()=>setView(key)}>{label}</button>)}</div><button className="btn-secondary" onClick={()=>setEditing(null)}><Plus className="h-4 w-4"/>Nuova partita</button></div></div><div className="space-y-3">{visible.length?visible.map(match=><MatchItem key={match.id} match={match} onEdit={setEditing} onEvents={setEventMatchId} onStats={setStatsMatchId}/>):<div className="rounded-2xl border border-dashed border-zinc-800 p-10 text-center text-sm text-zinc-400">Nessuna partita in questa vista.</div>}</div></section>
    {editing!==undefined&&<MatchWizard dashboard={data} match={editing} onClose={()=>setEditing(undefined)} onSaved={id=>{setEditing(undefined);setSavedId(id);void load()}}/>}
    {eventMatchId!=null&&<MatchEventEditor matchId={eventMatchId} onClose={()=>setEventMatchId(null)} onChanged={()=>void load()}/>}    
    {statsMatchId!=null&&<MatchPlayerStatsEditor matchId={statsMatchId} onClose={()=>setStatsMatchId(null)} onChanged={()=>void load()}/>}
    {savedId&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-3xl border border-emerald-400/20 bg-zinc-950 p-7 text-center shadow-2xl"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-emerald-400/10 text-emerald-300"><CheckCircle2 className="h-7 w-7"/></div><h2 className="mt-5 text-2xl font-black">Partita salvata</h2><p className="mt-2 text-sm text-zinc-400">Il dato manuale è stato registrato nell’audit e resta disponibile per integrazioni successive.</p><div className="mt-6 grid gap-2 sm:grid-cols-2"><Link className="btn-primary" to={`/matches/${savedId}`}>Apri partita</Link><button className="btn-secondary" onClick={()=>{setEventMatchId(savedId);setSavedId(null)}}>Aggiungi eventi</button><button className="btn-secondary" onClick={()=>{setStatsMatchId(savedId);setSavedId(null)}}>Statistiche e voti</button><button className="btn-secondary" onClick={()=>{setSavedId(null);const candidate=data.matches.find(match=>match.id!==savedId&&(match.state==='to_complete'||match.state==='scheduled'));setEditing(candidate??null)}}>Partita successiva</button></div><button className="mt-5 text-sm font-bold text-zinc-400 hover:text-white" onClick={()=>setSavedId(null)}>Chiudi</button></div></div>}
  </>}

function Metric({label,value,hint,tone='zinc'}:{label:string;value:number;hint:string;tone?:'zinc'|'green'|'blue'|'amber'}){const colors={zinc:'text-white',green:'text-emerald-300',blue:'text-sky-300',amber:'text-amber-200'};return <div className="card p-4"><div className="text-[11px] font-black uppercase tracking-wider text-zinc-400">{label}</div><div className={`mt-2 text-3xl font-black ${colors[tone]}`}>{value}</div><div className="mt-1 text-xs text-zinc-400">{hint}</div></div>}
