import { Download, Trash2, Upload } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageTitle } from '../components/Ui';
import { useExperience, type Favorite } from '../context/ExperienceContext';

export default function Favorites(){
  const experience=useExperience();
  const download=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),favorites:experience.favorites},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='sassuolo-history-preferiti.json';anchor.click();URL.revokeObjectURL(url)};
  const upload=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text());const favorites=(Array.isArray(parsed)?parsed:parsed.favorites) as Favorite[];if(!Array.isArray(favorites))throw new Error();experience.importFavorites(favorites);}catch{window.alert('File preferiti non valido.');}finally{event.target.value='';}};
  return <><PageTitle title="Preferiti" subtitle="Raccolta locale, esportabile e disponibile anche senza account." action={<div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={download} disabled={!experience.favorites.length}><Download aria-hidden="true" className="h-4 w-4"/>Esporta</button><label className="btn-secondary cursor-pointer"><Upload aria-hidden="true" className="h-4 w-4"/>Importa<input className="sr-only" type="file" accept="application/json,.json" onChange={upload}/></label><button className="btn-secondary text-red-200" onClick={experience.clearFavorites} disabled={!experience.favorites.length}><Trash2 aria-hidden="true" className="h-4 w-4"/>Cancella tutto</button></div>}/>{experience.favorites.length?<ul className="grid gap-3 md:grid-cols-2">{experience.favorites.map(item=><li className="card flex items-center justify-between gap-3 p-4" key={item.url}><div className="min-w-0"><Link className="block truncate font-bold text-neroverde-300 hover:underline" to={item.url}>{item.label}</Link><div className="mt-1 text-xs text-zinc-400">{item.type} · salvato il {new Date(item.savedAt).toLocaleString('it-IT')}</div></div><button className="btn-secondary !min-h-9 !px-2" aria-label={`Rimuovi ${item.label} dai preferiti`} onClick={()=>experience.toggleFavorite(item)}><Trash2 aria-hidden="true" className="h-4 w-4"/></button></li>)}</ul>:<div className="card p-8 text-center text-zinc-300">Nessun preferito. Usa il segnalibro nell’intestazione di una pagina per aggiungerla.</div>}</>;
}
