import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Activity, AlertTriangle, ArrowLeft, Clock3, ExternalLink, MapPin, RefreshCw, Shield, Users } from 'lucide-react';
import { api, post } from '../services/api';
import { CompletenessBadge, Loading, PageTitle, RemoteImage, Score, SourceBadge, fmt } from '../components/Ui';
import type { Match } from '../types';

type EventRow={id:number;minute:number|null;extra_minute:number|null;team_name:string|null;player_id:number|null;player_name:string|null;assist_player_id:number|null;assist_name:string|null;type:string|null;detail:string|null;comments:string|null;verification_note?:string|null;home_score?:number|null;away_score?:number|null};
type LineupPlayer={player?:{id?:string|number|null;localPlayerId?:number|null;name?:string;number?:number|null;pos?:string|null}};
type Lineup={id:number;team_name:string|null;team_logo:string|null;formation:string|null;coach_name:string|null;startXI:LineupPlayer[];substitutes:LineupPlayer[]};
type TeamStat={type:string;value:unknown};
type TeamStats={id:number;team_name:string|null;statistics:TeamStat[]};
type PlayerStat={id:number;team_name:string|null;team_logo:string|null;player_id:number|null;player_name:string;player_photo:string|null;minutes:number|null;position:string|null;rating:number|null;archive_rating:number|null;archive_rating_version:string|null;archive_rating_confidence:number|null;archive_rating_level:string|null;captain:number|null;shots_total:number|null;shots_on:number|null;goals:number|null;assists:number|null;passes_total:number|null;passes_key:number|null;pass_accuracy:number|null;tackles_total:number|null;blocks:number|null;interceptions:number|null;duels_total:number|null;duels_won:number|null;dribbles_attempts:number|null;dribbles_success:number|null;fouls_drawn:number|null;fouls_committed:number|null;yellow_cards:number|null;red_cards:number|null};
type Details={source_provider?:string|null;status_long?:string|null;status_short?:string|null;venue_name?:string|null;venue_city?:string|null;league_round?:string|null;home_team_logo?:string|null;away_team_logo?:string|null;events_synced?:number|null;lineups_synced?:number|null;team_stats_synced?:number|null;player_stats_synced?:number|null;injuries_synced?:number|null};
type Injury={id:number;team_name:string|null;player_id:number|null;player_name:string;type:string|null;reason:string|null};
type SpecialEvent={id:number;event_type:string;effective_at:string;match_minute:number|null;remaining_minutes:number|null;home_score:number|null;away_score:number|null;reason:string|null;description:string;authority:string|null;source_provider:string;source_url:string;last_verified_at:string};
type Modules={score:boolean;events:boolean;lineups:boolean;substitutions:boolean;teamStats:boolean;playerStats:boolean;injuries:boolean;specialEvents:boolean};
type Payload={match:Match;details:Details|null;outcome:{halftime:string|null;fulltime:string|null;extraTime:string|null;penalties:string|null};modules:Modules;events:EventRow[];specialEvents:SpecialEvent[];lineups:Lineup[];teamStats:TeamStats[];playerStats:PlayerStat[];injuries:Injury[];sources:{id:number;field:string|null;source_url:string;note:string|null;source_provider:string|null;verified_at:string}[]};

const statLabel=(value:string)=>value.replace(/_/g,' ').replace(/\b\w/g,char=>char.toUpperCase());
const displayValue=(value:unknown)=>value==null||value===''?'N/D':String(value);
function eventGlyph(type:string|null,detail:string|null){const value=`${type??''} ${detail??''}`.toLowerCase();if(value.includes('goal'))return '⚽';if(value.includes('red')&&value.includes('card'))return '🟥';if(value.includes('yellow')||value.includes('card'))return '🟨';if(value.includes('sub'))return '🔄';if(value.includes('var'))return '📺';return '•';}
function minuteLabel(event:EventRow){
  if(event.minute==null)return /(?:fine|termine) (?:della )?gara/i.test(event.verification_note??'')?'Fine gara':'—';
  return event.extra_minute?`${event.minute}+${event.extra_minute}'`:`${event.minute}'`;
}
const specialEventLabels:Record<string,string>={POSTPONED:'Rinviata',KICKOFF_DELAYED:'Calcio d’inizio ritardato',SUSPENDED:'Sospesa',RESUMED:'Ripresa / completata',ABANDONED:'Abbandonata',CANCELLED:'Annullata',AWARDED:'Risultato a tavolino',DATE_CHANGED:'Data modificata',VENUE_CHANGED:'Sede modificata',OTHER:'Avvenimento particolare'};

export default function MatchDetail(){
  const {id}=useParams();
  const [data,setData]=useState<Payload|null>(null);
  const [busy,setBusy]=useState(false);
  const [message,setMessage]=useState('');
  const load=()=>api<Payload>(`/matches/${id}`).then(setData);
  useEffect(()=>{void load()},[id]);
  const sync=async()=>{setBusy(true);setMessage('');try{const response=await post<any>(`/kickoff/match/${id}`);const result=response.result??response;const notices=[...(result?.errors??[]),...(result?.warnings??[])];setMessage(notices.length?`Aggiornato con avvisi: ${notices.join(' | ')}`:`Dettagli aggiornati · ${result.requests??0} richieste API`);await load();}catch(error){setMessage(String(error));}finally{setBusy(false);}};

  const groupedPlayers=useMemo(()=>{const map=new Map<string,PlayerStat[]>();for(const player of data?.playerStats??[]){const key=player.team_name??'Squadra';map.set(key,[...(map.get(key)??[]),player]);}return [...map.entries()];},[data]);
  const statRows=useMemo(()=>{
    if(!data)return [];
    if(data.teamStats.length){const keys=[...new Set(data.teamStats.flatMap(block=>block.statistics.map(stat=>stat.type)))];return keys.map(type=>({type,values:data.teamStats.map(block=>block.statistics.find(stat=>stat.type===type)?.value??null)}));}
    const match=data.match;
    return [
      {type:'Possesso',values:[match.possession_home==null?null:`${match.possession_home}%`,match.possession_away==null?null:`${match.possession_away}%`]},
      {type:'Tiri',values:[match.shots_home,match.shots_away]},{type:'Tiri in porta',values:[match.shots_on_target_home,match.shots_on_target_away]},
      {type:'Calci d’angolo',values:[match.corners_home,match.corners_away]},{type:'Falli',values:[match.fouls_home,match.fouls_away]},{type:'xG',values:[match.xg_home,match.xg_away]}
    ].filter(row=>row.values.some(value=>value!=null));
  },[data]);

  if(!data)return <Loading/>;
  const {match,details,modules}=data;
  const creditedSources=[...new Map(data.sources.filter(source=>source.source_url).map(source=>[`${source.source_provider??''}|${source.source_url}`,source])).values()];
  const syncFlags=details?[details.events_synced,details.lineups_synced,details.team_stats_synced,details.player_stats_synced,details.injuries_synced]:[];
  const syncProgress=syncFlags.some(value=>value!=null)?syncFlags.filter(Boolean).length:null;
  return <>
    <div className="mb-4 flex flex-wrap gap-2 text-xs text-zinc-400"><Link to="/matches" className="hover:text-neroverde-300">Partite</Link><span>/</span>{match.season&&<><Link to={`/seasons/${encodeURIComponent(match.season)}`} className="hover:text-neroverde-300">{match.season}</Link><span>/</span></>}<span>{match.home_team} – {match.away_team}</span></div>
    <div className="mb-4"><Link className="inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-white" to="/matches"><ArrowLeft className="h-4 w-4"/>Torna alle partite</Link></div>
    <PageTitle title={`${match.home_team} vs ${match.away_team}`} subtitle={`${match.competition??'Competizione N/D'} · ${match.season??'Stagione N/D'} · ${details?.league_round??match.round??'Giornata N/D'}`} action={<button className="btn-secondary" disabled={busy} onClick={sync}><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/>{busy?'Aggiornamento…':'Aggiorna dettagli'}</button>}/>
    <div className="mb-4 flex flex-wrap items-center gap-3"><CompletenessBadge level={match.completeness_level} prefix/>{syncProgress!=null&&<span className={`badge text-[10px] ${syncProgress===syncFlags.length?'text-neroverde-300':'text-amber-200'}`} title="Eventi, formazioni, statistiche squadra, statistiche giocatori e indisponibili">Sincronizzazione: {syncProgress}/{syncFlags.length} moduli</span>}<SourceBadge provider={match.source_provider} url={match.source_url} verifiedAt={match.last_verified_at}/></div>
    {message&&<div className="mb-5 rounded-xl border border-zinc-800 bg-zinc-900 p-3 text-sm text-zinc-300">{message}</div>}

    <section className="card mb-5 overflow-hidden p-5 md:p-7">
      <div className="grid items-center gap-5 md:grid-cols-[1fr_auto_1fr]">
        <div className="flex flex-col items-center gap-3 text-center md:items-end md:text-right">{details?.home_team_logo&&<RemoteImage className="h-16 w-16 object-contain" src={details.home_team_logo} alt={`Stemma ${match.home_team}`} width={64} height={64}/>}<div className="text-xl font-black">{match.home_team}</div></div>
        <div className="text-center"><div className="text-4xl font-black"><Score home={match.home_score} away={match.away_score}/></div><div className="mt-2 text-xs uppercase tracking-wider text-zinc-400">{details?.status_long??details?.status_short??'Stato N/D'}</div>{data.outcome.halftime&&<div className="mt-1 text-xs text-zinc-400">Intervallo {data.outcome.halftime}</div>}{data.outcome.extraTime&&<div className="mt-1 text-xs text-zinc-400">Dopo supplementari {data.outcome.extraTime}</div>}{data.outcome.penalties&&<div className="mt-1 text-xs font-bold text-neroverde-300">Rigori {data.outcome.penalties}</div>}</div>
        <div className="flex flex-col items-center gap-3 text-center md:items-start md:text-left">{details?.away_team_logo&&<RemoteImage className="h-16 w-16 object-contain" src={details.away_team_logo} alt={`Stemma ${match.away_team}`} width={64} height={64}/>}<div className="text-xl font-black">{match.away_team}</div></div>
      </div>
      <div className="mt-6 flex flex-wrap justify-center gap-x-6 gap-y-2 border-t border-zinc-800 pt-5 text-sm text-zinc-400"><span className="inline-flex items-center gap-2"><Clock3 className="h-4 w-4"/>{new Date(match.date).toLocaleString('it-IT')}</span>{(details?.venue_name||match.stadium)&&<span className="inline-flex items-center gap-2"><MapPin className="h-4 w-4"/>{details?.venue_name??match.stadium}{details?.venue_city?` · ${details.venue_city}`:''}</span>}{match.referee&&<span className="inline-flex items-center gap-2"><Shield className="h-4 w-4"/>Arbitro: {match.referee}</span>}{match.attendance!=null&&<span className="inline-flex items-center gap-2"><Users className="h-4 w-4"/>{match.attendance.toLocaleString('it-IT')} spettatori</span>}</div>
    </section>

    {modules.specialEvents&&<section className="card mb-5 border-amber-500/30 p-5"><div className="mb-4 flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-400"/><h2 className="text-lg font-bold">Avvenimenti particolari</h2></div><div className="space-y-3">{data.specialEvents.map(event=><article key={event.id} className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="font-bold text-amber-200">{specialEventLabels[event.event_type]??event.event_type}</div><time className="text-xs text-zinc-400" dateTime={event.effective_at}>{new Date(event.effective_at).toLocaleDateString('it-IT')}</time></div>{event.reason&&<div className="mt-2 font-semibold text-white">{event.reason}</div>}<p className="mt-1 text-sm leading-6 text-zinc-300">{event.description}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-zinc-400">{event.match_minute!=null&&<span>Minuto: {event.match_minute}’</span>}{event.remaining_minutes!=null&&<span>Residui: {event.remaining_minutes} minuti</span>}{event.home_score!=null&&event.away_score!=null&&<span>Punteggio: {event.home_score}-{event.away_score}</span>}{event.authority&&<span>Decisione: {event.authority}</span>}</div><a className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-neroverde-300 hover:underline" href={event.source_url} target="_blank" rel="noreferrer"><ExternalLink className="h-3.5 w-3.5"/>Fonte verificata: {event.source_provider}</a></article>)}</div></section>}

    {modules.events&&<section className="card mb-5 p-5"><div className="mb-4 flex items-center gap-2"><Activity className="h-5 w-5 text-neroverde-400"/><h2 className="text-lg font-bold">Eventi e marcatori</h2></div>{data.events.length?<div className="space-y-2">{data.events.map(event=><div key={event.id} className="grid grid-cols-[58px_34px_1fr] items-start gap-2 rounded-xl border border-zinc-800 bg-zinc-950/50 p-3"><div className="font-black tabular-nums text-zinc-300">{minuteLabel(event)}</div><div className="text-xl">{eventGlyph(event.type,event.detail)}</div><div><div className="font-semibold text-white">{event.player_id?<Link className="hover:text-neroverde-400" to={`/players/${event.player_id}`}>{event.player_name??'N/D'}</Link>:event.player_name??event.team_name??'Evento'}</div><div className="mt-0.5 text-xs text-zinc-400">{event.detail??event.type??'N/D'}{event.assist_name?<> · {String(event.type??'').toLowerCase().includes('sub')?'Entra':'Assist'}: {event.assist_player_id?<Link className="text-zinc-200 hover:text-neroverde-400" to={`/players/${event.assist_player_id}`}>{event.assist_name}</Link>:event.assist_name}</>:null}{event.home_score!=null&&event.away_score!=null?` · ${event.home_score}-${event.away_score}`:''}{event.comments?` · ${event.comments}`:''}</div></div></div>)}</div>:<p className="text-sm leading-6 text-zinc-300">{match.scorers}</p>}</section>}

    {modules.teamStats&&statRows.length>0&&<section className="card mb-5 p-5"><h2 className="mb-4 text-lg font-bold">Statistiche squadra</h2><div className="table-wrap"><table><thead><tr><th>Statistica</th>{(data.teamStats.length?data.teamStats.map(block=>block.team_name):[match.home_team,match.away_team]).map((name,index)=><th key={`${name}-${index}`} className="text-center">{name}</th>)}</tr></thead><tbody>{statRows.map(row=><tr key={row.type}><td>{statLabel(row.type)}</td>{row.values.map((value,index)=><td key={index} className="text-center font-semibold tabular-nums">{displayValue(value)}</td>)}</tr>)}</tbody></table></div></section>}

    {modules.lineups&&<section className="mb-5"><div className="mb-4 flex items-center gap-2"><Users className="h-5 w-5 text-neroverde-400"/><h2 className="text-lg font-bold">Formazioni</h2></div><div className="grid gap-4 xl:grid-cols-2">{data.lineups.map(lineup=><div className="card p-5" key={lineup.id}><div className="mb-4 flex items-center gap-3">{lineup.team_logo&&<RemoteImage className="h-9 w-9 object-contain" src={lineup.team_logo} alt={`Stemma ${lineup.team_name}`} width={36} height={36}/>}<div><div className="font-black">{lineup.team_name}</div><div className="text-xs text-zinc-400">{lineup.formation??'Modulo N/D'}{lineup.coach_name?` · Allenatore ${lineup.coach_name}`:''}</div></div></div><div className="mb-2 text-xs font-bold uppercase tracking-wider text-zinc-400">Titolari</div><PlayerGrid players={lineup.startXI}/>{lineup.substitutes.length>0&&<><div className="mb-2 mt-5 text-xs font-bold uppercase tracking-wider text-zinc-400">Panchina</div><PlayerGrid players={lineup.substitutes} bench/></>}</div>)}</div></section>}

    {modules.injuries&&<section className="card mb-5 p-5"><h2 className="mb-4 text-lg font-bold">Indisponibili / infortuni</h2><div className="grid gap-2 md:grid-cols-2">{data.injuries.map(injury=><div key={injury.id} className="rounded-xl border border-zinc-800 bg-zinc-950/50 p-3"><div className="font-semibold">{injury.player_id?<Link className="hover:text-neroverde-400" to={`/players/${injury.player_id}`}>{injury.player_name}</Link>:injury.player_name}</div><div className="mt-1 text-xs text-zinc-400">{injury.team_name??'Squadra N/D'} · {injury.type??injury.reason??'Indisponibile'}</div></div>)}</div></section>}

    {modules.playerStats&&<section><h2 className="mb-4 text-lg font-bold">Statistiche giocatori</h2><div className="space-y-5">{groupedPlayers.map(([team,players])=><div className="card p-5" key={team}><h3 className="mb-4 font-black">{team}</h3><div className="table-wrap"><table><thead><tr><th>Giocatore</th><th>Min</th><th>Voto</th><th>Gol</th><th>Assist</th><th>Tiri</th><th>Passaggi</th><th>Key pass</th><th>Tackle</th><th>Intercetti</th><th>Duelli</th><th>Dribbling</th><th>Falli</th><th>Cartellini</th></tr></thead><tbody>{players.map(player=><tr key={player.id}><td>{player.player_id?<Link className="font-semibold text-white hover:text-neroverde-400" to={`/players/${player.player_id}`}>{player.player_name}</Link>:player.player_name}<div className="text-xs text-zinc-400">{player.position??'N/D'}{player.captain?' · C':''}</div></td><td>{fmt(player.minutes)}</td><td>{player.archive_rating!=null?<><b className="text-neroverde-300">{Number(player.archive_rating).toFixed(1)}</b><div className="text-[10px] text-zinc-400">Archivio · {player.archive_rating_level} · {Math.round(Number(player.archive_rating_confidence??0)*100)}%</div></>:player.rating!=null?<><span>{Number(player.rating).toFixed(1)}</span><div className="text-[10px] text-zinc-400">Fonte esterna</div></>:'N/D'}</td><td>{fmt(player.goals)}</td><td>{fmt(player.assists)}</td><td>{fmt(player.shots_on)} / {fmt(player.shots_total)}</td><td>{fmt(player.passes_total)}</td><td>{fmt(player.passes_key)}</td><td>{fmt(player.tackles_total)}</td><td>{fmt(player.interceptions)}</td><td>{fmt(player.duels_won)} / {fmt(player.duels_total)}</td><td>{fmt(player.dribbles_success)} / {fmt(player.dribbles_attempts)}</td><td>{fmt(player.fouls_drawn)} / {fmt(player.fouls_committed)}</td><td>{player.yellow_cards?`🟨 ${player.yellow_cards}`:''}{player.red_cards?` 🟥 ${player.red_cards}`:''}{!player.yellow_cards&&!player.red_cards?'—':''}</td></tr>)}</tbody></table></div></div>)}</div></section>}

    {creditedSources.length>0&&<section className="card mt-5 p-5"><h2 className="mb-3 text-lg font-bold">Fonti e crediti</h2><p className="mb-3 text-sm text-zinc-400">I dati di questa scheda mantengono il collegamento alla fonte originale e alla data di verifica.</p><div className="flex flex-wrap gap-2">{creditedSources.map(source=><a key={`${source.source_provider}-${source.source_url}`} className="inline-flex items-center gap-1 rounded-lg border border-zinc-800 px-3 py-2 text-sm font-semibold text-neroverde-300 hover:border-neroverde-500 hover:underline" href={source.source_url} target="_blank" rel="noreferrer"><ExternalLink className="h-3.5 w-3.5"/>{source.source_provider??'Fonte originale'} · verificata {String(source.verified_at).slice(0,10)}</a>)}</div></section>}
    {!modules.events&&!modules.lineups&&!modules.teamStats&&!modules.playerStats&&<div className="card p-5 text-sm text-zinc-400">Questa gara ha copertura <b className="text-white">{match.completeness_level}</b>: sono mostrati soltanto i dati effettivamente disponibili, senza sezioni vuote o valori ricostruiti.</div>}
  </>;
}

function PlayerGrid({players,bench=false}:{players:LineupPlayer[];bench?:boolean}){return <div className="grid gap-2 sm:grid-cols-2">{players.map((row,index)=><div key={`${row.player?.id??index}`} className={bench?'rounded-lg border border-zinc-800 px-3 py-2 text-sm text-zinc-300':'rounded-lg bg-zinc-950 px-3 py-2 text-sm'}><span className="mr-2 text-zinc-400">{row.player?.number??'—'}</span>{row.player?.localPlayerId?<Link className="font-semibold text-white hover:text-neroverde-400" to={`/players/${row.player.localPlayerId}`}>{row.player.name??'N/D'}</Link>:row.player?.name??'N/D'} <span className="ml-1 text-xs text-zinc-400">{row.player?.pos??''}</span></div>)}</div>}
