import { FormEvent,useEffect,useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api } from '../services/api';
import { Empty,ErrorState,Loading,PageTitle } from '../components/Ui';
import MatchTable from '../components/MatchTable';
import ViewActions from '../components/ViewActions';
import type { Match } from '../types';
type Response={rows:Match[];total:number;page:number;pageSize:number};
export default function Matches(){
  const[params,setParams]=useSearchParams();const[data,setData]=useState<Response|null>(null);const[error,setError]=useState('');const opponent=params.get('opponent')||'',season=params.get('season')||'',competition=params.get('competition')||'',page=Math.max(1,Number(params.get('page')||1));const load=()=>{setError('');return api<Response>(`/matches?${params.toString()}&pageSize=50`).then(setData).catch(err=>setError(String(err)))};useEffect(()=>{void load()},[params]);const set=(key:string,value:string)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);if(key!=='page')next.delete('page');setParams(next)};const submit=(event:FormEvent)=>{event.preventDefault();void load()};if(error)return <ErrorState message={error} retry={load}/>;if(!data)return <Loading/>;
  return <><PageTitle title="Partite" subtitle="Filtri nell’URL, paginazione server-side e viste condivisibili." action={<ViewActions filename={`partite-pagina-${data.page}`} rows={data.rows} filters={{opponent:opponent||null,season:season||null,competition:competition||null,page:data.page,sort:'date desc'}} sources={data.rows.map(row=>row.source_provider??'')} columns={[{key:'date',label:'Data',unit:'ISO 8601',value:row=>row.date},{key:'season',label:'Stagione',value:row=>row.season},{key:'competition',label:'Competizione',value:row=>row.competition},{key:'home',label:'Casa',value:row=>row.home_team},{key:'homeScore',label:'Gol casa',value:row=>row.home_score},{key:'awayScore',label:'Gol trasferta',value:row=>row.away_score},{key:'away',label:'Trasferta',value:row=>row.away_team},{key:'source',label:'Fonte',value:row=>row.source_provider},{key:'verified',label:'Verificato il',unit:'ISO 8601',value:row=>row.last_verified_at}]}/>}/>
    <form onSubmit={submit} className="card mb-5 grid gap-3 p-4 md:grid-cols-[1fr_1fr_1fr_auto]"><input aria-label="Avversario" className="input" placeholder="Avversario" value={opponent} onChange={event=>set('opponent',event.target.value)}/><input aria-label="Stagione" className="input" placeholder="Stagione, es. 2013/14" value={season} onChange={event=>set('season',event.target.value)}/><input aria-label="Competizione" className="input" placeholder="Competizione" value={competition} onChange={event=>set('competition',event.target.value)}/><div className="flex gap-2"><button className="btn-primary">Aggiorna</button><button type="button" className="btn-secondary" onClick={()=>setParams({})}>Azzera filtri</button></div></form>
    {data.rows.length?<><MatchTable matches={data.rows}/><div className="mt-4 flex items-center justify-between text-sm"><span className="text-zinc-400">{data.total} risultati · pagina {data.page}</span><div className="flex gap-2"><button className="btn-secondary" disabled={page<=1} onClick={()=>set('page',String(page-1))}>Precedente</button><button className="btn-secondary" disabled={page*data.pageSize>=data.total} onClick={()=>set('page',String(page+1))}>Successiva</button></div></div></>:<Empty/>}
  </>;
}
