import { lazy,Suspense,useEffect,useMemo,useRef,useState,type ChangeEvent } from 'react';
import { Archive,ArrowRight,CalendarDays,Clapperboard,Download,Heart,Landmark,LockKeyhole,Shield,Trash2,Upload,Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import MemoryButton from '../components/MemoryButton';
import { PageTitle,StatCard } from '../components/Ui';
import { useMuseum } from '../context/MuseumContext';
import { calculateMuseumStats,emotionLabels,experienceLabels,exportPersonalMuseum,parsePersonalMuseum,type MuseumEntityType } from '../services/personalMuseum';

const MuseumTour=lazy(()=>import('../components/MuseumTour'));
const filterLabels:{key:'all'|MuseumEntityType;label:string;icon:typeof Landmark}[]=[{key:'all',label:'Tutti',icon:Archive},{key:'match',label:'Partite',icon:Clapperboard},{key:'player',label:'Giocatori',icon:Users},{key:'season',label:'Stagioni',icon:CalendarDays}];

export default function Museum(){
  const museum=useMuseum(),fileRef=useRef<HTMLInputElement>(null),[filter,setFilter]=useState<'all'|MuseumEntityType>('all'),[tourOpen,setTourOpen]=useState(false),[roomIndex,setRoomIndex]=useState(0),[status,setStatus]=useState(''),[confirmClear,setConfirmClear]=useState(false),[supporterSince,setSupporterSince]=useState(museum.state.profile.supporterSince),[dedication,setDedication]=useState(museum.state.profile.dedication);
  const stats=useMemo(()=>calculateMuseumStats(museum.memories),[museum.memories]);
  const visible=filter==='all'?museum.memories:museum.memories.filter(memory=>memory.type===filter);
  useEffect(()=>{setSupporterSince(museum.state.profile.supporterSince);setDedication(museum.state.profile.dedication);},[museum.state.profile.supporterSince,museum.state.profile.dedication]);
  useEffect(()=>{fileRef.current?.setAttribute('aria-label','Importa backup del museo');},[]);
  const enterMuseum=()=>{setRoomIndex(0);setTourOpen(true);};
  const download=()=>{const blob=new Blob([exportPersonalMuseum(museum.state)],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`museo-neroverde-${new Date().toISOString().slice(0,10)}.json`;document.body.append(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);setStatus('Backup del museo esportato.');};
  const importFile=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;if(file.size>2_000_000){setStatus('Backup troppo grande: il limite è 2 MB.');return;}try{museum.importState(parsePersonalMuseum(await file.text()));setStatus('Backup importato: i ricordi più recenti sono stati uniti al museo.');}catch(error){setStatus(error instanceof Error?error.message:'File del museo non valido.');}};
  const saveProfile=()=>{museum.updateProfile({supporterSince,dedication});setStatus('Dedica del museo salvata.');};
  const clear=()=>{if(!confirmClear){setConfirmClear(true);return;}museum.clearMuseum();setSupporterSince('');setDedication('');setConfirmClear(false);setStatus('Museo svuotato su questo dispositivo.');};
  return <>
    <PageTitle eyebrow="Spazio personale" tone="violet" title="Il mio Museo Neroverde" subtitle="Un luogo privato dove partite, giocatori e stagioni diventano la tua storia. Nessun profilo pubblico, nessuna condivisione: resta tutto in questo browser." action={<div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={download} disabled={!museum.memories.length}><Download aria-hidden="true" className="h-4 w-4"/>Esporta backup</button><button className="btn-secondary" onClick={()=>fileRef.current?.click()}><Upload aria-hidden="true" className="h-4 w-4"/>Importa</button><input ref={fileRef} className="sr-only" type="file" accept="application/json,.json" onChange={importFile}/></div>}/>
    <section className="museum-portal-card"><div className="museum-portal-beam" aria-hidden="true"/><div className="relative z-10 grid items-center gap-7 lg:grid-cols-[1.2fr_.8fr]"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/[.08] px-3 py-1.5 text-[10px] font-black uppercase tracking-[.18em] text-emerald-200"><LockKeyhole aria-hidden="true" className="h-3.5 w-3.5"/>Museo privato e locale</div><h2 className="max-w-2xl text-3xl font-black leading-tight text-white md:text-5xl">La storia del Sassuolo,<br/><span className="museum-gradient-text">come l’hai vissuta tu.</span></h2><p className="mt-4 max-w-xl text-sm leading-6 text-zinc-300">Aggiungi un ricordo dalle schede dell’archivio. Il tour trasforma emozioni e momenti in sale, luci e connessioni costruite soltanto per te.</p><button className="museum-enter-button mt-6" onClick={enterMuseum}><Landmark aria-hidden="true" className="h-5 w-5"/>{museum.memories.length?'Entra nel mio museo':'Scopri il museo'}<ArrowRight aria-hidden="true" className="h-4 w-4"/></button></div><div className="museum-portal-visual" aria-hidden="true"><div className="museum-door"><span/><span/><span/></div><div className="museum-floor"/></div></div></section>
    <div className="my-5 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6"><StatCard label="Ricordi" value={stats.total}/><StatCard label="Partite" value={stats.matches}/><StatCard label="I miei eroi" value={stats.players}/><StatCard label="Stagioni" value={stats.seasons}/><StatCard label="Allo stadio" value={stats.stadium}/><StatCard label="Annata più vissuta" value={stats.mostLivedSeason}/></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_340px]">
      <section aria-labelledby="museum-memories-title"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h2 id="museum-memories-title" className="text-xl font-black">I miei ricordi</h2><p className="mt-1 text-xs text-zinc-400">{visible.length} {visible.length===1?'frammento':'frammenti'} nel percorso</p></div><div className="flex gap-2 overflow-x-auto" role="group" aria-label="Filtra ricordi">{filterLabels.map(({key,label,icon:Icon})=><button key={key} className={`${filter===key?'btn-primary':'btn-secondary'} !min-h-9 !px-3 text-xs`} aria-pressed={filter===key} onClick={()=>setFilter(key)}><Icon aria-hidden="true" className="h-3.5 w-3.5"/>{label}</button>)}</div></div>
        {visible.length?<div className="space-y-3">{visible.map(memory=><article className="museum-memory-card" key={memory.key}><div className="museum-memory-symbol" aria-hidden="true">{memory.type==='match'?<Clapperboard/>:memory.type==='player'?<Users/>:<CalendarDays/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2 text-[10px] font-black uppercase tracking-wider text-zinc-500"><span>{memory.type==='match'?'Partita':memory.type==='player'?'Giocatore':'Stagione'}</span>{memory.season&&<><span>·</span><span>{memory.season}</span></>}<span>·</span><span className="text-amber-300">{emotionLabels[memory.emotion]}</span></div><h3 className="mt-1 truncate text-lg font-black text-white">{memory.label}</h3><p className="mt-1 text-xs text-zinc-400">{experienceLabels[memory.experience]} · intensità {memory.intensity}/5</p>{(memory.favoriteMoment||memory.note)&&<p className="mt-3 line-clamp-2 text-sm italic leading-6 text-zinc-300">“{memory.favoriteMoment||memory.note}”</p>}<div className="mt-3 flex flex-wrap gap-2"><Link className="btn-secondary !min-h-9 !px-3 text-xs" to={memory.url}>Apri nell’archivio<ArrowRight aria-hidden="true" className="h-3.5 w-3.5"/></Link><MemoryButton target={memory} compact/></div></div></article>)}</div>:<div className="card grid min-h-72 place-items-center p-7 text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-emerald-300/20 bg-emerald-300/[.07] text-emerald-200"><Heart aria-hidden="true" className="h-6 w-6"/></div><h3 className="mt-4 text-lg font-black">{museum.memories.length?'Nessun ricordo in questa sala':'Il museo aspetta la prima memoria'}</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-zinc-400">Apri una partita, un giocatore o una stagione e premi “Aggiungi al museo”. Potrai raccontare dove eri e cosa hai provato.</p><div className="mt-5 flex flex-wrap justify-center gap-2"><Link className="btn-secondary" to="/matches">Esplora partite</Link><Link className="btn-secondary" to="/players">Esplora giocatori</Link><Link className="btn-secondary" to="/seasons">Esplora stagioni</Link></div></div></div>}
      </section>
      <aside className="space-y-4"><section className="card p-5"><div className="flex items-center gap-2"><Heart aria-hidden="true" className="h-4 w-4 text-amber-300"/><h2 className="font-black">La dedica all’ingresso</h2></div><p className="mt-2 text-xs leading-5 text-zinc-400">Compare nella sala finale del tour. Anche questa resta privata.</p><label className="mt-4 block text-xs font-bold text-zinc-300">Neroverde dal<input className="input mt-2 w-full" maxLength={20} placeholder="es. 2008 o da sempre" value={supporterSince} onChange={event=>setSupporterSince(event.target.value)}/></label><label className="mt-4 block text-xs font-bold text-zinc-300">Dedica<textarea className="input mt-2 min-h-24 w-full resize-y" maxLength={180} placeholder="Una frase che racconta il tuo legame…" value={dedication} onChange={event=>setDedication(event.target.value)}/><span className="mt-1 block text-right text-[10px] text-zinc-500">{dedication.length}/180</span></label><button className="btn-primary mt-3 w-full" onClick={saveProfile}>Salva dedica</button></section>
        <section className="card border-emerald-300/15 p-5"><div className="flex items-center gap-2 text-emerald-200"><Shield aria-hidden="true" className="h-4 w-4"/><h2 className="font-black">Privacy, davvero</h2></div><ul className="mt-3 space-y-2 text-xs leading-5 text-zinc-400"><li>• Nessun account o profilo pubblico.</li><li>• Nessuna API riceve note o emozioni.</li><li>• Il backup JSON lo controlli tu.</li><li>• Importazione unita senza duplicati.</li></ul><Link className="mt-3 inline-flex text-xs font-bold text-neroverde-300 hover:underline" to="/methodology#personal-museum">Come funziona la custodia locale →</Link></section>
        <section className="card p-5"><h2 className="font-black">Zona delicata</h2><p className="mt-2 text-xs leading-5 text-zinc-400">Svuota soltanto i ricordi privati. I dati storici dell’archivio non vengono toccati.</p><button className={`btn-secondary mt-3 w-full ${confirmClear?'border-red-400/50 text-red-200':''}`} disabled={!museum.memories.length&&!museum.state.profile.dedication&&!museum.state.profile.supporterSince} onClick={clear}><Trash2 aria-hidden="true" className="h-4 w-4"/>{confirmClear?'Conferma: svuota il museo':'Svuota il museo'}</button></section>
      </aside>
    </div>
    {(status||museum.storageError)&&<div className="fixed bottom-4 right-4 z-[70] max-w-sm rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 text-sm font-semibold shadow-2xl" role="status" aria-live="polite">{museum.storageError||status}</div>}
    {tourOpen&&<Suspense fallback={<div className="fixed inset-0 z-[110] grid place-items-center bg-black text-sm font-bold text-emerald-200" role="status">Le luci del museo si stanno accendendo…</div>}><MuseumTour memories={museum.memories} profile={museum.state.profile} index={roomIndex} onIndex={setRoomIndex} onClose={()=>setTourOpen(false)}/></Suspense>}
  </>;
}
