import { useEffect,useState } from 'react';
import type { ReactElement } from 'react';
import { AlertTriangle, BadgeCheck, CalendarDays, Database, MapPin, Ruler, Scale } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../services/api';
import { Empty,Loading,PageTitle,RemoteImage,SourceBadge,StatCard,fmt } from '../components/Ui';
import MemoryButton from '../components/MemoryButton';
import type { Player,PlayerSeason,Transfer } from '../types';

type Aggregate=Pick<PlayerSeason,'competition'|'appearances'|'starts'|'minutes'|'goals'|'assists'|'yellow_cards'|'yellow_red_cards'|'red_cards'|'clean_sheets'>&{seasons:number};
type Identity={status:'verified'|'review'|'unresolved';sourceIds:{id:number;source_provider:string;source_player_id:string;source_url:string|null;last_verified_at:string|null}[];conflicts:{id:number;raw_name:string;source_provider:string|null;reason:string|null}[]};
type Source={id?:number;entity_type:string;entity_id:number;field:string|null;source_url:string;note:string|null;source_provider:string|null;verified_at:string|null};
type D={player:(Player&{derived_clean_sheets:number|null;seasons:number})|null;seasons:PlayerSeason[];competitionTotals:Aggregate[];cleanSheets:{season:string;competition:string;clean_sheets:number}[];transfers:Transfer[];identity:Identity;sources:Source[]};

export default function PlayerDetail(){
  const {id}=useParams();
  const [data,setData]=useState<D|null>(null);
  useEffect(()=>{api<D>(`/players/${id}`).then(setData)},[id]);
  if(!data)return <Loading/>;
  if(!data.player)return <Empty title="Giocatore non trovato"/>;
  const player=data.player;
  const isGoalkeeper=String(player.position??'').toLowerCase()==='goalkeeper';
  const birthplace=[player.birth_place,player.birth_country].filter(Boolean).join(', ');
  const identityLabel=data.identity.status==='verified'?'Identità verificata':data.identity.status==='review'?'Identità da revisionare':'Identità senza ID esterno';
  const profileSources=data.sources.filter((source,index,all)=>all.findIndex(other=>other.source_url===source.source_url&&other.source_provider===source.source_provider)===index);
  const sourceProviders=[...new Set(profileSources.map(source=>source.source_provider??'Fonte non indicata'))];
  return <>
    <PageTitle title={player.name} subtitle={[player.position,player.nationality].filter(Boolean).join(' · ')||'Profilo giocatore'} action={<MemoryButton target={{type:'player',entityId:String(player.id),label:player.name,url:`/players/${player.id}`}}/>}/>
    <div className={`mb-5 flex items-start gap-3 rounded-xl border p-4 ${data.identity.status==='review'?'border-amber-400/30 bg-amber-400/10':'border-zinc-800 bg-zinc-900/60'}`}>{data.identity.status==='verified'?<BadgeCheck className="h-5 w-5 shrink-0 text-neroverde-300"/>:<AlertTriangle className="h-5 w-5 shrink-0 text-amber-300"/>}<div><div className="font-bold">{identityLabel}</div><p className="mt-1 text-xs text-zinc-400">{data.identity.status==='review'?`${data.identity.conflicts.length} segnalazioni aperte: gli aggregati restano collegati al profilo corrente finché la revisione non è conclusa.`:data.identity.status==='verified'?`${data.identity.sourceIds.length} identificativi di fonte collegati al profilo.`:'Nessun conflitto aperto, ma manca ancora un identificativo esterno stabile.'}</p></div></div>

    <div className="mb-6 grid gap-4 lg:grid-cols-[220px_1fr]">
      <div className="card flex items-center justify-center p-5"><RemoteImage src={player.photo_url} className="h-44 w-44 rounded-2xl object-cover" alt={`Foto di ${player.name}`} width={176} height={176} fallback={<div className="grid h-44 w-44 place-items-center rounded-2xl bg-zinc-800 text-4xl font-black">{player.name.slice(0,2).toUpperCase()}</div>}/></div>
      <div className="space-y-4"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><StatCard label="Presenze Sassuolo" value={player.appearances}/><StatCard label="Titolarità" value={player.starts}/><StatCard label="Gol" value={player.goals}/><StatCard label="Assist" value={player.assists}/><StatCard label="Minuti" value={player.minutes}/><StatCard label="Gialli" value={player.yellow_cards}/><StatCard label="Doppi gialli" value={player.yellow_red_cards}/><StatCard label="Rossi" value={player.red_cards}/>{isGoalkeeper&&<StatCard label="Clean sheet" value={player.derived_clean_sheets}/>}</div>
        <section className="card p-4" aria-labelledby="bio-title"><h2 id="bio-title" className="mb-3 font-bold">Biografia essenziale</h2><dl className="grid gap-3 text-sm sm:grid-cols-2 xl:grid-cols-3"><Bio icon={<CalendarDays/>} label="Data di nascita" value={player.birth_date}/><Bio icon={<MapPin/>} label="Luogo di nascita" value={birthplace||null}/><Bio icon={<Ruler/>} label="Altezza" value={player.height}/><Bio icon={<Scale/>} label="Peso" value={player.weight}/><Bio icon={<CalendarDays/>} label="Prima presenza" value={player.first_appearance}/><Bio icon={<CalendarDays/>} label="Ultima presenza" value={player.last_appearance}/></dl></section>
      </div>
    </div>

    {data.competitionTotals.length>0&&<><h2 className="mb-3 text-lg font-bold">Totali per competizione</h2><div className="mb-6 table-wrap"><table><thead><tr><th>Competizione</th><th>Stagioni</th><th>Pres.</th><th>Tit.</th><th>Min.</th><th>Gol</th><th>Assist</th><th>Gialli</th><th>Doppi gialli</th><th>Rossi</th></tr></thead><tbody>{data.competitionTotals.map(row=><tr key={row.competition}><td>{row.competition}</td><td>{fmt(row.seasons)}</td><td>{fmt(row.appearances)}</td><td>{fmt(row.starts)}</td><td>{fmt(row.minutes)}</td><td>{fmt(row.goals)}</td><td>{fmt(row.assists)}</td><td>{fmt(row.yellow_cards)}</td><td>{fmt(row.yellow_red_cards)}</td><td>{fmt(row.red_cards)}</td></tr>)}</tbody></table></div></>}

    {data.seasons.length>0&&<><h2 className="mb-3 text-lg font-bold">Statistiche stagione per stagione</h2><div className="mb-6 table-wrap"><table><thead><tr><th>Stagione</th><th>Competizione</th><th>Pres.</th><th>Tit.</th><th>Min.</th><th>Gol</th><th>Assist</th><th>Gialli</th><th>Doppi gialli</th><th>Rossi</th>{isGoalkeeper&&<th>Clean sheet</th>}<th>Fonte</th></tr></thead><tbody>{data.seasons.map(season=><tr key={`${season.season}-${season.competition}`}><td><Link className="font-bold text-neroverde-300 hover:underline" to={`/seasons/${encodeURIComponent(season.season)}?competition=${encodeURIComponent(season.competition)}`}>{season.season}</Link></td><td>{season.competition}</td><td>{fmt(season.appearances)}</td><td>{fmt(season.starts)}</td><td>{fmt(season.minutes)}</td><td>{fmt(season.goals)}</td><td>{fmt(season.assists)}</td><td>{fmt(season.yellow_cards)}</td><td>{fmt(season.yellow_red_cards)}</td><td>{fmt(season.red_cards)}</td>{isGoalkeeper&&<td>{fmt(data.cleanSheets.find(row=>row.season===season.season&&row.competition===season.competition)?.clean_sheets??season.clean_sheets)}</td>}<td><SourceBadge provider={season.source_provider} url={(season as PlayerSeason&{source_url?:string|null}).source_url} verifiedAt={season.last_verified_at}/></td></tr>)}</tbody></table></div></>}

    {data.transfers.length>0&&<><h2 className="mb-3 text-lg font-bold">Trasferimenti</h2><div className="mb-6 table-wrap"><table><thead><tr><th>Data</th><th>Movimento</th><th>Da</th><th>A</th><th>Tipo</th><th>Fonte</th></tr></thead><tbody>{data.transfers.map(transfer=><tr key={transfer.id}><td>{fmt(transfer.date)}</td><td>{transfer.direction==='IN'?'Arrivo':'Partenza'}</td><td>{fmt(transfer.from_team_name)}</td><td>{fmt(transfer.to_team_name)}</td><td>{fmt(transfer.type)}</td><td><SourceBadge provider={transfer.source_provider} url={transfer.source_url} verifiedAt={transfer.last_verified_at}/></td></tr>)}</tbody></table></div></>}

    {(profileSources.length>0||data.identity.sourceIds.length>0)&&<section className="card p-5" aria-labelledby="sources-title"><div className="mb-4 flex items-center gap-2"><Database className="h-5 w-5 text-neroverde-300"/><h2 id="sources-title" className="text-lg font-bold">Fonti e identità</h2></div>{data.identity.sourceIds.length>0&&<div><div className="mb-2 text-xs font-bold uppercase tracking-wider text-zinc-400">Identificativi collegati</div><div className="flex flex-wrap gap-2">{data.identity.sourceIds.map(source=><SourceBadge key={`identity-${source.id}`} provider={`${source.source_provider} · ID ${source.source_player_id}`} url={source.source_url} verifiedAt={source.last_verified_at}/>)}</div></div>}{profileSources.length>0&&<div className={data.identity.sourceIds.length?'mt-5 border-t border-zinc-800 pt-4':''}><p className="text-sm text-zinc-400"><b className="text-zinc-200">{profileSources.length} riferimenti</b> da {sourceProviders.length} provider: {sourceProviders.join(', ')}.</p><details className="mt-3 rounded-xl border border-zinc-800 bg-zinc-950/40"><summary className="cursor-pointer px-4 py-3 text-sm font-bold text-neroverde-300">Consulta tutti i riferimenti</summary><div className="flex flex-wrap gap-2 border-t border-zinc-800 p-4">{profileSources.map((source,index)=><SourceBadge key={`source-${index}`} provider={source.source_provider??source.note??'Fonte'} url={source.source_url} verifiedAt={source.verified_at}/>)}</div></details></div>}</section>}
  </>;
}

function Bio({icon,label,value}:{icon:ReactElement;label:string;value:string|null|undefined}){return <div className="flex gap-2"><span className="mt-0.5 text-zinc-400 [&>svg]:h-4 [&>svg]:w-4">{icon}</span><div><dt className="text-xs font-bold uppercase tracking-wider text-zinc-400">{label}</dt><dd className="mt-1 font-semibold text-zinc-200">{fmt(value)}</dd></div></div>}
