import { useEffect,useState } from 'react';
import { Link,useSearchParams } from 'react-router-dom';
import { ArrowDown,ArrowUp,ChevronsUpDown } from 'lucide-react';
import { api } from '../services/api';
import { Empty,ErrorState,Loading,PageTitle,Pagination,RemoteImage,fmt,SourceBadge } from '../components/Ui';
import ViewActions from '../components/ViewActions';
import type { Player } from '../types';

type SortKey='appearances'|'goals'|'assists'|'minutes'|'name';type SortDirection='asc'|'desc';
type Response={rows:Player[];total:number;page:number;pageSize:number};
type Facets={positions:string[];nationalities:string[]};
const sortableColumns:ReadonlyArray<{key:Exclude<SortKey,'name'>;label:string}>=[{key:'appearances',label:'Pres.'},{key:'goals',label:'Gol'},{key:'assists',label:'Assist'},{key:'minutes',label:'Minuti'}];

export default function Players(){
  const[params,setParams]=useSearchParams();const[d,setD]=useState<Response|null>(null);const[facets,setFacets]=useState<Facets>({positions:[],nationalities:[]});const[error,setError]=useState('');const sort=(params.get('sort') as SortKey)||'appearances';const direction=(params.get('direction') as SortDirection)||'desc';const position=params.get('position')||'',nationality=params.get('nationality')||'',season=params.get('season')||'',page=Math.max(1,Number(params.get('page')||1));
  const load=()=>{const query=new URLSearchParams(params);query.set('sort',sort);query.set('direction',direction);query.set('page',String(page));query.set('pageSize','50');setError('');void api<Response>(`/players?${query}`).then(setD).catch(err=>setError(String(err)))};
  useEffect(()=>{void api<Facets>('/player-facets').then(setFacets).catch(()=>setFacets({positions:[],nationalities:[]}))},[]);useEffect(load,[sort,direction,position,nationality,season,page]);
  const options=facets;
  const setFilter=(key:string,value:string)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);if(key!=='page')next.delete('page');setParams(next,{replace:true})};
  const changeSort=(key:SortKey)=>{const next=new URLSearchParams(params);next.set('sort',key);next.set('direction',key===sort?(direction==='desc'?'asc':'desc'):(key==='name'?'asc':'desc'));setParams(next,{replace:true})};
  const sortableHeader=({key,label}:{key:Exclude<SortKey,'name'>;label:string})=>{const active=sort===key;const Icon=active?(direction==='desc'?ArrowDown:ArrowUp):ChevronsUpDown;return <th key={key} aria-sort={active?(direction==='desc'?'descending':'ascending'):'none'}><button type="button" className={`inline-flex items-center gap-1.5 whitespace-nowrap transition hover:text-white focus-visible:rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neroverde-400 ${active?'text-neroverde-400':''}`} onClick={()=>changeSort(key)} title={`Ordina per ${label}`}><span>{label}</span><Icon aria-hidden="true" className="h-3.5 w-3.5"/></button></th>};
  if(error)return <ErrorState message={error} retry={load}/>;if(!d)return <Loading/>;
  return <><PageTitle title="Giocatori" subtitle="Filtra l'archivio per ruolo, nazionalità e stagione. I campi non rilevati dalla fonte restano N/D." action={<ViewActions filename={`giocatori-pagina-${d.page}`} rows={d.rows} filters={{position:position||null,nationality:nationality||null,season:season||null,sort,direction,page:d.page}} sources={d.rows.map(row=>row.source_provider??'')} columns={[{key:'name',label:'Giocatore',value:row=>row.name},{key:'position',label:'Ruolo',value:row=>row.position},{key:'nationality',label:'Nazionalità',value:row=>row.nationality},{key:'appearances',label:'Presenze',unit:'partite',value:row=>row.appearances},{key:'minutes',label:'Minuti',unit:'min',value:row=>row.minutes},{key:'goals',label:'Gol',value:row=>row.goals},{key:'assists',label:'Assist',value:row=>row.assists},{key:'source',label:'Fonte',value:row=>row.source_provider},{key:'verified',label:'Verificato il',unit:'ISO 8601',value:row=>row.last_verified_at}]}/>}/>
    <div className="card mb-5 grid gap-3 p-4 md:grid-cols-4"><select aria-label="Ruolo" className="input" value={position} onChange={event=>setFilter('position',event.target.value)}><option value="">Tutti i ruoli</option>{options.positions.map(item=><option key={item}>{item}</option>)}</select><select aria-label="Nazionalità" className="input" value={nationality} onChange={event=>setFilter('nationality',event.target.value)}><option value="">Tutte le nazionalità</option>{options.nationalities.map(item=><option key={item}>{item}</option>)}</select><input aria-label="Stagione" className="input" value={season} onChange={event=>setFilter('season',event.target.value)} placeholder="Stagione, es. 2012/13"/><select aria-label="Ordinamento" className="input" value={sort} onChange={event=>changeSort(event.target.value as SortKey)}><option value="appearances">Presenze</option><option value="goals">Gol</option><option value="assists">Assist</option><option value="minutes">Minuti</option><option value="name">Nome</option></select></div>
    {!d.rows.length?<Empty text="Nessun giocatore corrisponde ai filtri selezionati."/>:<><div className="table-wrap"><table><thead><tr><th>Giocatore</th><th>Ruolo</th><th>Nazionalità</th>{sortableColumns.map(sortableHeader)}<th>Identità fonte</th><th>Fonte</th></tr></thead><tbody>{d.rows.map(player=><tr key={player.id}><td><Link className="flex items-center gap-3 font-bold text-neroverde-400 hover:underline" to={`/players/${player.id}`}><RemoteImage src={player.photo_url} className="h-9 w-9 rounded-full bg-zinc-800 object-cover" alt={`Foto di ${player.name}`} width={36} height={36}/>{player.name}</Link></td><td>{fmt(player.position)}</td><td>{fmt(player.nationality)}</td><td>{fmt(player.appearances)}</td><td>{fmt(player.goals)}</td><td>{fmt(player.assists)}</td><td>{fmt(player.minutes)}</td><td className="text-zinc-400">{fmt(player.source_external_id??player.api_football_id)}</td><td><SourceBadge provider={player.source_provider} url={player.source_url} verifiedAt={player.last_verified_at}/></td></tr>)}</tbody></table></div><Pagination page={d.page} pageSize={d.pageSize} total={d.total} onPage={value=>setFilter('page',String(value))}/></>}
  </>;
}
