import { useEffect,useState } from 'react';
import { useParams } from 'react-router-dom';
import { api } from '../services/api';
import { Empty,Loading,PageTitle,StatCard,fmt } from '../components/Ui';
import type { Player,PlayerSeason,Transfer } from '../types';
type D={player:(Player&{derived_clean_sheets:number|null})|null;seasons:PlayerSeason[];cleanSheets:{season:string;competition:string;clean_sheets:number}[];transfers:Transfer[]};
export default function PlayerDetail(){
  const{id}=useParams();const[d,setD]=useState<D|null>(null);
  useEffect(()=>{api<D>(`/players/${id}`).then(setD)},[id]);
  if(!d)return <Loading/>;if(!d.player)return <Empty title="Giocatore non trovato"/>;
  const p=d.player;const isGoalkeeper=String(p.position??'').toLowerCase()==='goalkeeper';
  return <><PageTitle title={p.name} subtitle={[p.position,p.nationality].filter(Boolean).join(' · ')||'Profilo giocatore'}/><div className="mb-6 grid gap-4 lg:grid-cols-[220px_1fr]"><div className="card flex items-center justify-center p-5">{p.photo_url?<img src={p.photo_url} className="h-44 w-44 rounded-2xl object-cover" alt={p.name}/>:<div className="grid h-44 w-44 place-items-center rounded-2xl bg-zinc-800 text-4xl font-black">{p.name.slice(0,2).toUpperCase()}</div>}</div><div><div className="grid grid-cols-2 gap-3 md:grid-cols-5"><StatCard label="Presenze Sassuolo" value={p.appearances}/><StatCard label="Gol" value={p.goals}/><StatCard label="Assist" value={p.assists}/><StatCard label="Minuti" value={p.minutes}/>{isGoalkeeper&&<StatCard label="Clean sheet" value={p.derived_clean_sheets}/>}</div></div></div>{d.seasons.length>0&&<><h2 className="mb-3 text-lg font-bold">Statistiche stagione per stagione</h2><div className="mb-6 table-wrap"><table><thead><tr><th>Stagione</th><th>Comp.</th><th>Pres.</th><th>Tit.</th><th>Min.</th><th>Gol</th><th>Assist</th>{isGoalkeeper&&<th>Clean sheet</th>}</tr></thead><tbody>{d.seasons.map(s=><tr key={`${s.season}${s.competition}`}><td>{s.season}</td><td>{s.competition}</td><td>{fmt(s.appearances)}</td><td>{fmt(s.starts)}</td><td>{fmt(s.minutes)}</td><td>{fmt(s.goals)}</td><td>{fmt(s.assists)}</td>{isGoalkeeper&&<td>{fmt(d.cleanSheets.find(x=>x.season===s.season&&x.competition===s.competition)?.clean_sheets)}</td>}</tr>)}</tbody></table></div></>}{d.transfers.length>0&&<><h2 className="mb-3 text-lg font-bold">Trasferimenti</h2><div className="table-wrap"><table><thead><tr><th>Data</th><th>Movimento</th><th>Da</th><th>A</th><th>Tipo</th></tr></thead><tbody>{d.transfers.map(t=><tr key={t.id}><td>{fmt(t.date)}</td><td>{t.direction==='IN'?'Arrivo':'Partenza'}</td><td>{fmt(t.from_team_name)}</td><td>{fmt(t.to_team_name)}</td><td>{fmt(t.type)}</td></tr>)}</tbody></table></div></>}</>}
