import { useEffect,useMemo,useState } from 'react';
import { Link,useParams,useSearchParams } from 'react-router-dom';
import { BarChart3,RefreshCw,Table2,Users,ArrowLeftRight,CalendarDays,Trophy } from 'lucide-react';
import { api,post } from '../services/api';
import { Breadcrumb,CompetitionBadge,Empty,Loading,PageTitle,StatCard,fmt,SourceBadge } from '../components/Ui';
import MatchTable from '../components/MatchTable';
import type { Match,Player,Season,Standing,TeamSeasonStats,Transfer } from '../types';

type SquadRow=Player&{player_id:number;player_name:string;player_photo?:string|null;stats_competition?:string|null;appearances:number|null;goals:number|null;assists:number|null;minutes:number|null;rating?:number|null;shots_total?:number|null;shots_on?:number|null;passes_key?:number|null;tackles_total?:number|null};
type Leader={id:number|null;name:string;photo_url:string|null;position:string|null;goals?:number|null;assists?:number|null;appearances:number|null;minutes:number|null};
type D={season:Season|null;competitions:Season[];matches:Match[];bracket:Match[];squad:SquadRow[];squadCoverage:{in_squad:number;played:number};standings:Standing[];teamStats:TeamSeasonStats|null;transfers:Transfer[];topScorer:Leader|null;topAssists:Leader|null};
type Tab='overview'|'standings'|'squad'|'team-stats'|'transfers'|'matches';

const tabDefs:[Tab,string,any][]=[['overview','Panoramica',Trophy],['standings','Classifica',Table2],['squad','Rosa & statistiche',Users],['team-stats','Statistiche squadra',BarChart3],['transfers','Trasferimenti',ArrowLeftRight],['matches','Partite',CalendarDays]];
const ratio=(v:number|null|undefined)=>v==null?'N/D':v.toFixed(2);
const cupRoundOrder=['Turno preliminare','Primo turno','Secondo turno','Terzo turno','Quarto turno','Sedicesimi di finale','Ottavi di finale','Quarti di finale','Semifinali','Finale'];
const cupExitLabel=(round:string|null)=>({
  'Turno preliminare':'Prelim.','Primo turno':'1° turno','Secondo turno':'2° turno','Terzo turno':'3° turno','Quarto turno':'4° turno','Sedicesimi di finale':'Sedicesimi','Ottavi di finale':'Ottavi','Quarti di finale':'Quarti','Semifinali':'Semifinali','Finale':'Finale'
} as Record<string,string>)[round??'']??'N/D';
const cupRoundLabel=(round:string|null|undefined)=>{
  const key=(round??'').trim().replace(/\s+/g,' ').toLowerCase();
  return ({
    'preliminary round':'Turno preliminare','turno preliminare':'Turno preliminare',
    'round 1':'Primo turno','first round':'Primo turno','1st round':'Primo turno','primo turno':'Primo turno',
    'round 2':'Secondo turno','second round':'Secondo turno','2nd round':'Secondo turno','secondo turno':'Secondo turno',
    'round 3':'Terzo turno','third round':'Terzo turno','3rd round':'Terzo turno','terzo turno':'Terzo turno',
    'round 4':'Quarto turno','fourth round':'Quarto turno','4th round':'Quarto turno','quarto turno':'Quarto turno',
    'round of 32':'Sedicesimi di finale','round of 16':'Ottavi di finale','sedicesimi di finale':'Sedicesimi di finale','ottavi di finale':'Ottavi di finale',
    'quarterfinals':'Quarti di finale','quarter-finals':'Quarti di finale','quarti di finale':'Quarti di finale',
    'semifinals':'Semifinali','semi-finals':'Semifinali','semifinali':'Semifinali','final':'Finale','finale':'Finale'
  } as Record<string,string>)[key]??(round?.trim()||'Turno non definito');
};
const CupBracket=({matches}:{matches:Match[]})=>{
  const groups=new Map<string,Match[]>();
  for(const match of matches){const round=cupRoundLabel(match.round);groups.set(round,[...(groups.get(round)??[]),match]);}
  const fixture=(match:Match)=><article className={`rounded-md border px-2 py-1.5 text-[10px] shadow-sm ${/sassuolo/i.test(match.home_team)||/sassuolo/i.test(match.away_team)?'border-neroverde-300 bg-neroverde-400/15':'border-white/20 bg-zinc-950/80'}`} key={match.external_key??match.id}><div className="flex min-w-0 items-center justify-between gap-2"><span title={match.home_team} className={`min-w-0 truncate ${/sassuolo/i.test(match.home_team)?'font-black text-neroverde-300':''}`}>{match.home_team}</span><b className="shrink-0 tabular-nums">{fmt(match.home_score)}</b></div><div className="mt-0.5 flex min-w-0 items-center justify-between gap-2"><span title={match.away_team} className={`min-w-0 truncate ${/sassuolo/i.test(match.away_team)?'font-black text-neroverde-300':''}`}>{match.away_team}</span><b className="shrink-0 tabular-nums">{fmt(match.away_score)}</b></div></article>;
  const ottavi=groups.get('Ottavi di finale')??[],quarti=groups.get('Quarti di finale')??[],semifinali=groups.get('Semifinali')??[],finale=groups.get('Finale')??[];
  const early=[...groups.entries()].filter(([round])=>cupRoundOrder.indexOf(round)<cupRoundOrder.indexOf('Ottavi di finale'));
  if(!groups.size)return <Empty text="Non sono ancora disponibili incontri per costruire il tabellone di questa edizione."/>;
  if(!ottavi.length)return <div className="card p-5"><p className="mb-4 text-sm text-zinc-400">Questa edizione non è arrivata agli ottavi nell’archivio: ecco gli incontri disponibili.</p><div className="grid gap-3 md:grid-cols-2">{[...groups.entries()].map(([round,fixtures])=><section key={round}><h2 className="mb-2 text-sm font-black text-amber-300">{round}</h2><div className="space-y-2">{fixtures.map(fixture)}</div></section>)}</div></div>;
  const leftOttavi=ottavi.slice(0,4),rightOttavi=ottavi.slice(4),leftQuarti=quarti.slice(0,2),rightQuarti=quarti.slice(2),leftSemi=semifinali.slice(0,2),rightSemi=semifinali.slice(2);
  const branch=(title:string,fixtures:Match[],spacing:string)=><section className={`relative ${spacing} after:absolute after:right-[-9px] after:top-1/2 after:h-px after:w-2 after:bg-amber-300/80`}><h2 className="mb-2 text-center text-[10px] font-black uppercase tracking-wider text-amber-200">{title}</h2><div className="space-y-2">{fixtures.map(fixture)}</div></section>;
  return <><p className="mb-4 text-sm text-zinc-400">Tabellone a due rami: ottavi, quarti e semifinali convergono verso la finale centrale. Il Sassuolo è evidenziato in verde.</p><div className="overflow-x-auto rounded-3xl border border-red-400/25 bg-[linear-gradient(135deg,#351018,#16090d_45%,#351018)] p-3 shadow-panel sm:p-4"><div className="grid min-w-[980px] grid-cols-[1.35fr_1fr_.82fr_138px_.82fr_1fr_1.35fr] items-center gap-2 lg:min-w-0 lg:gap-3"><div>{branch('Ottavi',leftOttavi,'')}</div><div>{branch('Quarti',leftQuarti,'py-7')}</div><div>{branch('Semifinali',leftSemi,'py-14')}</div><div className="flex min-h-[318px] flex-col items-center justify-center rounded-2xl border border-amber-300/35 bg-red-950/40 p-3 text-center"><Trophy className="h-14 w-14 text-amber-300 drop-shadow-[0_0_18px_rgba(251,191,36,.35)]"/><div className="mt-2 text-sm font-black tracking-wide text-white">COPPA<br/>ITALIA</div><div className="mt-3 w-full border-t border-amber-300/35 pt-2 text-[10px] font-black uppercase tracking-wider text-amber-200">Finale</div><div className="mt-2 w-full space-y-2">{finale.map(fixture)}</div></div><div>{branch('Semifinali',rightSemi,'py-14')}</div><div>{branch('Quarti',rightQuarti,'py-7')}</div><div>{branch('Ottavi',rightOttavi,'')}</div></div></div>{early.length>0&&<section className="mt-5 card p-4"><h2 className="mb-3 text-sm font-black text-amber-300">Turni precedenti</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{early.map(([round,fixtures])=><div key={round}><h3 className="mb-2 text-xs font-bold text-zinc-400">{round}</h3><div className="space-y-2">{fixtures.map(fixture)}</div></div>)}</div></section>}</>;
};

export default function SeasonDetail(){
  const{season}=useParams();const[params]=useSearchParams();const competition=params.get('competition')??'';const[d,setD]=useState<D|null>(null);const[tab,setTab]=useState<Tab>('overview');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
  const load=()=>api<D>(`/seasons/${encodeURIComponent(season||'')}${competition?`?competition=${encodeURIComponent(competition)}`:''}`).then(setD);
  useEffect(()=>{setD(null);void load()},[season,competition]);
  const sync=async()=>{if(!season)return;setBusy(true);setMessage('');try{const r=await post<any>(`/api-football/season/${encodeURIComponent(season)}`);const result=r.result;setMessage(result.errors?.length?`Sincronizzazione completata con avvisi: ${result.errors.join(' · ')}`:`Sincronizzazione API-Football completata (${result.requests??0} richieste).`);await load();}catch(e){setMessage(String(e))}finally{setBusy(false)}};
  const transferGroups=useMemo(()=>({arrivals:d?.transfers.filter(t=>t.direction==='IN')??[],departures:d?.transfers.filter(t=>t.direction==='OUT')??[]}),[d]);
  if(!d)return <Loading/>;if(!d.season&&!d.matches.length)return <Empty title="Stagione non trovata"/>;const s=d.season;const isCup=/^Coppa Italia$/i.test(s?.competition??competition);const bestCupRound=[...d.matches].map(m=>cupRoundLabel(m.round)).sort((a,b)=>cupRoundOrder.indexOf(b)-cupRoundOrder.indexOf(a))[0]??null;
  if(isCup&&tab==='overview')return <><Breadcrumb items={[{label:'Stagioni',to:'/seasons'},{label:season||'N/D'},{label:s?.competition||'N/D'}]}/><PageTitle title={season||'Stagione'} subtitle="Coppa Italia · statistiche calcolate sulle sole gare del Sassuolo"/><div className="mb-5 flex gap-2 overflow-x-auto pb-1"><button className="btn-primary whitespace-nowrap"><Trophy className="h-4 w-4"/>Panoramica</button><button className="btn-secondary whitespace-nowrap" onClick={()=>setTab('standings')}><Table2 className="h-4 w-4"/>Tabellone</button><button className="btn-secondary whitespace-nowrap" onClick={()=>setTab('squad')}><Users className="h-4 w-4"/>Rosa & statistiche</button><button className="btn-secondary whitespace-nowrap" onClick={()=>setTab('matches')}><CalendarDays className="h-4 w-4"/>Partite</button></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3"><StatCard label="Uscita" value={cupExitLabel(bestCupRound)}/><StatCard label="Partite" value={s?.matches}/><StatCard label="Vittorie" value={s?.wins}/><StatCard label="Pareggi" value={s?.draws}/><StatCard label="Sconfitte" value={s?.losses}/><StatCard label="Gol" value={s?.goals_for==null?null:`${s.goals_for}:${s.goals_against??0}`}/><StatCard label="Capocannoniere" value={d.topScorer?.goals===0?'Nessun marcatore':d.topScorer?`${d.topScorer.name} (${fmt(d.topScorer.goals)})`:'N/D'}/></div></>;
  if(isCup&&tab==='standings')return <><Breadcrumb items={[{label:'Stagioni',to:'/seasons'},{label:season||'N/D'},{label:s?.competition||'N/D'}]}/><PageTitle title={season||'Stagione'} subtitle="Coppa Italia · tabellone a eliminazione diretta"/><div className="mb-5 flex gap-2 overflow-x-auto pb-1"><button className="btn-secondary whitespace-nowrap" onClick={()=>setTab('overview')}><Trophy className="h-4 w-4"/>Panoramica</button><button className="btn-primary whitespace-nowrap"><Table2 className="h-4 w-4"/>Tabellone</button><button className="btn-secondary whitespace-nowrap" onClick={()=>setTab('squad')}><Users className="h-4 w-4"/>Rosa & statistiche</button><button className="btn-secondary whitespace-nowrap" onClick={()=>setTab('matches')}><CalendarDays className="h-4 w-4"/>Partite</button></div><CupBracket matches={d.bracket}/></>;
  const leaderCard=(title:string,p:Leader|null,key:'goals'|'assists')=>{const body=p?<><>{p.photo_url?<img className="h-12 w-12 rounded-full bg-zinc-800 object-cover" src={p.photo_url} alt=""/>:<div className="grid h-12 w-12 place-items-center rounded-full bg-zinc-800 text-xs font-black">{p.name.slice(0,2).toUpperCase()}</div>}</><div><div className="font-bold text-neroverde-400">{p.name}</div><div className="text-sm text-zinc-400">{fmt(p[key])} {key==='goals'?'gol':'assist'}{p.appearances==null?'':` · ${p.appearances} presenze`}</div></div></>:null;return <div className="card p-4"><div className="text-xs uppercase tracking-wider text-zinc-500">{title}</div>{p?(p.id?<Link to={`/players/${p.id}`} className="mt-3 flex items-center gap-3 rounded-xl hover:bg-zinc-800/50">{body}</Link>:<div className="mt-3 flex items-center gap-3">{body}</div>):<div className="mt-3 text-zinc-500">N/D — sincronizza le statistiche giocatori.</div>}</div>};
  return <><Breadcrumb items={[{label:'Stagioni',to:'/seasons'},{label:season||'N/D'},{label:s?.competition||'N/D'}]}/><PageTitle title={season||'Season'} subtitle={`${s?.competition||'Dettaglio stagione'}${s?.api_football_league_id?` · API league #${s.api_football_league_id}`:''}`} action={<button className="btn-primary" disabled={busy} onClick={sync}><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/>Aggiorna questa stagione</button>}/><div className="mb-4 flex flex-wrap items-center gap-2" aria-label="Competizioni della stagione"><span className="text-sm text-zinc-500">Competizioni:</span>{(d.competitions??[]).map(item=><Link key={item.id} to={`/seasons/${encodeURIComponent(season||'')}?competition=${encodeURIComponent(item.competition)}`}><CompetitionBadge competition={item.competition}/></Link>)}</div>{message&&<div className="mb-4 rounded-xl border border-zinc-800 bg-zinc-900 p-3 text-sm text-zinc-300">{message}</div>}
    <div className="mb-5 flex gap-2 overflow-x-auto pb-1">{tabDefs.map(([k,label,Icon])=><button key={k} className={tab===k?'btn-primary whitespace-nowrap':'btn-secondary whitespace-nowrap'} onClick={()=>setTab(k)}><Icon className="h-4 w-4"/>{isCup&&k==='standings'?'Tabellone':label}</button>)}</div>
    {tab==='overview'&&<><div className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8"><StatCard label="Posizione" value={s?.final_position?`#${s.final_position}`:null}/><StatCard label="Partite" value={s?.matches}/><StatCard label="Vittorie" value={s?.wins}/><StatCard label="Pareggi" value={s?.draws}/><StatCard label="Sconfitte" value={s?.losses}/><StatCard label="Gol" value={s?.goals_for==null?null:`${s.goals_for}:${s.goals_against??0}`}/><StatCard label="Punti" value={s?.points}/><StatCard label="Allenatore" value={fmt(s?.manager)}/></div><div className="mb-5 grid gap-4 md:grid-cols-2">{leaderCard('Capocannoniere Sassuolo',d.topScorer,'goals')}{leaderCard('Miglior assistman',d.topAssists,'assists')}</div><div className="grid gap-4 lg:grid-cols-3"><div className="card p-5"><h2 className="font-bold">Casa</h2><div className="mt-2 text-2xl font-black">{fmt(s?.home_record)}</div><p className="mt-1 text-xs text-zinc-500">V-N-P se disponibile.</p></div><div className="card p-5"><h2 className="font-bold">Trasferta</h2><div className="mt-2 text-2xl font-black">{fmt(s?.away_record)}</div><p className="mt-1 text-xs text-zinc-500">V-N-P se disponibile.</p></div><div className="card p-5"><h2 className="font-bold">Dati collegati</h2><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><span className="text-zinc-500">Giocatori</span><b>{d.squad.length}</b><span className="text-zinc-500">Classifica</span><b>{d.standings.length?'Sì':'No'}</b><span className="text-zinc-500">Team stats</span><b>{d.teamStats?'Sì':'No'}</b><span className="text-zinc-500">Trasferimenti</span><b>{d.transfers.length}</b></div></div></div></>}
    {tab==='standings'&&<>{d.standings.length?<div className="table-wrap"><table><thead><tr><th>#</th><th>Squadra</th><th>PG</th><th>V</th><th>N</th><th>P</th><th>GF</th><th>GS</th><th>DR</th><th>Pt</th><th>Forma</th></tr></thead><tbody>{d.standings.map(r=><tr key={r.id} className={/sassuolo/i.test(r.team_name)?'bg-neroverde-500/10':''}><td className="font-black">{fmt(r.rank)}</td><td><div className="flex items-center gap-2">{r.team_logo&&<img src={r.team_logo} className="h-6 w-6 object-contain" alt=""/>}<b>{r.team_name}</b></div></td><td>{fmt(r.played)}</td><td>{fmt(r.wins)}</td><td>{fmt(r.draws)}</td><td>{fmt(r.losses)}</td><td>{fmt(r.goals_for)}</td><td>{fmt(r.goals_against)}</td><td>{fmt(r.goals_diff)}</td><td className="font-black">{fmt(r.points)}</td><td className="font-mono text-xs">{fmt(r.form)}</td></tr>)}</tbody></table></div>:<Empty text="Classifica non ancora sincronizzata. Premi “Aggiorna questa stagione” per provare API-Football."/>}</>}
    {tab==='squad'&&<>{d.squad.length?<div className="table-wrap"><table><thead><tr><th>Giocatore</th><th>Ruolo</th><th>Pres.</th><th>Tit.</th><th>Min.</th><th>Gol</th><th>Assist</th><th>Rating</th><th>Tiri</th><th>Key pass</th><th>Tackle</th></tr></thead><tbody>{d.squad.map(p=><tr key={p.player_id}><td><Link className="flex items-center gap-2 font-bold text-neroverde-400" to={`/players/${p.player_id}`}>{p.player_photo&&<img className="h-8 w-8 rounded-full object-cover" src={p.player_photo} alt=""/>}{p.player_name}</Link></td><td>{fmt(p.position)}</td><td>{fmt(p.appearances)}</td><td>{fmt(p.starts)}</td><td>{fmt(p.minutes)}</td><td>{fmt(p.goals)}</td><td>{fmt(p.assists)}</td><td>{p.rating==null?'N/D':Number(p.rating).toFixed(2)}</td><td>{fmt(p.shots_total)}</td><td>{fmt(p.passes_key)}</td><td>{fmt(p.tackles_total)}</td></tr>)}</tbody></table></div>:<Empty text="Le statistiche giocatori di questa stagione non sono ancora in SQLite o non sono coperte dal piano/API."/>}</>}
    {tab==='team-stats'&&<>{d.teamStats?<><div className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-4"><StatCard label="Gol / partita" value={ratio(d.teamStats.goals_for_avg)}/><StatCard label="Subiti / partita" value={ratio(d.teamStats.goals_against_avg)}/><StatCard label="Clean sheet" value={d.teamStats.clean_sheets}/><StatCard label="Senza segnare" value={d.teamStats.failed_to_score}/></div><div className="grid gap-4 lg:grid-cols-2"><div className="card p-5"><h2 className="mb-4 font-bold">Record partita</h2><div className="grid grid-cols-2 gap-y-3 text-sm"><span className="text-zinc-500">Miglior vittoria casa</span><b>{fmt(d.teamStats.biggest_win_home)}</b><span className="text-zinc-500">Miglior vittoria fuori</span><b>{fmt(d.teamStats.biggest_win_away)}</b><span className="text-zinc-500">Peggior sconfitta casa</span><b>{fmt(d.teamStats.biggest_loss_home)}</b><span className="text-zinc-500">Peggior sconfitta fuori</span><b>{fmt(d.teamStats.biggest_loss_away)}</b><span className="text-zinc-500">Serie vittorie</span><b>{fmt(d.teamStats.longest_win_streak)}</b><span className="text-zinc-500">Serie pareggi</span><b>{fmt(d.teamStats.longest_draw_streak)}</b></div></div><div className="card p-5"><h2 className="mb-4 font-bold">Moduli utilizzati</h2>{d.teamStats.lineups?.length?<div className="space-y-2">{d.teamStats.lineups.slice(0,10).map(x=><div key={x.formation} className="flex justify-between rounded-xl bg-zinc-950 px-3 py-2"><span>{x.formation}</span><b>{x.played}</b></div>)}</div>:<p className="text-sm text-zinc-500">N/D</p>}</div></div></>:<Empty text="Statistiche squadra non ancora sincronizzate per questa stagione."/>}</>}
    {tab==='transfers'&&<div className="grid gap-5 xl:grid-cols-2"><section><h2 className="mb-3 font-bold text-neroverde-400">Arrivi ({transferGroups.arrivals.length})</h2>{transferGroups.arrivals.length?<div className="space-y-2">{transferGroups.arrivals.map(t=><div className="card flex items-center justify-between p-3" key={t.id}><div>{t.player_id?<Link className="font-bold" to={`/players/${t.player_id}`}>{t.player_name}</Link>:<b>{t.player_name}</b>}<div className="text-xs text-zinc-500">da {fmt(t.from_team_name)} · {fmt(t.date)}</div></div><span className="badge">{fmt(t.type)}</span></div>)}</div>:<Empty/>}</section><section><h2 className="mb-3 font-bold text-amber-300">Partenze ({transferGroups.departures.length})</h2>{transferGroups.departures.length?<div className="space-y-2">{transferGroups.departures.map(t=><div className="card flex items-center justify-between p-3" key={t.id}><div>{t.player_id?<Link className="font-bold" to={`/players/${t.player_id}`}>{t.player_name}</Link>:<b>{t.player_name}</b>}<div className="text-xs text-zinc-500">a {fmt(t.to_team_name)} · {fmt(t.date)}</div></div><span className="badge">{fmt(t.type)}</span></div>)}</div>:<Empty/>}</section></div>}
    {tab==='matches'&&<>{d.matches.length?<MatchTable matches={d.matches}/>:<Empty/>}</>}
  </>;
}
