import { useEffect,useMemo,useState } from 'react';
import { Link,useSearchParams } from 'react-router-dom';
import { ArrowDownLeft,ArrowUpRight,ExternalLink,RefreshCw } from 'lucide-react';
import { api,post } from '../services/api';
import { Empty,ErrorState,Loading,PageTitle,Pagination,fmt } from '../components/Ui';
import type { Transfer } from '../types';

type Season={season:string};
type Response={rows:Transfer[];total:number;page:number;pageSize:number};
const civilDate=(value:string)=>{const [year,month,day]=value.slice(0,10).split('-');return `${day}/${month}/${year}`};
export default function Transfers(){
  const[params,setParams]=useSearchParams();const[data,setData]=useState<Response|null>(null);const[seasons,setSeasons]=useState<Season[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const season=params.get('season')??'',session=params.get('session')??'',movement=params.get('movement')??'',page=Math.max(1,Number(params.get('page')||1));
  const setFilter=(key:string,value:string)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);if(key!=='page')next.delete('page');setParams(next,{replace:true})};
  const load=()=>{const query=new URLSearchParams(params);query.set('page',String(page));query.set('pageSize','50');setError('');return api<Response>(`/transfers?${query}`).then(setData).catch(err=>setError(String(err)))};
  useEffect(()=>{void api<Season[]>('/seasons').then(setSeasons).catch(()=>setSeasons([]))},[]);useEffect(()=>{setData(null);void load()},[params.toString()]);
  const update=async()=>{setBusy(true);try{await post('/api-football/transfers');await load()}finally{setBusy(false)}};
  const grouped=useMemo(()=>({arrivals:data?.rows.filter(x=>x.direction==='IN')??[],departures:data?.rows.filter(x=>x.direction==='OUT')??[]}),[data]);
  if(error)return <ErrorState message={error} retry={load}/>;if(!data)return <Loading/>;
  const money=(t:Transfer)=>t.fee_amount!=null&&t.fee_currency?new Intl.NumberFormat('it-IT',{style:'currency',currency:t.fee_currency,maximumFractionDigits:0}).format(t.fee_amount):t.fee_display??'N/D';
  const table=(rows:Transfer[],direction:'IN'|'OUT')=>rows.length?<div className="table-wrap max-w-full"><table><thead><tr><th>Data</th><th>Giocatore</th><th>{direction==='IN'?'Da':'A'}</th><th>Movimento</th><th>Sessione</th><th>Costo</th><th>Fonte</th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td>{t.date?civilDate(t.date):'N/D'}</td><td>{t.player_id?<Link className="font-bold text-neroverde-400 hover:underline" to={`/players/${t.player_id}`}>{t.player_name}</Link>:<><b>{t.player_name}</b><span className="ml-2 badge">identità da riconciliare</span></>}</td><td>{fmt(direction==='IN'?t.from_team_name:t.to_team_name)}</td><td><span className="badge">{fmt(t.movement_type??t.type)}</span></td><td>{t.session==='SUMMER'?'Estiva':t.session==='WINTER'?'Invernale':'N/D'}</td><td>{money(t)}</td><td>{t.source_url?<a aria-label={`Fonte trasferimento ${t.player_name}`} href={t.source_url} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4 text-neroverde-300"/></a>:'N/D'}</td></tr>)}</tbody></table></div>:<Empty text="Nessun movimento rosa per questi filtri e questa pagina."/>;
  return <><PageTitle title="Trasferimenti" subtitle="Acquisti, cessioni, prestiti, rientri e svincoli riconciliati con l’identità del giocatore. I costi mancanti restano N/D." action={<div className="flex flex-wrap gap-2"><select aria-label="Stagione" className="input w-40" value={season} onChange={e=>setFilter('season',e.target.value)}><option value="">Tutte le stagioni</option>{[...new Set(seasons.map(s=>s.season))].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Sessione" className="input w-40" value={session} onChange={e=>setFilter('session',e.target.value)}><option value="">Tutte le sessioni</option><option value="SUMMER">Estiva</option><option value="WINTER">Invernale</option></select><select aria-label="Movimento" className="input w-40" value={movement} onChange={e=>setFilter('movement',e.target.value)}><option value="">Tutti i movimenti</option><option value="TRANSFER">Acquisto/cessione</option><option value="LOAN">Prestito</option><option value="RETURN">Rientro</option><option value="FREE">Svincolato</option><option value="RELEASE">Rilascio</option></select><button className="btn-secondary" disabled={busy} onClick={update}><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/>Aggiorna</button></div>}/><div className="grid min-w-0 gap-5 xl:grid-cols-2"><section className="min-w-0"><h2 className="mb-3 flex items-center gap-2 text-lg font-bold"><ArrowDownLeft className="h-5 w-5 text-neroverde-400"/>Arrivi <span className="text-sm text-zinc-400">({grouped.arrivals.length} nella pagina)</span></h2>{table(grouped.arrivals,'IN')}</section><section className="min-w-0"><h2 className="mb-3 flex items-center gap-2 text-lg font-bold"><ArrowUpRight className="h-5 w-5 text-amber-300"/>Partenze <span className="text-sm text-zinc-400">({grouped.departures.length} nella pagina)</span></h2>{table(grouped.departures,'OUT')}</section></div><Pagination page={data.page} pageSize={data.pageSize} total={data.total} onPage={value=>setFilter('page',String(value))}/></>;
}
