import { useEffect, useRef, useState, type ReactNode } from 'react';
import { CalendarDays, Clock3, Search, Shield, SlidersHorizontal, Users, X } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';
import { api } from '../services/api';
import type { Season } from '../types';

type Results={players:{id:number;name:string;position:string|null;matched_alias?:string|null}[];matches:{id:number;date:string;season:string;competition:string;home_team:string;away_team:string;home_score:number|null;away_score:number|null}[];seasons:{id:number;season:string;competition:string}[];opponents:{name:string;matches:number}[]};
const RECENT_KEY='sassuolo_recent_searches';
const Group=({title,children}:{title:string;children:ReactNode})=><section className="mb-2"><div className="px-2 py-1 text-[10px] font-black uppercase tracking-wider text-zinc-400">{title}</div>{children}</section>;
const loadRecent=()=>{try{return JSON.parse(localStorage.getItem(RECENT_KEY)??'[]') as string[]}catch{return []}};

export default function GlobalSearch(){
  const[q,setQ]=useState('');const[r,setR]=useState<Results|null>(null);const[recent,setRecent]=useState<string[]>(loadRecent);const[focused,setFocused]=useState(false);const[filtersOpen,setFiltersOpen]=useState(false);const[competition,setCompetition]=useState('');const[from,setFrom]=useState('');const[to,setTo]=useState('');const[seasons,setSeasons]=useState<Season[]>([]);const input=useRef<HTMLInputElement>(null);const location=useLocation();
  useEffect(()=>{void api<Season[]>('/seasons').then(setSeasons)},[]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'||event.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes((event.target as HTMLElement).tagName)){event.preventDefault();input.current?.focus()}if(event.key==='Escape'){setR(null);input.current?.blur()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
  useEffect(()=>{const timer=setTimeout(()=>{if(q.trim().length<2){setR(null);return}const params=new URLSearchParams({q:q.trim()});if(competition)params.set('competition',competition);if(from)params.set('from',from);if(to)params.set('to',to);void api<Results>(`/search?${params}`).then(setR).catch(()=>setR(null))},220);return()=>clearTimeout(timer)},[q,competition,from,to]);
  const remember=()=>{const term=q.trim();if(!term)return;const next=[term,...recent.filter(item=>item.toLocaleLowerCase()!==term.toLocaleLowerCase())].slice(0,5);setRecent(next);localStorage.setItem(RECENT_KEY,JSON.stringify(next))};
  const close=()=>{remember();setR(null);setQ('')};const has=r&&Object.values(r).some(items=>items.length);const activeFilters=Boolean(competition||from||to);const context=new URLSearchParams({from:location.pathname+location.search,q:q.trim()});if(competition)context.set('competition',competition);if(from)context.set('periodFrom',from);if(to)context.set('periodTo',to);
  const competitions=[...new Set(seasons.map(item=>item.competition))].sort();
  return <div className="relative w-full max-w-xl"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-400"/><input ref={input} aria-label="Ricerca globale" className="input !pl-11 !pr-20" value={q} onFocus={()=>{setFocused(true);if(q.length<2&&recent.length)setR(null)}} onBlur={()=>setTimeout(()=>setFocused(false),150)} onChange={event=>setQ(event.target.value)} placeholder="Cerca anche con refusi o alias…"/><button type="button" aria-label="Filtri ricerca" aria-expanded={filtersOpen} className={`absolute right-10 top-1/2 -translate-y-1/2 rounded-lg p-1.5 ${activeFilters?'text-neroverde-300':'text-zinc-400'} hover:bg-zinc-800`} onClick={()=>setFiltersOpen(value=>!value)}><SlidersHorizontal className="h-4 w-4"/></button><kbd className="pointer-events-none absolute right-2 top-1/2 -translate-y-1/2 text-[10px] text-zinc-400">Ctrl K</kbd></div>
    {filtersOpen&&<div className="absolute right-0 z-[60] mt-2 grid w-full gap-2 rounded-xl border border-zinc-700 bg-zinc-950 p-3 shadow-2xl sm:grid-cols-3"><select aria-label="Competizione ricerca" className="input" value={competition} onChange={event=>setCompetition(event.target.value)}><option value="">Ogni competizione</option>{competitions.map(item=><option key={item}>{item}</option>)}</select><input aria-label="Anno iniziale" className="input" inputMode="numeric" value={from} onChange={event=>setFrom(event.target.value.replace(/\D/g,'').slice(0,4))} placeholder="Dal 2008"/><div className="flex gap-1"><input aria-label="Anno finale" className="input" inputMode="numeric" value={to} onChange={event=>setTo(event.target.value.replace(/\D/g,'').slice(0,4))} placeholder="Al 2026"/>{activeFilters&&<button type="button" aria-label="Azzera filtri ricerca" className="rounded-lg p-2 text-zinc-400 hover:bg-zinc-800" onClick={()=>{setCompetition('');setFrom('');setTo('')}}><X className="h-4 w-4"/></button>}</div></div>}
    {!q&&recent.length>0&&focused&&<div className="absolute right-0 z-50 mt-2 w-full rounded-xl border border-zinc-700 bg-zinc-950 p-2 shadow-2xl"><Group title="Ricerche recenti">{recent.map(term=><button type="button" className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-sm hover:bg-zinc-900" onClick={()=>setQ(term)} key={term}><Clock3 className="h-3.5 w-3.5 text-zinc-400"/>{term}</button>)}</Group></div>}
    {r&&<div className="absolute right-0 z-50 mt-2 max-h-[70vh] w-full overflow-auto rounded-xl border border-zinc-700 bg-zinc-950 p-2 shadow-2xl">{!has&&<p className="p-3 text-sm text-zinc-400">Nessun risultato per “{q}”. Prova ad ampliare periodo o competizione.</p>}<Group title="Giocatori">{r.players.map(item=><Link onClick={close} className="flex items-center gap-2 rounded-lg px-2 py-2 text-sm hover:bg-zinc-900" to={`/players/${item.id}?${context}`} key={`p${item.id}`}><Users className="h-3.5 w-3.5 text-neroverde-400"/><span>{item.name}{item.matched_alias&&item.matched_alias!==item.name&&<small className="ml-1 text-zinc-400">alias: {item.matched_alias}</small>}</span><span className="ml-auto text-zinc-400">{item.position||'N/D'}</span></Link>)}</Group><Group title="Stagioni">{r.seasons.map(item=><Link onClick={close} className="flex items-center gap-2 rounded-lg px-2 py-2 text-sm hover:bg-zinc-900" to={`/seasons/${encodeURIComponent(item.season)}?competition=${encodeURIComponent(item.competition)}&${context}`} key={`s${item.id}`}><CalendarDays className="h-3.5 w-3.5 text-neroverde-400"/>{item.season} · {item.competition}</Link>)}</Group><Group title="Partite">{r.matches.map(item=><Link onClick={close} className="flex items-center gap-2 rounded-lg px-2 py-2 text-sm hover:bg-zinc-900" to={`/matches/${item.id}?${context}`} key={`m${item.id}`}><Shield className="h-3.5 w-3.5 text-neroverde-400"/><span className="min-w-0 truncate">{item.home_team} {item.home_score??'N/D'}–{item.away_score??'N/D'} {item.away_team}</span><span className="ml-auto shrink-0 text-xs text-zinc-400">{item.season}</span></Link>)}</Group><Group title="Avversari">{r.opponents.map(item=><Link onClick={close} className="block rounded-lg px-2 py-2 text-sm hover:bg-zinc-900" to={`/h2h?opponent=${encodeURIComponent(item.name)}&${context}`} key={item.name}>{item.name}<span className="ml-2 text-xs text-zinc-400">{item.matches} gare</span></Link>)}</Group></div>}
  </div>;
}
