import { useEffect,useMemo } from 'react';
import type React from 'react';
import { createPortal } from 'react-dom';
import { ArrowLeft,ArrowRight,CalendarDays,Clapperboard,Heart,Landmark,Shield,Star,Users,X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useExperience } from '../context/ExperienceContext';
import { useModalA11y } from '../hooks/useModalA11y';
import { buildMuseumRooms,calculateMuseumStats,emotionLabels,experienceLabels,type MuseumMemory,type MuseumProfile,type MuseumRoom } from '../services/personalMuseum';

const roomIcons={welcome:Landmark,timeline:CalendarDays,matches:Clapperboard,heroes:Users,seasons:Shield,constellation:Star,finale:Heart};
const points=[[50,10],[78,22],[90,48],[75,78],[48,90],[20,76],[10,46],[24,20],[50,48],[62,62],[38,64],[64,36]];
const dateLabel=(value:string|null|undefined)=>value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleDateString('it-IT',{day:'numeric',month:'short',year:'numeric'}):null;

export default function MuseumTour({memories,profile,index,onIndex,onClose}:{memories:MuseumMemory[];profile:MuseumProfile;index:number;onIndex:(index:number)=>void;onClose:()=>void}){
  const {reducedMotion}=useExperience(),rooms=useMemo(()=>buildMuseumRooms(memories),[memories]),room=rooms[Math.min(index,rooms.length-1)],stats=useMemo(()=>calculateMuseumStats(memories),[memories]);
  const dialogRef=useModalA11y(onClose,true),previous=()=>onIndex(Math.max(0,index-1)),next=()=>onIndex(Math.min(rooms.length-1,index+1));
  useEffect(()=>{const value=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=value};},[]);
  const Icon=roomIcons[room.id];
  return createPortal(<div className={`museum-tour ${reducedMotion?'museum-no-motion':''}`}><div className="museum-tour-orbit museum-tour-orbit-one" aria-hidden="true"/><div className="museum-tour-orbit museum-tour-orbit-two" aria-hidden="true"/><div className="museum-tour-grain" aria-hidden="true"/><div ref={dialogRef} className="relative z-10 flex h-full flex-col" role="dialog" aria-modal="true" aria-labelledby="museum-room-title" tabIndex={-1} onKeyDown={event=>{if(event.key==='ArrowLeft'){event.preventDefault();previous();}if(event.key==='ArrowRight'){event.preventDefault();next();}}}>
    <header className="museum-tour-header"><div className="flex min-w-0 items-center gap-3"><div className="museum-mark"><Landmark aria-hidden="true" className="h-5 w-5"/></div><div className="min-w-0"><div className="truncate text-xs font-black uppercase tracking-[.18em] text-emerald-200">Il mio Museo Neroverde</div><div className="text-[10px] font-semibold uppercase tracking-widest text-zinc-500">Esperienza privata · sala {index+1} di {rooms.length}</div></div></div><button className="museum-tour-close" onClick={onClose} aria-label="Esci dal museo"><X aria-hidden="true" className="h-5 w-5"/><span className="hidden sm:inline">Esci</span></button></header>
    <div className="museum-progress" aria-hidden="true"><span style={{width:`${((index+1)/rooms.length)*100}%`}}/></div>
    <main className="museum-room" key={room.id}><div className="museum-room-heading"><div className="museum-room-icon" aria-hidden="true"><Icon className="h-5 w-5"/></div><div><div className="text-[10px] font-black uppercase tracking-[.24em] text-amber-300">{room.eyebrow}</div><h2 id="museum-room-title" className="museum-room-title">{room.title}</h2></div></div><Room room={room} stats={stats} profile={profile}/></main>
    <footer className="museum-tour-footer"><button className="museum-tour-nav" disabled={index===0} onClick={previous}><ArrowLeft aria-hidden="true" className="h-4 w-4"/>Sala precedente</button><nav aria-label="Sale del museo" className="museum-dots">{rooms.map((item,roomIndex)=><button key={item.id} aria-label={`Vai a ${item.title}`} aria-current={roomIndex===index?'step':undefined} className={roomIndex===index?'is-active':''} onClick={()=>onIndex(roomIndex)}/>)}</nav>{index<rooms.length-1?<button className="museum-tour-nav museum-tour-nav-next" onClick={next}>Sala successiva<ArrowRight aria-hidden="true" className="h-4 w-4"/></button>:<button className="museum-tour-nav museum-tour-nav-next" onClick={onClose}>Torna all’archivio<ArrowRight aria-hidden="true" className="h-4 w-4"/></button>}</footer>
  </div></div>,document.body);
}

function Room({room,stats,profile}:{room:MuseumRoom;stats:ReturnType<typeof calculateMuseumStats>;profile:MuseumProfile}){
  if(room.id==='welcome')return <div className="museum-welcome"><p className="museum-lead">Non è una classifica. È il modo in cui <span>tu</span> hai vissuto il Sassuolo.</p>{stats.total?<div className="museum-stats"><MuseumStat value={stats.total} label="ricordi"/><MuseumStat value={stats.livedSeasons} label="stagioni vissute"/><MuseumStat value={stats.stadium} label="volte allo stadio"/><MuseumStat value={stats.topEmotion?emotionLabels[stats.topEmotion]:'—'} label="emozione dominante"/></div>:<p className="museum-empty-copy">Il primo ricordo accenderà le sale. Parti da una partita, un giocatore o una stagione dell’archivio.</p>}<div className="museum-private-seal"><Shield aria-hidden="true" className="h-4 w-4"/>Solo su questo dispositivo</div></div>;
  if(room.id==='timeline')return <div className="museum-timeline">{room.memories.slice(0,16).map((memory,index)=><article className="museum-timeline-item" key={memory.key}><div className="museum-timeline-pin" aria-hidden="true">{index+1}</div><div><time className="text-[10px] font-black uppercase tracking-wider text-amber-300">{dateLabel(memory.date)??memory.season??'Senza data'}</time><h3 className="mt-1 text-lg font-black text-white">{memory.label}</h3><p className="mt-1 text-xs text-zinc-400">{experienceLabels[memory.experience]} · {emotionLabels[memory.emotion]} · intensità {memory.intensity}/5</p>{(memory.favoriteMoment||memory.note)&&<p className="mt-3 max-w-xl text-sm italic leading-6 text-zinc-200">“{memory.favoriteMoment||memory.note}”</p>}</div></article>)}</div>;
  if(room.id==='matches')return <CardRoom memories={room.memories} kind="match"/>;
  if(room.id==='heroes')return <CardRoom memories={room.memories} kind="player"/>;
  if(room.id==='seasons')return <CardRoom memories={room.memories} kind="season"/>;
  if(room.id==='constellation')return <Constellation memories={room.memories}/>;
  return <div className="museum-finale"><div aria-hidden="true" className="museum-finale-heart"><Heart className="h-10 w-10"/></div><p className="museum-lead">{profile.dedication||'Ogni partita lascia qualcosa. Il resto lo scrive il prossimo ricordo.'}</p>{profile.supporterSince&&<p className="mt-4 text-sm font-bold uppercase tracking-[.2em] text-emerald-200">Neroverde dal {profile.supporterSince}</p>}{stats.firstMemory&&<p className="mt-8 text-sm text-zinc-400">Il primo frammento della tua linea del tempo: <b className="text-white">{stats.firstMemory.label}</b>.</p>}</div>;
}

function MuseumStat({value,label}:{value:string|number;label:string}){return <div><div className="text-2xl font-black text-white md:text-4xl">{value}</div><div className="mt-1 text-[10px] font-black uppercase tracking-[.16em] text-zinc-500">{label}</div></div>}

function CardRoom({memories,kind}:{memories:MuseumMemory[];kind:'match'|'player'|'season'}){return <div className="museum-card-grid">{memories.slice(0,12).map((memory,index)=><article className="museum-exhibit" key={memory.key} style={{'--museum-delay':`${Math.min(index,8)*55}ms`} as React.CSSProperties}><div className="museum-exhibit-top"><span>{memory.season??dateLabel(memory.date)??(kind==='player'?'Eroe':'Archivio')}</span><span aria-label={`Intensità ${memory.intensity} su 5`}>{'✦'.repeat(memory.intensity)}</span></div><h3>{memory.label}</h3><div className="museum-exhibit-meta">{emotionLabels[memory.emotion]} · {experienceLabels[memory.experience]}</div>{(memory.favoriteMoment||memory.note)&&<p>“{memory.favoriteMoment||memory.note}”</p>}<div className="mt-auto pt-5">{kind==='match'?<Link className="museum-exhibit-link" to={`${memory.url}?cinema=start`}><Clapperboard aria-hidden="true" className="h-4 w-4"/>Rivivi nel Match Cinema</Link>:<Link className="museum-exhibit-link" to={memory.url}>Apri nell’archivio<ArrowRight aria-hidden="true" className="h-4 w-4"/></Link>}</div></article>)}</div>}

function Constellation({memories}:{memories:MuseumMemory[]}){const visible=memories.slice(0,12),connections:React.ReactNode[]=[];for(let a=0;a<visible.length;a++)for(let b=a+1;b<visible.length;b++)if(visible[a].season&&visible[a].season===visible[b].season)connections.push(<line key={`${a}-${b}`} x1={points[a][0]} y1={points[a][1]} x2={points[b][0]} y2={points[b][1]}/>);return <div className="museum-constellation-layout"><div className="museum-constellation" aria-hidden="true"><svg viewBox="0 0 100 100" role="presentation"><g className="museum-constellation-lines">{connections}</g>{visible.map((memory,index)=><g key={memory.key} className="museum-star"><circle cx={points[index][0]} cy={points[index][1]} r={1.2+memory.intensity*.18}/><circle className="museum-star-halo" cx={points[index][0]} cy={points[index][1]} r={3+memory.intensity*.4}/></g>)}</svg></div><div><p className="max-w-lg text-base leading-7 text-zinc-300">I ricordi della stessa stagione si cercano e si collegano. Partite, eroi e annate diventano una sola storia: la tua.</p><ul className="mt-5 grid gap-2 sm:grid-cols-2">{visible.map(memory=><li key={memory.key} className="flex items-center gap-2 text-sm font-semibold text-zinc-200"><Star aria-hidden="true" className="h-3.5 w-3.5 text-amber-300"/><span className="truncate">{memory.label}</span></li>)}</ul></div></div>}
