import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const target=path.resolve('data/reconciliation/candidates/player-season-2008-09-reconciled');
const statsPath=path.join(target,'statscrew.csv');
const archiveUrl='http://calcio-seriea.net/presenze/2008/3079/';
const goalsUrl='http://calcio-seriea.net/gol_segnati/2008/3079/';
const worldUrl='https://www.worldfootball.net/teams/te13744/sassuolo-calcio/statistics-matches/co113/italy-serie-b/se3373/2008-2009/';
const verified='2026-08-10';

function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);const parse=(line:string)=>{const out:string[]=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){out.push(value);value='';}else value+=c;}out.push(value);return out;};const headers=parse(lines[0]);return lines.slice(1).map(line=>Object.fromEntries(parse(line).map((value,index)=>[headers[index],value])));}
const cell=(value:unknown)=>{const text=value==null?'':String(value);return /[",\r\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text;};
const csv=(headers:string[],rows:Record<string,unknown>[])=>[headers.join(','),...rows.map(row=>headers.map(h=>cell(row[h])).join(','))].join('\n')+'\n';
const stats=parseCsv(fs.readFileSync(statsPath,'utf8'));const byStats=new Map(stats.map(r=>[r.player_name,r]));

// Tot, substituted out, substituted in, bench, goals, yellow, dismissals.
const archive=[
 ['Walter Bressan','G',41,0,0,0,0,2,0],['Emiliano Salvetti','M',39,13,4,2,6,1,0],['Francesco Magnanelli','M',37,6,1,0,0,9,0],
 ['Alessandro Noselli','F',37,18,4,1,16,3,0],['Riccardo Zampagna','F',36,8,1,0,11,9,1],['Gaetano Masucci','F',35,17,12,1,3,5,0],
 ['Filippo Pensalfini','M',32,7,12,1,4,8,1],['Andrea Poli','M',32,11,10,4,5,5,0],['Nicola Donazzan','D',31,2,0,1,0,8,0],
 ['Angelo Rea','D',31,4,0,0,2,10,0],['Fabrizio Anselmi','D',31,2,3,8,0,10,0],['Massimiliano Fusani','M',29,6,13,11,0,4,0],
 ['Horacio Erpen','F',29,12,14,9,3,6,0],['Marco Andreolli','D',28,1,0,2,1,4,1],['Stefano Pagani','M',26,10,14,5,2,0,0],
 ['Marco Piccioni','D',23,2,0,1,0,7,0],['Nicolò Consolini','D',18,2,4,10,0,1,0],['Daniele Martinetti','F',13,3,8,2,3,2,0],
 ['Attila Filkor','M',10,0,10,12,0,1,0],['Alessandro Bastrini','D',9,0,2,9,0,0,0],['Francesco Della Rocca','M',7,1,6,18,0,0,0],
 ['Andy Selva','F',6,0,6,6,0,1,0],['Sebastiano Girelli','D',5,1,0,12,0,1,1],['William Jidayi','M',2,0,2,6,0,0,0],['Alberto Pomini','G',1,0,0,24,0,0,0],
] as const;

const archiveHeaders=['player_name','season','competition','appearances','starts','substitutes_in','substitutes_out','bench_appearances','goals','yellow_cards','red_cards_combined','position','source_provider','source_url','last_verified_at'];
const archiveRows=archive.map(([player_name,position,appearances,substitutes_out,substitutes_in,bench_appearances,goals,yellow_cards,red_cards_combined])=>({player_name,season:'2008/09',competition:'Serie B',appearances,starts:appearances-substitutes_in,substitutes_in,substitutes_out,bench_appearances,goals,yellow_cards,red_cards_combined,position,source_provider:'calcio-seriea.net',source_url:archiveUrl,last_verified_at:verified}));
const dataHeaders=['player_name','season','competition','appearances','starts','minutes','goals','assists','yellow_cards','yellow_red_cards','red_cards','position','source_provider','source_url','last_verified_at'];
const dataRows=archiveRows.map(r=>({player_name:r.player_name,season:r.season,competition:r.competition,appearances:r.appearances,starts:r.starts,minutes:'',goals:r.goals,assists:'',yellow_cards:r.yellow_cards,yellow_red_cards:'',red_cards:r.red_cards_combined,position:r.position,source_provider:'calcio-seriea.net',source_url:archiveUrl,last_verified_at:verified}));
const discrepancies:Record<string,unknown>[]=[];const fields=['appearances','starts','goals','yellow_cards','red_cards','position'] as const;
for(const row of dataRows){const old=byStats.get(row.player_name);for(const field of fields){const a=old?.[field]??'',b=String(row[field]??'');if(a!==b)discrepancies.push({player_name:row.player_name,field,statscrew_value:a,archive_value:b,selected_value:b,resolution:'Complete season appearance archive selected over incomplete aggregate table.',status:'resolved',evidence_url:archiveUrl,note:'Archive totals reconcile 42 matches: 588 appearances, 126 substitute entries, 462 starts.'});}}
discrepancies.push({player_name:'TEAM',field:'player_goals',statscrew_value:55,archive_value:56,selected_value:56,resolution:'Archive lists all 56 player goals; Pensalfini has four rather than three.',status:'resolved',evidence_url:goalsUrl,note:'56 player goals plus one opponent own goal equals 57 team goals.'});
discrepancies.push({player_name:'Patrice Feussi',field:'opponent_own_goal',statscrew_value:'',archive_value:1,selected_value:1,resolution:'Specialist historical goal archive selected; event recorded separately from Sassuolo player goals.',status:'resolved',evidence_url:goalsUrl,note:"Sassuolo-Pisa 3-1, 2008-09-16, 81'."});
fs.writeFileSync(path.join(target,'archive-presences.csv'),csv(archiveHeaders,archiveRows),'utf8');fs.writeFileSync(path.join(target,'data.csv'),csv(dataHeaders,dataRows),'utf8');
const discrepancyHeaders=['player_name','field','statscrew_value','archive_value','selected_value','resolution','status','evidence_url','note'];fs.writeFileSync(path.join(target,'discrepancies.csv'),csv(discrepancyHeaders,discrepancies),'utf8');
const goalHeaders=['date','season','competition','home_team','away_team','home_score','away_score','scoring_team','player_name','player_team','event_type','minute','source_provider','source_url','confirmation_url','last_verified_at','note'];
const goals=[{date:'2008-09-16',season:'2008/09',competition:'Serie B',home_team:'Sassuolo',away_team:'Pisa',home_score:3,away_score:1,scoring_team:'Sassuolo',player_name:'Patrice Feussi',player_team:'Pisa',event_type:'opponent_own_goal',minute:"81'",source_provider:'calcio-seriea.net',source_url:goalsUrl,confirmation_url:'https://www.transfermarkt.it/us-sassuolo_ac-pisa-1909/index/spielbericht/924235',last_verified_at:verified,note:'Historical goal archive classifies the third Sassuolo goal as an own goal. Kept outside Sassuolo player goal totals.'}];
fs.writeFileSync(path.join(target,'goal-resolution.csv'),csv(goalHeaders,goals),'utf8');
const hash=(file:string)=>crypto.createHash('sha256').update(fs.readFileSync(path.join(target,file))).digest('hex');const dataHash=hash('data.csv');
const sums={appearances:dataRows.reduce((n,r)=>n+Number(r.appearances),0),starts:dataRows.reduce((n,r)=>n+Number(r.starts),0),goals:dataRows.reduce((n,r)=>n+Number(r.goals),0),yellow:dataRows.reduce((n,r)=>n+Number(r.yellow_cards),0),red:dataRows.reduce((n,r)=>n+Number(r.red_cards),0)};
const manifest={area:'player_seasons',season:'2008/09',competition:'Serie B',source_provider:'calcio-seriea.net',source_url:archiveUrl,verified_at:verified,file:'data.csv',sha256:dataHash,records_total:dataRows.length,records_discarded:0,discard_reasons:[],fields_covered:dataHeaders,validation:{status:'reconciled',checks:[{name:'complete_player_extract',status:'passed',note:'25 players with at least one Serie B appearance.'},{name:'appearances_and_starts',status:'passed',note:`${sums.appearances} appearances - 126 substitute entries = ${sums.starts} starts = 42 × 11.`},{name:'goal_reconciliation',status:'passed',note:`${sums.goals} player goals + 1 opponent own goal = 57 team goals.`},{name:'goalkeeper_reconciliation',status:'passed',note:'Walter Bressan 41 starts + Alberto Pomini 1 start = 42 goalkeeper starts.'},{name:'field_by_field_comparison',status:'passed',note:`${discrepancies.length} source differences documented and resolved.`},{name:'nullable_unverified_fields',status:'passed',note:'Minutes, assists, and yellow-red split left NULL because the complete archive does not verify them.'},{name:'identities_reviewed',status:'passed',note:'All 25 names match existing canonical player identities.'}],unresolved_conflicts:[]},field_source_policy:{calcio_seriea_net:['appearances','starts','goals','yellow_cards','red_cards','position'],left_null:['minutes','assists','yellow_red_cards']},related_files:{archive_presences_csv_sha256:hash('archive-presences.csv'),statscrew_csv_sha256:hash('statscrew.csv'),discrepancies_csv_sha256:hash('discrepancies.csv'),goal_resolution_csv_sha256:hash('goal-resolution.csv')},notes:[`WorldFootball (${worldUrl}) and StatsCrew were retained as comparison sources but not selected because their totals cover only 440 starts and 55 player goals.`,'Regular-season Serie B only; Coppa Italia excluded.','Unknown or source-conflicted fields remain NULL rather than inferred.']};
fs.writeFileSync(path.join(target,'manifest.json'),JSON.stringify(manifest,null,2)+'\n','utf8');
fs.writeFileSync(path.join(target,'SOURCES.md'),`# PlayerSeason Serie B 2008/09 — riconciliato\n\nFonte primaria: calcio-seriea.net (${archiveUrl}), tabella completa delle presenze Sassuolo nella Serie B 2008/09. Totali pubblicati e ricalcolati: 588 presenze, 126 subentri, 462 titolarità, 56 gol giocatore, 97 ammonizioni e 4 espulsioni.\n\nL'elenco gol (${goalsUrl}) documenta 56 gol dei calciatori e un'autorete di Patrice Feussi in Sassuolo–Pisa 3-1 del 16 settembre 2008: totale squadra 57. Filippo Pensalfini risulta a quattro gol.\n\nPortieri: Walter Bressan 41 presenze senza subentri; Alberto Pomini 1 presenza senza subentri. La scheda di Pomini indica l'esordio in Serie B in Sassuolo–Salernitana 1-0 del 24 gennaio 2009.\n\nWorldFootball e StatsCrew sono conservati come confronto, ma non prevalgono perché fermano le titolarità a 440 e i gol giocatore a 55. Minuti, assist e separazione giallo-rosso restano NULL perché non verificabili dalla fonte completa. Coppa Italia esclusa.\n`,'utf8');
console.log(JSON.stringify({target,records:dataRows.length,discrepancies:discrepancies.length,...sums,sha256:dataHash},null,2));
