import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const target=path.resolve('data/reconciliation/candidates/player-season-2009-10-reconciled');
const statsPath=path.join(target,'statscrew.csv');
const worldUrl='https://www.worldfootball.net/teams/te13744/sassuolo-calcio/statistics-matches/co113/italy-serie-b/se1558/2009-2010/';
const statsUrl='https://www.statscrew.com/worldfootball/stats/t-SASCA963/y-2009';
const ownGoalUrl='https://web.archive.org/web/20140117003534/http://www.legaserieb.it:80/it/serie-b/campionato/matchreport/-/match-report/Sassuolo-Salernitana/24231';
const verified='2026-08-10';

function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);const parse=(line:string)=>{const out:string[]=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){out.push(value);value='';}else value+=c;}out.push(value);return out;};const headers=parse(lines[0]);return lines.slice(1).map(line=>Object.fromEntries(parse(line).map((value,index)=>[headers[index],value])));}
const cell=(value:unknown)=>{const text=value==null?'':String(value);return /[",\r\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text;};
const csv=(headers:string[],rows:Record<string,unknown>[])=>[headers.join(','),...rows.map(row=>headers.map(h=>cell(row[h])).join(','))].join('\n')+'\n';

// Complete WorldFootball table after explicitly selecting Serie B 2009/2010.
const world=[
 ['Mauro Minelli','D',40,3595,40,0,0,0,4,1,0],['Walter Bressan','G',37,3330,37,0,0,1,2,0,0],['Luigi Riccio','M',38,3327,38,0,7,4,4,0,0],
 ['Francesco Magnanelli','M',38,3247,37,1,4,0,7,0,0],['Alessandro Noselli','F',39,3015,35,4,17,18,2,0,0],['Tiziano Polenghi','D',32,2711,31,1,6,2,9,1,0],
 ['Jonathan Rossini','D',31,2613,29,2,1,2,6,0,1],['Gianluigi Bianco','D',29,2119,22,7,5,1,3,1,0],['Daniele Martinetti','F',32,1991,24,8,14,10,4,0,0],
 ['Emiliano Salvetti','M',28,1870,21,7,11,3,2,0,0],['Daniele Quadrini','F',35,1844,21,14,16,5,5,0,0],['Massimiliano Fusani','M',29,1773,18,11,3,1,3,1,0],
 ['Gaetano Masucci','F',26,1636,17,9,10,4,4,0,0],['Marco Gorzegno','M',26,1630,19,7,7,1,4,1,1],['Marco Piccioni','D',22,1619,17,5,0,0,2,1,0],
 ['Riccardo Zampagna','F',25,1267,12,13,5,5,2,0,0],['Carl Valeri','M',15,1049,13,2,5,0,4,0,0],['Nicolò Consolini','D',18,931,10,8,3,0,2,0,0],
 ['Nicola Donazzan','D',10,706,8,2,2,1,4,0,0],['Mario Titone','M',18,459,4,14,4,1,1,1,0],['Alberto Pomini','G',5,450,5,0,0,0,0,0,0],
 ['Attila Filkor','M',5,199,2,3,1,0,0,0,0],['Angelo Rea','D',2,107,1,1,0,0,0,0,0],['Giorgio Schiavini','M',1,70,1,0,1,0,0,0,0],
 ['Mariano Romano','M',1,37,0,1,0,0,0,0,0],['Milan Jirásek','M',1,21,0,1,0,0,0,0,0],['Diego Falcinelli','F',1,9,0,1,0,0,0,0,0],
] as const;

const stats=parseCsv(fs.readFileSync(statsPath,'utf8'));const byName=new Map(stats.map(row=>[row.player_name,row]));
const canonicalName=(name:string)=>name==='Milan Jirásek'?'Milan Jirasek':name;
const worldHeaders=['player_name','season','competition','appearances','minutes','starts','substitutes_in','substitutes_out','goals','yellow_cards','yellow_red_cards','red_cards','position','source_provider','source_url','last_verified_at'];
const worldRows=world.map(([name,position,appearances,minutes,starts,substitutes_in,substitutes_out,goals,yellow_cards,yellow_red_cards,red_cards])=>({player_name:name,season:'2009/10',competition:'Serie B',appearances,minutes,starts,substitutes_in,substitutes_out,goals,yellow_cards,yellow_red_cards,red_cards,position,source_provider:'WorldFootball.net',source_url:worldUrl,last_verified_at:verified}));
const missingStats=worldRows.filter(row=>!byName.has(row.player_name));if(missingStats.length)throw new Error(`StatsCrew identities missing: ${missingStats.map(r=>r.player_name).join(', ')}`);
const dataHeaders=['player_name','season','competition','appearances','starts','minutes','goals','assists','yellow_cards','yellow_red_cards','red_cards','position','source_provider','source_url','last_verified_at'];
const dataRows=worldRows.map(row=>({...row,player_name:canonicalName(row.player_name),assists:byName.get(row.player_name)?.assists??'',source_provider:'WorldFootball.net + StatsCrew',source_url:worldUrl}));
const compareFields=['appearances','starts','minutes','goals','yellow_cards','red_cards','position'] as const;const discrepancies:Record<string,unknown>[]=[];
for(const row of dataRows){const sourceName=row.player_name==='Milan Jirasek'?'Milan Jirásek':row.player_name;const old=byName.get(sourceName)!;for(const field of compareFields){const a=old[field]??'',b=String(row[field]??'');if(a!==b)discrepancies.push({player_name:row.player_name,field,statscrew_value:a,worldfootball_value:b,selected_value:b,resolution:'WorldFootball selected for match-derived field; StatsCrew retained only for assists.',status:'resolved',evidence_url:worldUrl,note:'Complete Serie B 2009/2010 table verified in an interactive browser.'});}}
discrepancies.push({player_name:'Milan Jirasek',field:'identity',statscrew_value:'Milan Jirásek',worldfootball_value:'Milan Jirásek',selected_value:'Milan Jirasek',resolution:'Resolved to the canonical identity already present in the local database.',status:'resolved',evidence_url:worldUrl,note:'Accent-normalized alias; prevents creation of a duplicate player.'});
fs.writeFileSync(path.join(target,'worldfootball.csv'),csv(worldHeaders,worldRows),'utf8');fs.writeFileSync(path.join(target,'data.csv'),csv(dataHeaders,dataRows),'utf8');
const discrepancyHeaders=['player_name','field','statscrew_value','worldfootball_value','selected_value','resolution','status','evidence_url','note'];fs.writeFileSync(path.join(target,'discrepancies.csv'),csv(discrepancyHeaders,discrepancies),'utf8');
const goalHeaders=['date','season','competition','home_team','away_team','home_score','away_score','scoring_team','player_name','event_type','minute','source_provider','source_url','confirmation_url','last_verified_at','note'];
const goalRows=[{date:'2010-01-30',season:'2009/10',competition:'Serie B',home_team:'Sassuolo',away_team:'Salernitana',home_score:3,away_score:2,scoring_team:'Sassuolo',player_name:'Iacopo Balestri',event_type:'opponent_own_goal',minute:"36'",source_provider:'Lega Serie B archived match report',source_url:ownGoalUrl,confirmation_url:'https://it.wikipedia.org/wiki/Unione_Sportiva_Sassuolo_Calcio_2009-2010',last_verified_at:verified,note:'Balestri was a Salernitana player; the archived league report lists his own goal among the Sassuolo goals.'}];
fs.writeFileSync(path.join(target,'goal-resolution.csv'),csv(goalHeaders,goalRows),'utf8');
fs.writeFileSync(path.join(target,'roster-zero-appearances.csv'),'player_name,season,competition,roster_status,source_provider,source_url,last_verified_at,note\n','utf8');
const hash=(file:string)=>crypto.createHash('sha256').update(fs.readFileSync(path.join(target,file))).digest('hex');const dataHash=hash('data.csv');
const manifest={area:'player_seasons',season:'2009/10',competition:'Serie B',source_provider:'WorldFootball.net + StatsCrew',source_url:worldUrl,verified_at:verified,file:'data.csv',sha256:dataHash,records_total:dataRows.length,records_discarded:0,discard_reasons:[],fields_covered:dataHeaders,validation:{status:'reconciled',checks:[{name:'worldfootball_complete_extract',status:'passed',note:'27/27 rows extracted after explicitly selecting Serie B 2009/2010.'},{name:'statscrew_complete_extract',status:'passed',note:'27/27 scoring rows supplied in the external package.'},{name:'field_by_field_comparison',status:'passed',note:`${discrepancies.length} differences documented and resolved by field policy.`},{name:'player_goals_sum',status:'passed',note:'59 player goals in both sources.'},{name:'team_goals_cross_check',status:'passed',note:'60 team goals.'},{name:'own_goals_reconciled',status:'passed',note:'59 player goals + 1 opponent own goal (Iacopo Balestri, Salernitana) = 60 team goals.'},{name:'starts_total',status:'passed',note:'462 starts = 42 matches × 11.'},{name:'identities_reviewed',status:'passed',note:'All 27 identities reviewed; Milan Jirásek resolved to existing canonical name Milan Jirasek.'}],unresolved_conflicts:[]},field_source_policy:{worldfootball:['appearances','starts','minutes','goals','yellow_cards','yellow_red_cards','red_cards','position'],statscrew:['assists'],official_match_reports:['opponent_own_goal']},related_files:{worldfootball_csv_sha256:hash('worldfootball.csv'),statscrew_csv_sha256:hash('statscrew.csv'),roster_zero_appearances_csv_sha256:hash('roster-zero-appearances.csv'),discrepancies_csv_sha256:hash('discrepancies.csv'),goal_resolution_csv_sha256:hash('goal-resolution.csv')},notes:['Regular-season Serie B only; Coppa Italia and playoffs excluded.','Opponent own goals are documented separately and are not attributed to Sassuolo players.']};
fs.writeFileSync(path.join(target,'manifest.json'),JSON.stringify(manifest,null,2)+'\n','utf8');
fs.writeFileSync(path.join(target,'SOURCES.md'),`# PlayerSeason Serie B 2009/10 — riconciliato\n\nPerimetro: sola regular season di Serie B 2009/10; Coppa Italia e playoff esclusi.\n\n- WorldFootball.net (${worldUrl}): presenze, titolarità, minuti, gol, cartellini e posizione. La tabella completa di 27 giocatori è stata verificata selezionando esplicitamente “Serie B - 2009/2010”.\n- StatsCrew (${statsUrl}): assist.\n- Referto Lega Serie B archiviato (${ownGoalUrl}): autogol di Iacopo Balestri al 36' di Sassuolo–Salernitana 3-2 del 30 gennaio 2010.\n\nRiconciliazione: 59 gol attribuiti ai giocatori Sassuolo + 1 autogol avversario = 60 gol squadra. L'autogol è conservato in goal-resolution.csv e non attribuito a un giocatore Sassuolo. Tutte le differenze tra le due fonti sono documentate in discrepancies.csv.\n`,'utf8');
console.log(JSON.stringify({target,records:dataRows.length,discrepancies:discrepancies.length,appearances:dataRows.reduce((n,r)=>n+Number(r.appearances),0),starts:dataRows.reduce((n,r)=>n+Number(r.starts),0),playerGoals:dataRows.reduce((n,r)=>n+Number(r.goals),0),sha256:dataHash},null,2));
