import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';
import { db, normalizeNameForMatch } from '../server/db/database.js';

const reepRoot=path.resolve(process.argv[2]??'.tmp-reep'),candidateRoot=path.resolve(process.argv[3]??'data/reconciliation/candidates/identity-crosswalk-reep-wyscout-sassuolo-2017-18');
const rich=JSON.parse(fs.readFileSync('data/reconciliation/candidates/match-details-wyscout-serie-a-2017-18/rich-data.json','utf8'));
const wanted=new Map<string,string>();for(const match of rich.matches)for(const lineup of match.lineups)for(const row of [...lineup.startXI,...lineup.substitutes])wanted.set(String(row.player.providerId),row.player.name);
const parse=(line:string)=>{const out:string[]=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){out.push(value);value='';}else value+=c;}out.push(value);return out;};
const stream=readline.createInterface({input:fs.createReadStream(path.join(reepRoot,'data','people.csv'),{encoding:'utf8'}),crlfDelay:Infinity});let headers:string[]=[];const found=new Map<string,Record<string,string>>();
for await(const line of stream){if(!headers.length){headers=parse(line);continue;}const values=parse(line),wyscout=values[headers.indexOf('key_wyscout')];if(wyscout&&wanted.has(wyscout)){const row:Object=Object.fromEntries(headers.map((header,index)=>[header,values[index]??'']));found.set(wyscout,row as Record<string,string>);}}
const localPlayers=db.prepare('SELECT id,name,birth_date FROM players').all() as any[];
const rows=[...wanted].sort((a,b)=>a[1].localeCompare(b[1])).map(([wyscoutId,wyscoutName])=>{const reep=found.get(wyscoutId),keys=[wyscoutName,reep?.name,reep?.full_name].filter(Boolean).map(value=>normalizeNameForMatch(String(value)));const local=localPlayers.filter(player=>keys.includes(normalizeNameForMatch(player.name)));const unique=local.length===1?local[0]:null;return {provider_player_id:wyscoutId,provider_player_name:wyscoutName,reep_id:reep?.reep_id??'',reep_name:reep?.name??'',date_of_birth:reep?.date_of_birth??'',key_sofascore:reep?.key_sofascore??'',key_api_football:reep?.key_api_football??'',local_player_id:unique?.id??'',local_player_name:unique?.name??'',status:!reep?'reep_missing':unique?'unique_name_match':local.length?'ambiguous':'local_missing',confidence:unique?'reviewed_exact_name':'unresolved',source_url:'https://github.com/withqwerty/reep',last_verified_at:'2026-08-13'};});
fs.mkdirSync(candidateRoot,{recursive:true});const columns=Object.keys(rows[0]);const cell=(v:unknown)=>{const s=String(v??'');return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;};const data=[columns,...rows.map(row=>columns.map(column=>(row as any)[column]))].map(row=>row.map(cell).join(',')).join('\n')+'\n';fs.writeFileSync(path.join(candidateRoot,'data.csv'),data);
const source=path.join(reepRoot,'data','people.csv'),meta=path.join(reepRoot,'data','meta.json'),license=path.join(reepRoot,'LICENSE');for(const file of [source,meta,license])fs.copyFileSync(file,path.join(candidateRoot,'source-'+path.basename(file)));
const sha=(file:string)=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),counts=Object.fromEntries(['unique_name_match','reep_missing','ambiguous','local_missing'].map(status=>[status,rows.filter(row=>row.status===status).length]));
fs.writeFileSync(path.join(candidateRoot,'SOURCES.md'),`# Fonte e credito — Reep\n\nCrosswalk: **Reep — The football entity register**, release v0 2026.25 (21 giugno 2026), <https://github.com/withqwerty/reep>. Dati pubblicati con licenza **CC0 1.0**.\n\nReep collega gli identificativi Wyscout ad altri provider. In questo candidato il collegamento al giocatore locale è automatico soltanto quando il nome normalizzato individua una sola identità; tutte le altre righe restano irrisolte. Il file sorgente, i metadata della release e la licenza sono inclusi nel pacchetto.\n`);
const manifest={area:'player_identity_crosswalk',season:'2017/18',competition:'Serie A',source_provider:'Reep v0 2026.25',source_url:'https://github.com/withqwerty/reep',verified_at:'2026-08-13',file:'data.csv',sha256:sha(path.join(candidateRoot,'data.csv')),records_total:rows.length,records_discarded:0,counts,source_files:{'source-people.csv':sha(path.join(candidateRoot,'source-people.csv')),'source-meta.json':sha(path.join(candidateRoot,'source-meta.json')),'source-LICENSE':sha(path.join(candidateRoot,'source-LICENSE'))},validation:{status:'reconciled',checks:[{name:'provider_ids',status:'passed'},{name:'unique_local_identity_only',status:'passed'},{name:'license',status:'passed',note:'CC0 1.0 archiviata'}],unresolved_conflicts:rows.filter(row=>row.status!=='unique_name_match').map(row=>({provider_player_id:row.provider_player_id,status:row.status}))},notes:['Reep v0 è congelato; gli ID v0 non sono intercambiabili con Reep v1.','Le righe irrisolte non sono importate.']};fs.writeFileSync(path.join(candidateRoot,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');console.log(JSON.stringify({candidateRoot,records:rows.length,counts},null,2));db.close();
