import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const input=path.resolve(process.argv[2]??'.tmp-wyscout'),output=path.resolve(process.argv[3]??'data/reconciliation/candidates/match-details-wyscout-serie-a-2017-18');
const sourceUrl='https://figshare.com/collections/Soccer_match_event_dataset/4415000',verifiedAt='2026-08-13',sassuoloId=3315;
const sha=(file:string)=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),read=(file:string)=>JSON.parse(fs.readFileSync(file,'utf8'));
const csv=(value:unknown)=>{const s=value==null?'':String(value);return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;};
const players=read(path.join(input,'players.json')) as any[],teams=read(path.join(input,'teams.json')) as any[],matches=(read(path.join(input,'matches','matches_Italy.json')) as any[]).filter(match=>match.teamsData?.[sassuoloId]);
const allEvents=read(path.join(input,'events','events_Italy.json')) as any[];
if(matches.length!==38)throw new Error(`Attese 38 gare Sassuolo, trovate ${matches.length}`);
const playerById=new Map(players.map(player=>[player.wyId,player])),teamById=new Map(teams.map(team=>[team.wyId,team]));
const name=(id:number)=>{const p=playerById.get(id);return p?[p.firstName,p.middleName,p.lastName].filter(Boolean).join(' ').replace(/\\u([0-9a-f]{4})/gi,(_,x)=>String.fromCharCode(parseInt(x,16))):`Wyscout player ${id}`;};
const has=(event:any,tag:number)=>event.tags?.some((row:any)=>row.id===tag);
const minute=(event:any)=>Math.floor(Number(event.eventSec??0)/60)+(event.matchPeriod==='2H'?45:event.matchPeriod==='E1'?90:event.matchPeriod==='E2'?105:0);
const byMatch=new Map<number,any[]>();for(const event of allEvents){if(!matches.some(match=>match.wyId===event.matchId))continue;const rows=byMatch.get(event.matchId)??[];rows.push(event);byMatch.set(event.matchId,rows);}
const richMatches=matches.sort((a,b)=>String(a.dateutc).localeCompare(String(b.dateutc))).map(match=>{
  const sides=Object.values(match.teamsData) as any[],home=sides.find(team=>team.side==='home'),away=sides.find(team=>team.side==='away');if(!home||!away)throw new Error(`${match.wyId}: squadre mancanti`);
  const teamName=(id:number)=>teamById.get(id)?.name??String(id),events=(byMatch.get(match.wyId)??[]).sort((a,b)=>a.matchPeriod.localeCompare(b.matchPeriod)||a.eventSec-b.eventSec||a.id-b.id);
  const lineups=[home,away].map(team=>{const formation=team.formation??{};const row=(entry:any)=>({player:{id:`wyscout:${entry.playerId}`,providerId:entry.playerId,name:name(entry.playerId),number:null,pos:playerById.get(entry.playerId)?.role?.code2??null}});return {teamId:team.teamId,teamName:teamName(team.teamId),formation:'',coachName:null,coachProviderId:team.coachId??null,startXI:(formation.lineup??[]).map(row),substitutes:(formation.bench??[]).map(row)};});
  if(lineups.some(lineup=>lineup.startXI.length!==11))throw new Error(`${match.wyId}: XI incompleto`);
  const rawGoals=events.filter(event=>(has(event,101)&&(event.eventName==='Shot'||event.eventName==='Free Kick'))||has(event,102));
  const rawCards=events.filter(event=>has(event,1701)||has(event,1702)||has(event,1703));
  const rawSubs=sides.flatMap(team=>(team.formation?.substitutions??[]).map((sub:any,index:number)=>({id:`${match.wyId}:sub:${team.teamId}:${index}`,eventSec:(Number(sub.minute)>45?Number(sub.minute)-45:Number(sub.minute))*60,matchPeriod:Number(sub.minute)>45?'2H':'1H',teamId:team.teamId,playerId:sub.playerOut,replacementId:sub.playerIn,substitution:true})));
  let homeScore=0,awayScore=0;
  const keyEvents=[...rawGoals,...rawCards,...rawSubs].sort((a,b)=>minute(a)-minute(b)||Number(a.eventSec)-Number(b.eventSec)).map((event,index)=>{
    const goal=rawGoals.includes(event),ownGoal=goal&&has(event,102),scoringTeamId=ownGoal?(event.teamId===home.teamId?away.teamId:home.teamId):event.teamId;
    if(goal){if(scoringTeamId===home.teamId)homeScore++;else awayScore++;}
    const sourceIndex=events.indexOf(event),assist=goal&&!ownGoal?events.slice(Math.max(0,sourceIndex-5),sourceIndex).reverse().find(row=>row.teamId===event.teamId&&has(row,301)):null;
    const card=has(event,1702)?'Red Card':has(event,1703)?'Second Yellow':has(event,1701)?'Yellow Card':null;
    return {providerEventId:String(event.id),sequenceNumber:index,minute:minute(event),extraMinute:null,teamId:event.teamId,teamName:teamName(event.teamId),scoringTeamName:goal?teamName(scoringTeamId):null,playerId:event.playerId??null,playerName:event.playerId?name(event.playerId):null,assistPlayerId:event.substitution?event.replacementId:assist?.playerId??null,assistName:event.substitution?name(event.replacementId):assist?.playerId?name(assist.playerId):null,type:goal?'Goal':event.substitution?'Substitution':'Card',detail:ownGoal?'Own Goal':goal?event.subEventName||'Goal':event.substitution?'Player change':card,isOwnGoal:ownGoal?1:0,scoringPlay:goal?1:0,homeScore:goal?homeScore:null,awayScore:goal?awayScore:null};
  });
  if(homeScore!==Number(home.score)||awayScore!==Number(away.score))throw new Error(`${match.wyId}: gol ${homeScore}-${awayScore}, risultato ${home.score}-${away.score}`);
  const shots=events.filter(event=>event.eventName==='Shot'||event.eventName==='Free Kick'&&['Penalty','Free kick shot'].includes(event.subEventName)).map(event=>({providerEventId:String(event.id),minute:minute(event),second:Math.floor(Number(event.eventSec??0)%60),teamId:event.teamId,teamName:teamName(event.teamId),playerId:event.playerId||null,playerName:event.playerId?name(event.playerId):null,outcome:has(event,101)?'Goal':has(event,1801)?'Saved':'Off Target',goal:has(event,101),onTarget:has(event,101)||has(event,1801),xg:null,bodyPart:has(event,401)?'Left Foot':has(event,402)?'Right Foot':has(event,403)?'Head/body':null,shotType:event.subEventName,location:event.positions?.[0]??null,endLocation:event.positions?.[1]??null}));
  return {providerMatchId:String(match.wyId),date:String(match.dateutc).slice(0,10),kickOff:String(match.dateutc).slice(11),matchWeek:match.gameweek,homeTeam:{id:home.teamId,name:teamName(home.teamId)},awayTeam:{id:away.teamId,name:teamName(away.teamId)},homeScore:home.score,awayScore:away.score,stadium:String(match.venue??'').replace(/\\u00e0/g,'à')||null,referee:null,lineups,events:keyEvents,shots};
});

fs.mkdirSync(path.join(output,'source-files'),{recursive:true});
for(const file of ['players.json','teams.json','matches_Italy.zip','events_Italy.zip'])fs.copyFileSync(path.join(input,file),path.join(output,'source-files',file));
const index:any={};for(const [file,url] of [['players.json','https://ndownloader.figshare.com/files/15073721'],['teams.json','https://ndownloader.figshare.com/files/15073697'],['matches_Italy.zip','https://ndownloader.figshare.com/files/14464622'],['events_Italy.zip','https://ndownloader.figshare.com/files/14464685']]){const target=path.join(output,'source-files',file);index[file]={url,sha256:sha(target),bytes:fs.statSync(target).size};}
const rich={schemaVersion:1,season:'2017/18',competition:'Serie A',sourceProvider:'Wyscout Soccer Match Event Dataset',sourceUrl,lastVerifiedAt:verifiedAt,matches:richMatches};
fs.writeFileSync(path.join(output,'rich-data.json'),JSON.stringify(rich,null,2)+'\n');fs.writeFileSync(path.join(output,'source-index.json'),JSON.stringify(index,null,2)+'\n');
const headers=['match_date','home_team','away_team','home_score','away_score','stadium','provider_match_id','lineups','key_events','shots','source_provider','source_url','last_verified_at'];const rows=richMatches.map(match=>[match.date,match.homeTeam.name,match.awayTeam.name,match.homeScore,match.awayScore,match.stadium,match.providerMatchId,match.lineups.length,match.events.length,match.shots.length,rich.sourceProvider,rich.sourceUrl,rich.lastVerifiedAt]);fs.writeFileSync(path.join(output,'data.csv'),[headers,...rows].map(row=>row.map(csv).join(',')).join('\n')+'\n');
fs.writeFileSync(path.join(output,'aliases.csv'),'source_name,canonical_name,entity_type\nInternazionale,Inter,team\nSassuolo,U.S. Sassuolo Calcio,team\n');fs.writeFileSync(path.join(output,'discrepancies.csv'),'field,source_value,canonical_value,status,resolution\nhome_team,Sassuolo,U.S. Sassuolo Calcio,resolved,Alias locale\nteam_name,Internazionale,Inter,resolved,Alias locale\n');
fs.writeFileSync(path.join(output,'SOURCES.md'),`# Fonti e crediti — Wyscout Serie A 2017/18\n\nFonte: **Soccer match event dataset**, Luca Pappalardo et al., pubblicato su Figshare e distribuito con licenza **CC BY 4.0**: <${sourceUrl}>.\n\nCitazione accademica: Pappalardo, L. et al. (2019), *A public data set of spatio-temporal match events in soccer competitions*, Scientific Data 6, 236. DOI: <https://doi.org/10.1038/s41597-019-0247-7>.\n\nGli URL, SHA-256 e file originali sono conservati in \`source-index.json\` e \`source-files/\`. Le statistiche di tiro sono derivate dagli eventi pubblicati; il dataset non fornisce xG, quindi il campo resta N/D.\n`);
const dataPath=path.join(output,'data.csv'),richPath=path.join(output,'rich-data.json'),indexPath=path.join(output,'source-index.json');const totals=richMatches.reduce((sum,match)=>({keyEvents:sum.keyEvents+match.events.length,shots:sum.shots+match.shots.length,players:sum.players+match.lineups.reduce((n,lineup)=>n+lineup.startXI.length+lineup.substitutes.length,0)}),{keyEvents:0,shots:0,players:0});
const manifest={area:'match_details_wyscout_season',season:'2017/18',competition:'Serie A',source_provider:rich.sourceProvider,source_url:sourceUrl,verified_at:verifiedAt,file:'data.csv',sha256:sha(dataPath),rich_file:'rich-data.json',rich_sha256:sha(richPath),source_index:'source-index.json',source_index_sha256:sha(indexPath),records_total:38,records_discarded:0,fields_covered:['venue','lineups','goals','cards','substitutions','shots','event_locations'],counts:{matches:38,...totals,raw_files:4},validation:{status:'reconciled',checks:[{name:'fixture_count',status:'passed',note:'38/38 gare Sassuolo'},{name:'starting_xi',status:'passed',note:'Due XI da 11 per gara'},{name:'goal_reconciliation',status:'passed',note:'Gol, inclusi autogol, coerenti coi risultati'},{name:'source_attribution',status:'passed',note:'CC BY 4.0, autori, DOI e URL inclusi'}],unresolved_conflicts:[]},notes:['xG non presente nella fonte: resta N/D.','Arbitri disponibili solo come identificativi, non importati come nomi.']};fs.writeFileSync(path.join(output,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');
console.log(JSON.stringify({output,records:38,...totals},null,2));
