import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { db, normalizeNameForMatch, nowIso, recordSourceReference } from '../db/database.js';

type Candidate={candidate_path:string;season:string;competition:string;source_provider?:string|null};
type Issue={row:number;field:string|null;code:string;message:string;critical:boolean};
const hash=(file:string)=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const same=(expected:unknown,actual:string)=>/^[a-f0-9]{64}$/i.test(String(expected??''))&&String(expected).toLowerCase()===actual.toLowerCase();
const read=(dir:string)=>{const manifest=JSON.parse(fs.readFileSync(path.join(dir,'manifest.json'),'utf8'));const richPath=path.join(dir,manifest.rich_file||'rich-data.json');return {manifest,rich:JSON.parse(fs.readFileSync(richPath,'utf8')),richPath};};
const fixtureFor=(season:string,competition:string,match:any)=>{
  const rows=db.prepare(`SELECT * FROM matches WHERE season=? AND competition=? AND substr(date,1,10)=?`).all(season,competition,String(match.date).slice(0,10)) as any[];
  const scored=rows.filter(row=>Number(row.home_score)===Number(match.homeScore)&&Number(row.away_score)===Number(match.awayScore));
  return scored.length===1?scored[0]:rows.length===1?rows[0]:null;
};
const localPlayerId=(name:string)=>{const key=normalizeNameForMatch(name);const rows=(db.prepare('SELECT id,name FROM players').all() as any[]).filter(row=>normalizeNameForMatch(row.name)===key);return rows.length===1?rows[0].id:null;};

export function previewOpenDataSeasonCandidate(dir:string,candidate:Candidate){
  const issues:Issue[]=[];let manifest:any,rich:any,richPath:string;
  try{({manifest,rich,richPath}=read(dir));}catch(error){return {entity:'open-data-season',filename:'data.csv',checksum:'',format:'csv',rows:0,validRows:0,created:0,updated:0,skipped:0,conflicts:0,errors:1,canApply:false,issues:[{row:0,field:null,code:'invalid_package',message:String(error),critical:true}]};}
  const dataHash=hash(path.join(dir,'data.csv'));
  if(!same(manifest.sha256,dataHash))issues.push({row:0,field:'data.csv',code:'checksum_mismatch',message:'Checksum data.csv non valido',critical:true});
  if(!same(manifest.rich_sha256,hash(richPath)))issues.push({row:0,field:manifest.rich_file,code:'checksum_mismatch',message:'Checksum rich-data non valido',critical:true});
  if(manifest.source_index){const file=path.join(dir,manifest.source_index);if(!fs.existsSync(file)||!same(manifest.source_index_sha256,hash(file)))issues.push({row:0,field:manifest.source_index,code:'source_index_checksum',message:'Indice delle fonti non valido',critical:true});}
  if(manifest.raw_archive){const file=path.join(dir,manifest.raw_archive.file);if(!fs.existsSync(file)||!same(manifest.raw_archive.sha256,hash(file)))issues.push({row:0,field:manifest.raw_archive.file,code:'raw_checksum',message:'Archivio raw non valido',critical:true});}
  if(rich.season!==candidate.season||rich.competition!==candidate.competition)issues.push({row:0,field:null,code:'scope_mismatch',message:'Perimetro candidato non coerente',critical:true});
  if(!rich.sourceProvider||!rich.sourceUrl)issues.push({row:0,field:'source',code:'missing_source',message:'Fonte o URL mancanti',critical:true});
  let created=0,updated=0,skipped=0;
  for(let i=0;i<(rich.matches??[]).length;i++){
    const match=rich.matches[i],fixture=fixtureFor(rich.season,rich.competition,match),row=i+2;
    if(!fixture){issues.push({row,field:null,code:'fixture_not_found',message:`Fixture non univoca: ${match.date} ${match.homeTeam?.name}-${match.awayTeam?.name}`,critical:true});continue;}
    if(Number(fixture.home_score)!==Number(match.homeScore)||Number(fixture.away_score)!==Number(match.awayScore))issues.push({row,field:null,code:'score_conflict',message:'Risultato in conflitto con la fixture canonica',critical:true});
    const goalEvents=(match.events??[]).filter((event:any)=>event.type==='Goal');
    if(goalEvents.length!==Number(match.homeScore)+Number(match.awayScore))issues.push({row,field:'events',code:'goal_mismatch',message:'Gol evento non coerenti col risultato',critical:true});
    if((match.lineups??[]).length!==2||(match.lineups??[]).some((lineup:any)=>lineup.startXI?.length!==11))issues.push({row,field:'lineups',code:'invalid_lineups',message:'Formazioni iniziali incomplete',critical:true});
    const counts={details:Number((db.prepare('SELECT count(*) c FROM match_details WHERE match_id=?').get(fixture.id) as any).c),lineups:Number((db.prepare('SELECT count(*) c FROM match_lineups WHERE match_id=? AND source_provider=?').get(fixture.id,rich.sourceProvider) as any).c),events:Number((db.prepare('SELECT count(*) c FROM match_events WHERE match_id=? AND source_provider=?').get(fixture.id,rich.sourceProvider) as any).c),teamStats:Number((db.prepare('SELECT count(*) c FROM match_team_stats WHERE match_id=? AND source_provider=?').get(fixture.id,rich.sourceProvider) as any).c)};
    created+=(counts.details?0:1)+Math.max(0,2-counts.lineups)+Math.max(0,(match.events??[]).length-counts.events)+Math.max(0,2-counts.teamStats);updated++;skipped+=counts.details+counts.lineups+counts.events+counts.teamStats;
  }
  if((rich.matches??[]).length!==Number(manifest.records_total))issues.push({row:0,field:null,code:'record_count',message:'Conteggio manifest diverso dai dati ricchi',critical:true});
  if((manifest.validation?.unresolved_conflicts??[]).length)issues.push({row:0,field:null,code:'unresolved_conflicts',message:'Conflitti irrisolti nel manifest',critical:true});
  const errors=issues.filter(issue=>issue.critical).length;
  return {entity:'open-data-season',filename:'data.csv',checksum:dataHash,format:'csv',rows:rich.matches?.length??0,validRows:errors?0:rich.matches.length,created,updated,skipped,conflicts:issues.filter(issue=>issue.code.includes('conflict')).length,errors,canApply:errors===0,issues,counts:manifest.counts??{}};
}

export function importOpenDataSeasonCandidate(dir:string,candidate:Candidate){
  const preview=previewOpenDataSeasonCandidate(dir,candidate);if(!preview.canApply)throw new Error(`Import open data bloccato: ${preview.errors} errori`);
  const {rich}=read(dir);let details=0,lineups=0,events=0,teamStats=0,playerStats=0,references=0;
  const addReference=(entityId:number,field:string,value:unknown)=>{if(db.prepare(`SELECT 1 FROM source_references WHERE entity_type='matches' AND entity_id=? AND field=? AND source_provider=? AND source_url=?`).get(entityId,field,rich.sourceProvider,rich.sourceUrl))return;recordSourceReference({entityType:'matches',entityId,field,sourceUrl:rich.sourceUrl,sourceProvider:rich.sourceProvider,originalValue:String(value),transformation:`${rich.sourceProvider}:open-data-events`,verifiedAt:rich.lastVerifiedAt});references++;};
  db.transaction(()=>{for(const match of rich.matches){
    const fixture=fixtureFor(rich.season,rich.competition,match);if(!fixture)throw new Error(`Fixture non trovata: ${match.date}`);
    const providerMatchId=String(match.providerMatchId),apiFixtureId=-Math.abs(Number(providerMatchId));if(!Number.isSafeInteger(apiFixtureId)||!apiFixtureId)throw new Error(`ID provider non valido: ${providerMatchId}`);
    db.prepare(`UPDATE matches SET stadium=COALESCE(stadium,?),referee=COALESCE(referee,?),shots_home=COALESCE(shots_home,?),shots_away=COALESCE(shots_away,?),shots_on_target_home=COALESCE(shots_on_target_home,?),shots_on_target_away=COALESCE(shots_on_target_away,?),xg_home=COALESCE(xg_home,?),xg_away=COALESCE(xg_away,?),last_verified_at=? WHERE id=?`).run(match.stadium??null,match.referee??null,...teamNumbers(match),rich.lastVerifiedAt,fixture.id);
    for(const [field,value] of [['stadium',match.stadium],['referee',match.referee],['shots/xg',JSON.stringify(teamNumbers(match))]] as const)if(value!=null&&value!=='')addReference(fixture.id,field,value);
    if(!(db.prepare('SELECT 1 FROM match_details WHERE match_id=?').get(fixture.id))){db.prepare(`INSERT INTO match_details(match_id,api_fixture_id,source_provider,provider_match_id,status_long,status_short,venue_name,league_name,league_country,league_round,home_team_provider_id,home_team_name,away_team_provider_id,away_team_name,goals_home,goals_away,fulltime_home,fulltime_away,events_synced,lineups_synced,team_stats_synced,player_stats_synced,venue_synced,last_verified_at) VALUES(${Array.from({length:24},()=>'?').join(',')})`).run(fixture.id,apiFixtureId,rich.sourceProvider,providerMatchId,'Match Finished','FT',match.stadium,'Serie A','Italy',`Giornata ${match.matchWeek??''}`,String(match.homeTeam.id),match.homeTeam.name,String(match.awayTeam.id),match.awayTeam.name,match.homeScore,match.awayScore,match.homeScore,match.awayScore,1,1,1,1,match.stadium?1:0,rich.lastVerifiedAt);details++;}
    const insertLineup=db.prepare(`INSERT OR IGNORE INTO match_lineups(match_id,api_fixture_id,source_provider,provider_match_id,provider_team_id,team_api_id,team_name,formation,coach_name,start_xi_json,substitutes_json,raw_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`);
    for(const lineup of match.lineups??[]){const enrich=(rows:any[])=>rows.map(row=>({...row,player:{...row.player,localPlayerId:row.player?.name?localPlayerId(row.player.name):null}}));lineups+=insertLineup.run(fixture.id,apiFixtureId,rich.sourceProvider,providerMatchId,String(lineup.teamId),-Math.abs(Number(lineup.teamId)),lineup.teamName,lineup.formation||null,lineup.coachName??null,JSON.stringify(enrich(lineup.startXI)),JSON.stringify(enrich(lineup.substitutes)),JSON.stringify(lineup)).changes;}
    const exists=db.prepare(`SELECT 1 FROM match_events WHERE match_id=? AND source_provider=? AND provider_event_id=?`),insertEvent=db.prepare(`INSERT INTO match_events(match_id,api_fixture_id,source_provider,provider_match_id,provider_event_id,sequence_number,minute,extra_minute,team_provider_id,team_api_id,team_name,player_provider_id,player_api_id,player_id,player_name,assist_player_provider_id,assist_player_api_id,assist_player_id,assist_name,type,detail,scoring_play,home_score,away_score,scoring_team_name,is_own_goal,source_url,verification_note,verified_by,last_verified_at) VALUES(${Array.from({length:30},()=>'?').join(',')})`);
    for(const event of match.events??[]){if(exists.get(fixture.id,rich.sourceProvider,String(event.providerEventId)))continue;const p=event.playerId==null?null:-Math.abs(Number(event.playerId)),a=event.assistPlayerId==null?null:-Math.abs(Number(event.assistPlayerId));events+=insertEvent.run(fixture.id,apiFixtureId,rich.sourceProvider,providerMatchId,String(event.providerEventId),event.sequenceNumber??null,event.minute??null,event.extraMinute??null,event.teamId==null?null:String(event.teamId),event.teamId==null?null:-Math.abs(Number(event.teamId)),event.teamName??null,event.playerId==null?null:String(event.playerId),p,event.playerName?localPlayerId(event.playerName):null,event.playerName??null,event.assistPlayerId==null?null:String(event.assistPlayerId),a,event.assistName?localPlayerId(event.assistName):null,event.assistName??null,event.type,event.detail??null,event.scoringPlay??0,event.homeScore??null,event.awayScore??null,event.scoringTeamName??event.teamName??null,event.isOwnGoal??0,rich.sourceUrl,'Evento normalizzato dal dataset open data indicato.','DATA-01 open data',rich.lastVerifiedAt).changes;}
    const teamAgg=aggregateTeams(match),insertTeam=db.prepare(`INSERT OR IGNORE INTO match_team_stats(match_id,source_provider,provider_match_id,api_fixture_id,provider_team_id,team_api_id,team_name,stats_json,raw_json) VALUES(?,?,?,?,?,?,?,?,?)`);
    for(const team of teamAgg){teamStats+=insertTeam.run(fixture.id,rich.sourceProvider,providerMatchId,apiFixtureId,String(team.teamId),-Math.abs(Number(team.teamId)),team.teamName,JSON.stringify(team.stats),JSON.stringify({derivedFrom:'shots',source:rich.sourceUrl})).changes;}
    const playerAgg=aggregatePlayers(match),insertPlayer=db.prepare(`INSERT OR IGNORE INTO match_player_stats(match_id,source_provider,provider_match_id,api_fixture_id,provider_team_id,team_api_id,team_name,player_id,provider_player_id,api_football_player_id,player_name,shots_total,shots_on,goals,statistics_json) VALUES(${Array.from({length:15},()=>'?').join(',')})`);
    for(const player of playerAgg){playerStats+=insertPlayer.run(fixture.id,rich.sourceProvider,providerMatchId,apiFixtureId,String(player.teamId),-Math.abs(Number(player.teamId)),player.teamName,localPlayerId(player.playerName),String(player.playerId),-Math.abs(Number(player.playerId)),player.playerName,player.shots,player.onTarget,player.goals,JSON.stringify({shots:{total:player.shots,on:player.onTarget},goals:{total:player.goals},expected_goals:player.xg,derivedFrom:'open-data shot events',source:rich.sourceUrl})).changes;}
  }})();
  return {created:details+lineups+events+teamStats+playerStats,updated:rich.matches.length,skipped:preview.skipped,details,lineups,events,teamStats,playerStats,provenanceReferences:references,importedAt:nowIso()};
}

function aggregateTeams(match:any){return [match.homeTeam,match.awayTeam].map((team:any)=>{const shots=(match.shots??[]).filter((shot:any)=>String(shot.teamId)===String(team.id));return {teamId:team.id,teamName:team.name,stats:[{type:'Total Shots',value:shots.length},{type:'Shots on Goal',value:shots.filter((shot:any)=>['Goal','Saved','Saved to Post'].includes(shot.outcome)||shot.onTarget).length},{type:'Expected Goals',value:shots.some((shot:any)=>shot.xg!=null)?shots.reduce((n:number,shot:any)=>n+Number(shot.xg??0),0):null}]};});}
function teamNumbers(match:any){const teams=aggregateTeams(match);const value=(index:number,type:string)=>teams[index].stats.find(row=>row.type===type)?.value??null;return [value(0,'Total Shots'),value(1,'Total Shots'),value(0,'Shots on Goal'),value(1,'Shots on Goal'),value(0,'Expected Goals'),value(1,'Expected Goals')];}
function aggregatePlayers(match:any){const map=new Map<string,any>();for(const shot of match.shots??[]){if(!shot.playerId||!shot.playerName)continue;const key=`${shot.teamId}:${shot.playerId}`,row=map.get(key)??{teamId:shot.teamId,teamName:shot.teamName,playerId:shot.playerId,playerName:shot.playerName,shots:0,onTarget:0,goals:0,xg:0};row.shots++;if(['Goal','Saved','Saved to Post'].includes(shot.outcome)||shot.onTarget)row.onTarget++;if(shot.outcome==='Goal'||shot.goal)row.goals++;row.xg+=Number(shot.xg??0);map.set(key,row);}return [...map.values()];}
