import { lazy, Suspense, type ComponentType, type LazyExoticComponent } from 'react';
import { Route, Routes } from 'react-router-dom';
import AppLayout from './layouts/AppLayout'; import { Loading, WidgetBoundary } from './components/Ui';
const PlayerIdentityManager=lazy(()=>import('./pages/PlayerIdentityManager'));
const Favorites=lazy(()=>import('./pages/Favorites'));
const CurrentSeason=lazy(()=>import('./pages/CurrentSeason'));
const Coaches=lazy(()=>import('./pages/Coaches'));const Corrections=lazy(()=>import('./pages/Corrections'));
const Club=lazy(()=>import('./pages/Club')); const Dashboard=lazy(()=>import('./pages/Dashboard')); const Seasons=lazy(()=>import('./pages/Seasons')); const SeasonDetail=lazy(()=>import('./pages/SeasonDetail')); const Matches=lazy(()=>import('./pages/Matches')); const MatchDetail=lazy(()=>import('./pages/MatchDetail')); const HeadToHead=lazy(()=>import('./pages/HeadToHead')); const Players=lazy(()=>import('./pages/Players')); const PlayerDetail=lazy(()=>import('./pages/PlayerDetail')); const HallOfFame=lazy(()=>import('./pages/HallOfFame')); const Records=lazy(()=>import('./pages/Records')); const CurrentSquad=lazy(()=>import('./pages/CurrentSquad')); const News=lazy(()=>import('./pages/News')); const DataManager=lazy(()=>import('./pages/DataManager')); const ManualEditor=lazy(()=>import('./pages/ManualEditor')); const Transfers=lazy(()=>import('./pages/Transfers')); const Compare=lazy(()=>import('./pages/Compare')); const Timeline=lazy(()=>import('./pages/Timeline')); const Methodology=lazy(()=>import('./pages/Methodology'));
const page=(C:LazyExoticComponent<ComponentType>)=><WidgetBoundary label="La pagina"><Suspense fallback={<Loading/>}><C/></Suspense></WidgetBoundary>;
export default function App(){return <Routes><Route element={<AppLayout/>}><Route index element={page(Club)}/><Route path="dashboard" element={page(Dashboard)}/><Route path="current-season" element={page(CurrentSeason)}/><Route path="seasons" element={page(Seasons)}/><Route path="seasons/:season" element={page(SeasonDetail)}/><Route path="matches" element={page(Matches)}/><Route path="matches/:id" element={page(MatchDetail)}/><Route path="h2h" element={page(HeadToHead)}/><Route path="players" element={page(Players)}/><Route path="players/:id" element={page(PlayerDetail)}/><Route path="compare" element={page(Compare)}/><Route path="timeline" element={page(Timeline)}/><Route path="coaches" element={page(Coaches)}/><Route path="corrections" element={page(Corrections)}/><Route path="methodology" element={page(Methodology)}/><Route path="favorites" element={page(Favorites)}/><Route path="hall-of-fame" element={page(HallOfFame)}/><Route path="records" element={page(Records)}/><Route path="squad" element={page(CurrentSquad)}/><Route path="transfers" element={page(Transfers)}/><Route path="news" element={page(News)}/><Route path="data-manager/identities" element={page(PlayerIdentityManager)}/><Route path="data-manager" element={page(DataManager)}/><Route path="data-manager/manual" element={page(ManualEditor)}/><Route path="*" element={<EmptyRoute/>}/></Route></Routes>}
function EmptyRoute(){return <ErrorState404/>}
function ErrorState404(){return <div className="card p-8 text-center"><h1 className="text-2xl font-black">Pagina non trovata</h1><p className="mt-2 text-zinc-400">La route richiesta non esiste o non è più disponibile.</p></div>}
