import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import './index.css';
import { ExperienceProvider } from './context/ExperienceContext';
import { MuseumProvider } from './context/MuseumContext';
import { installFrontendTelemetry } from './services/telemetry';
import { loadDatasetRelease } from './services/datasetRelease';
import { registerAppUpdates } from './services/appUpdate';
installFrontendTelemetry();
loadDatasetRelease();
registerAppUpdates();
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><ExperienceProvider><MuseumProvider><App/></MuseumProvider></ExperienceProvider></BrowserRouter></React.StrictMode>);
